### ISSUE TITLE
safe handling of duplicate register_application requests

### ISSUE THREAD

**Issue by sueann** [ucbrise/clipper#112]
Q: what happens if you try to register the same application twice (same name)?

A: The update will overwrite the old application with the new one. I think the place this will cause problems is you will have multiple query handlers registered to the same REST endpoint and I'm not sure which one will get called. We should probably prevent this from happening (which is a 2 line code change).

**Comment by dcrankshaw** [comment]
Fixed by #115. Clipper now throws an error if you try to register an application with the same name twice.
