### ISSUE TITLE
boost error when executing make

### ISSUE THREAD

**Issue by AirAI** [ucbrise/clipper#124]
I could successfully `make` the  old clipper source code (cloned on March). But I came across the following boost error when  I executed `make`  instruction after I updated the new clipper source code today.

../libclipper/libclipper.a(query_processor.cpp.o): In function `boost::detail::shared_state_base::set_exception_at_thread_exit(boost::exception_ptr)':
/home/guest/tools/boost-1.60.0/include/boost-1_60/boost/thread/future.hpp:434: undefined reference to `boost::detail::make_ready_at_thread_exit(boost::shared_ptr<boost::detail::shared_state_base>)'
../libclipper/libclipper.a(query_processor.cpp.o): In function `boost::detail::shared_state<void>::set_value_at_thread_exit()':
/home/guest/tools/boost-1.60.0/include/boost-1_60/boost/thread/future.hpp:791: undefined reference to `boost::detail::make_ready_at_thread_exit(boost::shared_ptr<boost::detail::shared_state_base>)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/frontends/query_frontend] Error 1
make[1]: *** [src/frontends/CMakeFiles/query_frontend.dir/all] Error 2
make: *** [all] Error 2

**Comment by dcrankshaw** [comment]
The build is passing so this is likely a problem with your environment. Here are some debugging steps to try.

1. Run `./configure --cleanup` to fully clean the repository.
2. Run `git submodule update --init && git submodule update --checkout` to make sure all the Git submodules are fully synced.
3. Try building with vagrant (there are instructions in the README) which has all of the correct dependencies. If the vagrant build works fine, then it is likely a problem with one of your dependencies (maybe Boost based on the output you selected).
