### ISSUE TITLE
dowload_cifar not working on python3

### ISSUE THREAD

**Issue by lucasmoura** [ucbrise/clipper#132]
Because of how **urllib** is being used, the **download_cifar** script is not working on python 3, since URLOpener is not availabe since python 3.3. 

Should we add support to python 3 to the files related to the tutorials, or just inform that the user should run them with python 2 ?

**Comment by dcrankshaw** [comment]
I don't have much experience with Python 3. How hard is it to make the tutorial support both Python 2 and 3?

**Comment by lucasmoura** [comment]
I have looked at some python files that are being used in the tutorial and it doesn't seem that hard to make it compatible with Python 3 as well. I will start working on that

**Comment by dcrankshaw** [comment]
That would be great. Can you create a GitHub issue for making Clipper Python 3 compatible and assign it to yourself?

**Comment by lucasmoura** [comment]
Okay, I will close this issue and create a new one

**Comment by lucasmoura** [comment]
@dcrankshaw I don't think I can assign myself to the issue using github, since I don't have the necessary permissions, but I will say in the issue that I will be working on it.
