### ISSUE TITLE
Make Clipper compatible with Python 3

### ISSUE THREAD

**Issue by lucasmoura** [ucbrise/clipper#138]
While running the tutorials, I realized that Clipper is not supporting Python 3. It will be necessary to update the python files to add support to Python 3 while also maintaining support for Python 2.

It will also be necessary to check the dependencies of the project. For example, [fabric](https://github.com/fabric/fabric) is only available for Python 2.

**Comment by lucasmoura** [comment]
I will be working on that issue and I will report any problems that I can find

**Comment by dcrankshaw** [comment]
This is still a relevant issue. As we refactor the Clipper admin to make it more modular and add support for Kubernetes, we will remove the dependency on fabric which is not Python 3 compatible.

**Comment by simon-mo** [comment]
Hi @jwirjo 

The latest development is just to add version specification in package dependency for pip packaging in pull request #311. You just need to add these files to your branch: https://github.com/ucbrise/clipper/pull/311/files

Here’s few things I researched that might be helpful:
* A great resource:
    * Instagram’s 2to3 lessons: https://youtu.be/66XoCk79kjM?t=1487
    * Use ensure_byte(), ensure_string(), etc, abstraction. 
* Don’t forget to update integration tests for python2 and make separate (maybe?) case for python3. https://github.com/ucbrise/clipper/tree/develop/integration-tests
* The byte string conversion commonly appears in:
    * RPC.py
    * Python Model Deployer:
        * In clipper_admin/clipper_admin/deployers/python.py, add sys.version specification.

**Comment by jwirjo** [comment]
1.) Make clipper_admin Python 3 compatible.
2.) Make rpc.py Python 3 compatible. 
3.) Make Python 3 version of Python Closure Dockerfile & RPC Dockerfile. (make sure all dependencies are python3 compatible)
4.) Modify integration tests: clipper_admin_tests.py

**Comment by simon-mo** [comment]
Just reminded me:
- yapf python formatter and linter expect different syntax behavior for different python version. (Something I struggled a lot in PR #356) If we are doing this, we should all format the code using same python version (since bin/format_code.sh) use the python that’s in your PATH.

**Comment by dcrankshaw** [comment]
@jwirjo you may find this guide on creating packages for PyPy helpful when converting the Python package to be both 2 and 3 compatible:

https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

**Comment by dcrankshaw** [comment]
@jwirjo [here are some instructions](https://gist.github.com/dcrankshaw/1207956669768c8b31adffb122923b12) for running a model container outside of Docker in a standalone process for debugging `rpc.py`.

**Comment by dcrankshaw** [comment]
@jwirjo now that you've made `rpc.py` Python 3 compatible, here are the next steps:
1) Create Python 3 versions of [RPCDockerfile](https://github.com/ucbrise/clipper/blob/develop/dockerfiles/RPCDockerfile) and [`PyClosureDockerFile`](https://github.com/ucbrise/clipper/blob/develop/dockerfiles/PyClosureContainerDockerfile). `RPCPy3Dockerfile` should replace the base image in [this line](https://github.com/ucbrise/clipper/blob/5fd16eb776df9d1193320bad21ae49d3b9da5793/dockerfiles/RPCDockerfile#L3) with `continuumio/anaconda3:latest`.
2) Add the logic in `deploy_python_closure` that checks for the current version of Python and sets the `base_image` argument to the Python 3 version if in Python 3 and the Python 2 version if in Python 2. You can use `sys.version_info` to check for which Python version is running.
3) Check the Clipper admin Python package for Python 3 compatibility and modify `setup.py` to build a wheel. See @simon-mo's [earlier comment](https://github.com/ucbrise/clipper/issues/138#issuecomment-348595831) and previous PR (#311).

Once you've done these things, check back in with me and we'll discuss how to run the integration tests in both Python 2 and 3.
