### ISSUE TITLE
is the tutorial supposed to work?

### ISSUE THREAD

**Issue by miramar-labs** [ucbrise/clipper#141]

**Comment by Corey-Zumar** [comment]
@miramar-labs Yes, what's the issue you're facing?

**Comment by miramar-labs** [comment]
i'm fairly new to jupyter notebooks but I cloned the sources, went through the steps and brought up the first tutorial .. edited cifar_loc to point to a local folder and ran the first cell .. that downloaded the cifar tar.gz. ok .. ran the 2nd cell, got an error .. took a look in extract_cifar.py and that code is looking for a subfolder called 'cifar-10-batches-py' off my download folder .. which wasn't there as the cifar tar.gz hadn't been unzipped .. hmm.. so I manually unzipped the file and got a bit further .. but then the cell that uses cifar_utils to load the data is looking for files that don't exist .. and so at this point i'm a bit confused and am wondering what noob mistake I have made..?

**Comment by dcrankshaw** [comment]
Can you post the full error output you got when you tried to run the 2nd cell?

**Comment by miramar-labs** [comment]
so in cell 1 I set my download folder like so:
cifar_loc = "/Users/mlabs/clipper/examples/tutorial/cifar"
ran cell 1 .. it downloaded cifar-10-python.tar.gz to that folder as expected. However, it is not extracted yet.
ran cell 2 .. (thinking it would extract it) .. but got these errors:
Unpickling data batches...
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/Users/mlabs/clipper/examples/tutorial/extract_cifar.py in <module>()
     96         sys.exit(1)
     97     extract_to_csv(loc, *extract_cifar(loc), \
---> 98         max_train_datapoints=max_train_datapoints, max_test_datapoints=max_test_datapoints)

/Users/mlabs/clipper/examples/tutorial/extract_cifar.py in extract_cifar(loc)
     22     data, labels = [], []
     23     test_data, test_labels = [], []
---> 24     for filename in os.listdir(batches_dir):
     25         file_path = os.path.join(batches_dir, filename)
     26         if 'data_batch' in filename:

OSError: [Errno 2] No such file or directory: '/Users/mlabs/clipper/examples/tutorial/cifar/cifar-10-batches-py'

**Comment by nishadsingh1** [comment]
@miramar-labs Thanks for altering us to this – there's a PR (#142) up now that attempts to solve the issue you're facing.

**Comment by miramar-labs** [comment]
another thing (maybe as i'm new to jupyter notebooks) is that i'm trying to reset the tutorial .. start over.. remove my edits .. and auto-saved checkpoints .. so I go to the Kernel menu at the top of the page and select 'Restart & Clear Output' as that sounded promising, but it doesn't seem to reset anything - certainly not my edits anyway .. what's the trick to it?  thanks

**Comment by nishadsingh1** [comment]
Yeah, I don't think that changes edits. You can go to File -> Revert to Checkpoint -> click the earliest checkpoint. 
<img width="594" alt="screen shot 2017-04-26 at 6 17 43 pm" src="https://cloud.githubusercontent.com/assets/6938722/25463697/d63b32ec-2aac-11e7-8084-4825b0c0df1d.png">

**Comment by miramar-labs** [comment]
unfortunately there doesn't seem to be an earlier checkpoint that _doesn't_ contain my edits .. hmm .. next time i will be sure to checkpoint before I start ... 
(as for resetting .. git checkout -- . on the root of the source tree clears the notebooks)

**Comment by dcrankshaw** [comment]
Fixed by #142
