### ISSUE TITLE
kubernetes integration

### ISSUE THREAD

**Issue by geoHeil** [ucbrise/clipper#144]
do you plan to allow for kubernetes integration instead of using docker-compose / swarm?

**Comment by yubozhao** [comment]
I would love to know the planning for this as well.

I guess, for now we can split up the redis, query_frontend and mgmt_frontend

**Comment by dcrankshaw** [comment]
We do plan to enable Kubernetes integration. The clipper_manager script is in serious need of refactoring. The plan is to build a library that abstracts out the container management functionality behind an API. Then we can have an implementation of the interface for Kubernetes, one with plain Docker/Docker-compose, and potentially even other container management tools.

**Comment by dcrankshaw** [comment]
Progress on this has begun with #206

**Comment by dcrankshaw** [comment]
Support for Kubernetes added in #251
