### ISSUE TITLE
pthread_mutex_lock error after deploying two applications

### ISSUE THREAD

**Issue by AirAI** [ucbrise/clipper#148]
The clipper works well when it is deployed one application.  When it is deployed two applications ,it also works well for request related to the first deployed application, but it reports the following error for request related to the second deployed application.
`
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc7fff700 (LWP 59250)]
__GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:66
66      ../nptl/pthread_mutex_lock.c: No such file or directory.
`

**Comment by AirAI** [comment]
Has the problem been solved yet?

**Comment by dcrankshaw** [comment]
It's in progress. I'm pretty sure that #157 + #149 fixes this.
