### ISSUE TITLE
query_frontend - very high CPU usage

### ISSUE THREAD

**Issue by rmdort** [ucbrise/clipper#154]
I am on Google cloud platform server (n1-highmem-2 - 2 vCPUs, 13 GB memory) . No apps running

query_frontend is using 200% of the CPU

![image](https://cloud.githubusercontent.com/assets/118231/26022526/7ff6fc1e-37da-11e7-9807-a029716dbffe.png)

Is this normal. Do you need any other logs?

**Comment by dcrankshaw** [comment]
Yeah this is a known issue. We have a few busy waits in the codebase that we're in the process of getting rid of. Clipper should get a little more efficient in the next few weeks.

**Comment by dcrankshaw** [comment]
#157 should help with this substantially

**Comment by rmdort** [comment]
Thank you. I just tested with #157 and the CPU usage hasn't come down. This issue still persists

**Comment by dcrankshaw** [comment]
Yeah you're right. We removed some but not all the busy waits. #162 takes care of the rest, at least while Clipper is idle.

**Comment by withsmilo** [comment]
This issue still occurs after applied #162. I did a stress test to the query_frontend container and found that query_frontend is using very high CPU usage although the test is finished (some requests were failed) and no app is running.
