### ISSUE TITLE
Error when tried run the clipper

### ISSUE THREAD

**Issue by daijidj** [ucbrise/clipper#167]
Hi, I ran into two issues when tried the clipper project:

1. when run the "pip install -r requirements.txt" , the error occur:

> Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/share'

this error happened after I ignored installing the "six", the error was "OSError: [Errno 1] Operation not permitted: '/var/folders/wj/wkz200q12ssg05sqrxzqb7sr0000gp/T/pip-JbPkys-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'", Is there any thing I need to do to install all these? this error might something with OS, my OS is macOS Sierra.

2.When I tried to run the “example_client.py”. I got the error message which is:

> lTraceback (most recent call last):
  File "example_client.py", line 29, in <module>
    "-1.0", 40000)
  File "/Users/jidai/Downloads/clipper/management/clipper_manager.py", line 294, in register_application
    r = requests.post(url, headers=headers, data=req_json)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1338): Max retries exceeded with url: /admin/add_app (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d916450>: Failed to establish a new connection: [Errno 61] Connection refused',))

Should I try another host and port and if yes, any suggestions for the host and port? (these dockers are on:

clipper_redis_1,

clipper_mgmt_frontend_1,

clipper_query_frontend_1)

Looking forward to hearing from you.

**Comment by dcrankshaw** [comment]
The first error appears to be a permissions issue when trying to do `pip install`. You can try doing `sudo pip install`. Alternatively, we recommend using [Anaconda](https://www.continuum.io/downloads) for your Python installation, which should avoid any permissions issues.

For the second error, can you post the output of `docker ps -a` and the output of `docker logs clipper_mgmt_frontend_1`? For some reason, you are unable to connect to the clipper management frontend. The logs should help diagnose why.

**Comment by dcrankshaw** [comment]
@daijidj Any progress on this?

**Comment by hrishikeshvganu** [comment]
I have a similar problem. When I issue:
` clipper.get_all_containers()` I get:

```

---------------------------------------------------------------------------
ConnectionError                           Traceback (most recent call last)
<ipython-input-23-282caae68a67> in <module>()
----> 1 clipper.get_all_containers()

/home/ubuntu/miniconda2/envs/py2k/lib/python2.7/site-packages/clipper_admin/clipper_manager.pyc in get_all_containers(self, verbose)
    812         req_json = json.dumps({"verbose": verbose})
    813         headers = {'Content-type': 'application/json'}
--> 814         r = requests.post(url, headers=headers, data=req_json)
    815
    816         if r.status_code == requests.codes.ok:

/home/ubuntu/miniconda2/envs/py2k/lib/python2.7/site-packages/requests/api.pyc in post(url, data, json, **kwargs)
    108     """
    109
--> 110     return request('post', url, data=data, json=json, **kwargs)
    111
    112

/home/ubuntu/miniconda2/envs/py2k/lib/python2.7/site-packages/requests/api.pyc in request(method, url, **kwargs)
     54     # cases, and look like a memory leak in others.
     55     with sessions.Session() as session:
---> 56         return session.request(method=method, url=url, **kwargs)
     57
     58
/home/ubuntu/miniconda2/envs/py2k/lib/python2.7/site-packages/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    471
    472         except (ProtocolError, socket.error) as err:
--> 473             raise ConnectionError(err, request=request)
    474
    475         except MaxRetryError as e:

ConnectionError: ('Connection aborted.', BadStatusLine("''",))

```



 @dcrankshaw: the logs you asked for are here:

```
(py2k) ubuntu@~/e/h/P/i/i/ike ❯❯❯ docker ps                                                                                                  ⏎
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                                            NAMES
7720050f8fb4        clipper/query_frontend:latest        "/clipper/release/..."   26 minutes ago      Up 26 minutes       0.0.0.0:1337->1337/tcp, 0.0.0.0:7000->7000/tcp   in_query_frontend_1
69f8ac822433        clipper/management_frontend:latest   "/clipper/release/..."   26 minutes ago      Up 26 minutes       0.0.0.0:1338->1338/tcp                           in_mgmt_frontend_1
95201607956b        redis:alpine                         "docker-entrypoint..."   26 minutes ago      Up 26 minutes       0.0.0.0:6379->6379/tcp                           in_redis_1
a57ffadf3900        all_1                                "/usr/lib/postgres..."   3 weeks ago         Up 3 weeks          5432/tcp, 0.0.0.0:8080->8080/tcp                 sad_wing
6051277cbf11        mongo:latest                         "docker-entrypoint..."   7 weeks ago         Up 7 weeks          0.0.0.0:32769->27017/tcp                         mongodb
aa37a32ab881        29ccc219ac95                         "/bin/bash"              2 months ago        Up 2 months         0.0.0.0:80->80/tcp                               awesome_leavitt
(py2k) ubuntu@ip-172-16-2-57 ~/e/h/P/i/i/ike ❯❯❯ docker logs in_mgmt_frontend_1
[16:14:10.364][info]       [REDIS] Successfully issued command "SELECT 1"
[16:14:10.364][info]     [STATEDB] Persistent state DB created

```

**Comment by hrishikeshvganu** [comment]
I had some old docker images for clipper frontend, backend and they were being used. When I deleted them and created the Clipper management class object everything worked fine. Seems to be incompatibility between clipper_admin and old docker images

**Comment by dcrankshaw** [comment]
Great. Glad you figured that out. I'm surprised that Docker didn't take care of that for you. Usually the Docker daemon will check to see if there is a newer version of the image (since we tag the images with "latest") and pull that down if so.
