### ISSUE TITLE
mkdir permission denied issue

### ISSUE THREAD

**Issue by rmdort** [ucbrise/clipper#170]
I am getting the following error when deploying models

````
Fatal error: run() received nonzero return code 1 while executing!

Requested: mkdir -p /tmp/clipper-models/mom_predict_model/3
Executed: /bin/bash -l -c "mkdir -p /tmp/clipper-models/mom_predict_model/3"

=============================== Standard output ===============================

mkdir: cannot create directory ‘/tmp/clipper-models/mom_predict_model/3’: Permission denied

================================================================================

Aborting.
````

How to replicate
* Start clipper
* Deploy a model
* `sudo reboot` the server
* Deploy a new model

**Comment by dcrankshaw** [comment]
So Clipper needs to serialize some data somewhere to deploy a model. Right now we create a fresh directory in `/tmp` to deploy the model. Can you modify the permissions on /tmp so it's writable by by the user running deploy_model?
