### ISSUE TITLE
Allow redis_persistence_path to read from an existing Redis snapshot

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#172]
I just realized that forcing `redis_persistence_path` to not already exist will be problematic if you want to restart the Redis container and have it read from an existing Redis snapshot.

@Corey-Zumar Can you check if you can replicate the Docker container issue I was having when setting `redis_persistence_path` to `/tmp`?

**Comment by Corey-Zumar** [comment]
@dcrankshaw Confirmed that I can reproduce this behavior when setting the path to `/tmp`

**Comment by dcrankshaw** [comment]
Duplicate of #216
