### ISSUE TITLE
Unloading old models

### ISSUE THREAD

**Issue by rmdort** [ucbrise/clipper#176]
When a new model is deployed, can clipper unload previous versions of that model ?

We deploy at least 10 versions of a model a day. All the old docker containers hogs the machine. Right now we manually stop the old ones. Is it possible to have an API to undeploy?

**Comment by dcrankshaw** [comment]
This is definitely an important feature. The big blocker here is what should be removing the containers. We would like `query_frontend` and `management_frontend` containers to be independent of any particular underlying model container technology. E.g. Clipper should not need to care whether a model container is running in Docker, on bare metal, etc.

How do you envision this working? Would you like a method added to `clipper_manager`? What would the function signature look like?

**Comment by rmdort** [comment]
Yes thats right. I am currently handling in `clipper_manager`. I label each container with `model_name` and remove old ones when new model is deployed. 

https://github.com/rmdort/clipper/blob/ola/clipper_admin/clipper_manager.py#L866

**Comment by dcrankshaw** [comment]
Cool. I actually just learned about Docker labels recently and this seems like a good intermediate solution to the problem. I'll put together a PR to address this soon.
