### ISSUE TITLE
No selection state found for query with user_id: 1

### ISSUE THREAD

**Issue by AirAI** [ucbrise/clipper#177]
when I send a query request with "uid=0"to the PREDICT port of the registered application, it works well. But if i assign uid with 1 or other value(i.e, uid=1, or uid=2), it reports the following error. What is the variable uid used for?
No selection state found for query with user_id: 1

Codes are similar to the cifar_utils.py in L122
uid=1
url = "http://%s:1337/%s/predict" % (host, app)    
json = json.dumps({'uid': uid, 'input': list(x)})

**Comment by dcrankshaw** [comment]
Apologies for the confusion. The user ID currently must be 0. I just filed #184 to remove it from the prediction request object until personalization is supported.
