### ISSUE TITLE
Confusing parts of Clipper Manager API

### ISSUE THREAD

**Issue by jegonzal** [ucbrise/clipper#188]
The following are a list of peculiarities I found in the python admin API:

- [x] The `clipper_admin` python module contains the `clipper_manager`.  Is the second _clipper_ needed?  
- [ ] The `register_application` function takes a `model` argument but must the model exist?  It seems (from the demo) that the model does not need to be present when registering it in an application.  This should probably raise an error.
- [x] Are `selection_policies` active in this release? (See `inspect_selection_policy`)?
- [ ] What are `external_models` (See `register external models`)
- [x] The use of labels is a bit unclear.

**Comment by dcrankshaw** [comment]
The remaining confusing parts can be tracked in #218
