### ISSUE TITLE
Volume mounting host paths into docker containers precludes distributed deployment of models

### ISSUE THREAD

**Issue by feynmanliang** [ucbrise/clipper#200]
To deploy a model, clipper currently:

* On the client running `clipper_manager`, serializes the prediction function to disk (https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_manager.py#L666) and copies the pickled function to the clipper host (https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_manager.py#L539) at a magical `/tmp/{model_repo}/{name}/{version}` file path (https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_manager.py#L497)
* On the clipper host, spins up a docker container using `model_metadata[container_name]` and read-only volume mounts the serialized model from the magical file path https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_manager.py#L955

Reading models from the host's filesystem is not durable, as all models are lost when a single machine fails. Furthermore, it prevents distributed deployment since which physical host a container is scheduled to is not readily guaranteed. Under the current design: a model can only be deployed if its host machine has the model in its filesystem.

Kubernetes provides a [volumes](https://kubernetes.io/docs/concepts/storage/volumes/) concept, but these are backed either by the host filesystem or a cloud provider volume (e.g. AWS EBS), both of which k8s restricts to be accessible from a single pod (EBS can only be mounted to one EC2 instance at a time).

There are a few possible solutions to the problem:

1. When deploying a model, build a docker image on the client and push the image to a docker registry. Have Redis track the pushed docker image instead of the magical `/tmp/{model_repo/...` file path. This will make build significantly slower, but improves durability (if the docker registry is durable) and scalability (each replica pulls the image and deploys it with no sharing of global state)
2. Have deployed containers request the model after container startup (e.g. from S3, or from the clipper host). This keeps builds at the same speed as before (time-cost of predict function serialization), but introduces additional setup costs (S3 bucket setup requires configuration and couples design to AWS) or could also lack durability (if models are still only persisted on the clipper host)

**Comment by dcrankshaw** [comment]
After the refactor in #251, Clipper no longer mounts volumes from the local filesystem by default.
