### ISSUE TITLE
Refactor model and application registration and linking

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#218]
There is some confusion and some limitations around the way that models and applications are registered with Clipper.

- [x] Currently applications specify the name of the model that they will query. This is a little bit awkward and requires the developer registering the application to know the name of the model, even if it hasn't been registered yet. Instead, one proposal is to register model and applications independently. When a user wants to associate a specific model with an application, they could call a `link_model(app_name, model_name)` to associate the two. If we go with this proposal, what are the semantics of `link` and a potential `unlink`. For example, during linking we should type check to make sure that the application and model have compatible input types.

- [ ] Users have expressed some confusion over what `input_type` means and how to use it or set it appropriately. This can be fixed with better documentation and examples.

- [x] For simple applications and demos, we should support a `clipper_admin` method that both registers an application and deploys a model at once. This lets you call a single method to start serving a model.

**Comment by nishadsingh1** [comment]
https://github.com/nishadsingh1/clipper/tree/links is a WIP branch that will address the first checkbox in this issue

**Comment by dcrankshaw** [comment]
Fixed by #226
