### ISSUE TITLE
Fix task latency measurement for better batching behavior

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#222]
While benchmarking (#204) Clipper, @nishadsingh1 discovered that the latency measurements used to estimate container throughput and therefore batch size include the time a task spends in the model queue waiting to be executed. As a result, we underestimate batch sizes as the queues start to fill up.

@nishadsingh1, you have a fix for this right?

**Comment by nishadsingh1** [comment]
Yep, it's demonstrated here: https://github.com/ucbrise/clipper/pull/204/files#diff-b833f65e61cd8ad63fd6e579acbb3096R459.
I'll get a PR up with the fix + other general benchmarking refactoring when #191 is merged in to avoid a rebase

**Comment by dcrankshaw** [comment]
This will be fixed by #225
