### ISSUE TITLE
On macOS query always returns the default prediction

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#224]
This behavior has only been observed on macOS, so I think it's likely that the problem has to do with the way Clang compiles Boost on macs.

Steps to reproduce
1. Start Clipper
2. Register an application with type doubles and default output X and very large latency SLO.
3. Register an external model matching the name specified when registering the application
4. Connect the model to Clipper (I used the Java NoOpModel)
5. Send a prediction request with an array of doubles to Clipper
6. Observe that the response is the default output

From checking the logs, it is clear that both the model container gets queried and the response is returned in time. With further digging, I isolated the problem to `boost::future`s that were initially ready becoming "unready".

When a prediction is requested, the QueryProcessor schedules a task to evaluate the prediction, then waits for the future associated with the requested prediction to complete before the timer expires. Meanwhile, the task executor sends the prediction to a model container. When that prediction is returned from the container, it is placed in the prediction cache. This triggers the cache to [complete promises](https://github.com/ucbrise/clipper/blob/4278da241903fa02b45967a2ced0b3c87b4346a3/src/libclipper/src/task_executor.cpp#L66-L67) for any futures that have been returned, including the one that the QueryProcessor is waiting on. At this point, `boost::future::is_ready() == true`. The QueryProcessor is notified that the future is ready and proceeds to finish processing it and return a response. As part of that post-processing (due to the way that future composition works), QueryProcessor again calls [`future::is_ready`](https://github.com/ucbrise/clipper/blob/5a7d17251046436505ccf925d275f6ebd83c18dc/src/libclipper/src/query_processor.cpp#L116) to determine whether response processing was triggered due to the prediction task completing or the timer expiring. For some reason on macOS, this second call to `future::is_ready` returns false which causes the QueryProcessor to return the default response. I have not encountered this problem when running Clipper through our Docker containers, which use Alpine Linux, compile Clipper with GCC, and use the Alpine package repository's version of [Boost](https://pkgs.alpinelinux.org/package/edge/main/x86/boost-dev).

According to the documentation for [Boost Future](http://www.boost.org/doc/libs/1_64_0/doc/html/thread/synchronization.html#thread.synchronization.futures.reference.unique_future.is_ready), "The result of [future::is_ready] is not stable and that the future could become not ready even if the function returned true or vice-versa." It seems like the only way to fix this problem is to replace our use of Boost::future with an implementation that does not have this bug. Facebook's [Folly](https://github.com/facebook/folly/tree/master/folly/futures) library seems like the leading candidate. It supports future continuations and composition (which Clipper requires) and seems to be actively maintained by Facebook.

**Comment by rmdort** [comment]
I have also observed that the very first prediction request after a model is deployed always returns the default response. We are running clipper on ubuntu. Not sure if this is the same issue?

**Comment by zerowgravity** [comment]
Not sure if this is MacOS specific, but when deploying the predict_function an empty set is returned from redis.


```if "empty list or set" or "" in result.stdout:
                # Model not found
                print("Trying to add container but model {mn}:{mv} not in "
                     "Redis".format(mn=model_name, mv=model_version))
                return False```

Has anyone seen this on MacOS Sierra ?
