### ISSUE TITLE
Update clipper python plugin

### ISSUE THREAD

**Issue by rmdort** [ucbrise/clipper#229]
@dcrankshaw can you update clipper python plugin to the latest master branch?

**Comment by dcrankshaw** [comment]
I will create a new patch release and update the clipper python package on pypi this weekend. In the meantime, you can install the pip package locally by cloning the Clipper repo and running the following command

```sh
pip install /path/to/clipper
```

See the [pip docs](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs) for details.

**Comment by dcrankshaw** [comment]
New release is out. Run `pip install -U clipper_admin` to upgrade.
