### ISSUE TITLE
Error publishing model: Error parsing JSON: Type mismatch!

### ISSUE THREAD

**Issue by bigdata2** [ucbrise/clipper#230]
I installed clipper_admin using pip install. 

I got the following error when I ran the quick start example mentioned in the README:

>>> clipper.deploy_predict_function("feature_sum_model", 1, feature_sum_function, "doubles")
Anaconda environment found. Verifying packages.
Fetching package metadata .........
Solving package specifications: .

Supplied environment details
Serialized and supplied predict function
model_data_path is: /tmp/predict_serializations/feature_sum_model
Error publishing model: Error parsing JSON: Type mismatch! JSON key model_version expected type Stringbut found type Number. Expected JSON schema: 
  {
   "model_name" := string,
   "model_version" := string,
   "labels" := [string],
   "input_type" := "integers" | "bytes" | "floats" | "doubles" | "strings",
   "container_name" := string,
   "model_data_path" := string
  }

False

**Comment by nishadsingh1** [comment]
Thanks for letting us know! @dcrankshaw, I think we pushed a new version of the management frontend but haven't updated the pip package to reflect the changes to the management library -- does that sound right?

**Comment by dcrankshaw** [comment]
No the pip package has been updated since then. Try pulling the latest versions of the Docker containers.

```
docker pull clipper/query_frontend
docker pull clipper/management_frontend
```

**Comment by dcrankshaw** [comment]
Ahh apologies, I misread your error. That's a typo in the README. We changed 

```
clipper.deploy_predict_function("feature_sum_model", "1", feature_sum_function, "doubles")
```

**Comment by dcrankshaw** [comment]
(Deleted my previous comments. That's what I get for responding to issues before drinking my first cup of coffee). @nishadsingh1 is correct. I'll put out a new release today. The salient change is that model versions can now be strings.

**Comment by dcrankshaw** [comment]
The new release is out. Run `pip install -U clipper_admin` to upgrade.
