### ISSUE TITLE
Cannot start clipper after update

### ISSUE THREAD

**Issue by rmdort** [ucbrise/clipper#235]
Locally when i run `clipper.start()`, it gives an error

````
Fatal error: local() encountered an error (return code 1) while executing 'docker-compose up -d query_frontend'

================================ Standard error ================================

Starting tutorial_redis_1
Recreating 97f6da1e7238_97f6da1e7238_tutorial_mgmt_frontend_1

ERROR: for mgmt_frontend  No such image: sha256:4f6a793bdd1d5f56012943ca193117137cbfc0c219dec667ff56d250fcae5444
Encountered errors while bringing up the project.

================================================================================

Aborting.
````

**Comment by dcrankshaw** [comment]
I'm unable to reproduce this locally. It looks like it might be a problem with out of date Docker containers. Specifically, it looks like docker-compose may be trying to find a Docker container that has been updated. Try deleting the docker-compose.yml file in this directory and running `Clipper.start()` again. If that does not solve the problem, I would try deleting all of the Clipper Docker images from your machine. When you run `Clipper.start()` it will download the newest version of each image.
