### ISSUE TITLE
E2E Encryption Configuration for Clipper Services 

### ISSUE THREAD

**Issue by smrtslckr** [ucbrise/clipper#239]
What would be the best way to configure E2E encryption for clipper services?  I currently utilize AWS Elastic Container Service and Elastic Beanstalk with Docker Containers which allow easy configuration of the correct E2E encryption options for my APIs.

**Comment by dcrankshaw** [comment]
Can you expand on your use case a little bit? You can send encrypted inputs to Clipper for prediction, and decrypt them only in your deployed model containers when they need to make predictions.

**Comment by smrtslckr** [comment]
@dcrankshaw Certainly, thank you for inquiring.  I meant what would be the best way to specify TLS protocols and ciphers for setting up E2E encryption for a Clipper service for example?  My apologies since I have limited ops experience but in the AWS elastic beanstalk case you can use ebextensions files to configure these settings.

**Comment by dcrankshaw** [comment]
This is somewhat orthogonal to Clipper's core functionality. I would imagine that you would do it in a similar way as for a web server or other REST service, but unfortunately I can't provide any more specific guidance.
