### ISSUE TITLE
Out of the box support for deploying Keras models

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#241]
As requested in #233

**Comment by gmittal** [comment]
Based on the conversation in #233, I assume this issue is resolved now?

**Comment by withsmilo** [comment]
@gmittal : The latest Clipper version, v0.4.1 supports Keras already. Here are examples for  Keras. I will close this issue. 
* https://github.com/ucbrise/clipper/blob/develop/examples/frameworks/keras_on_docker_example.ipynb
* https://github.com/ucbrise/clipper/blob/develop/examples/image_query/keras_on_docker_example.ipynb

**Comment by rkooo567** [comment]
@gmittal Also, we will update Keras to API documentation soon. Until then, please look at Pydoc here. https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/deployers/keras.py
