### ISSUE TITLE
Docker container exits due to errors after clipper.deploy_predict_function

### ISSUE THREAD

**Issue by bigdata2** [ucbrise/clipper#265]
I have a very simple tensorflow model that I am trying to deploy using the following command:
clipper.deploy_predict_function("mnist_model", 3, mnist_score, "doubles")

However, the model fails to deploy and the docker log for the container has a few errors. Is there something else I need to do to deploy this function?

My model and docker log are copied below.

**Model**:

```
import cv2

def mnist_score(img):
    sess = tf.Session('', tf.Graph())
    with sess.graph.as_default():
        saver = tf.train.import_meta_graph("../../test/lenet.meta")
        saver.restore(sess, tf.train.latest_checkpoint('../../test'))
    
    logits = sess.run('logits:0', feed_dict={'X:0': img})
    return logits.astype(np.str).tolist()

img = cv2.imread('tmp.png',0)
img = np.expand_dims(img, axis=0)
img = np.expand_dims(img, axis=3)

print("MNIST test score: %s" % mnist_score(img))
```
**Docker Log**:

First attempting to run Python container without installing supplied dependencies.
Starting PythonContainer container
Connecting to Clipper with default port: 7000
Initializing Python function container
No module named tensorflow
Encountered an ImportError when running Python container without installing supplied dependencies.
Will install supplied dependencies and try again.
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    cudatoolkit:    7.5-0             
    cudnn:          5.1-0             
    libgpuarray:    0.6.8-0           
    libprotobuf:    3.2.0-0           
    mako:           1.0.6-py27_0      
    mock:           2.0.0-py27_0      
    pbr:            1.10.0-py27_0     
    protobuf:       3.2.0-py27_0      
    pygpu:          0.6.8-py27_0      
    tensorflow-gpu: 1.1.0-np112py27_0 
    theano:         0.9.0-py27_0      

The following packages will be UPDATED:

    anaconda:       custom-py27_0      --> 4.4.0-np112py27_0 
    conda:          4.3.22-py27_0      --> 4.3.23-py27_0     

The following packages will be DOWNGRADED:

    nbconvert:      5.2.1-py27_0       --> 5.1.1-py27_0      
    pandas:         0.20.2-np112py27_0 --> 0.20.1-np112py27_0
    testpath:       0.3.1-py27_0       --> 0.3-py27_0        

cudatoolkit-7. 100% |###############################| Time: 0:00:20  11.03 MB/s
cudnn-5.1-0.ta 100% |###############################| Time: 0:00:07  10.84 MB/s
libgpuarray-0. 100% |###############################| Time: 0:00:00  12.25 MB/s
libprotobuf-3. 100% |###############################| Time: 0:00:00  11.05 MB/s
mako-1.0.6-py2 100% |###############################| Time: 0:00:00  14.31 MB/s
protobuf-3.2.0 100% |###############################| Time: 0:00:00  15.86 MB/s
pandas-0.20.1- 100% |###############################| Time: 0:00:01  11.21 MB/s
pbr-1.10.0-py2 100% |###############################| Time: 0:00:00  13.42 MB/s
pygpu-0.6.8-py 100% |###############################| Time: 0:00:00  11.34 MB/s
testpath-0.3-p 100% |###############################| Time: 0:00:00  16.53 MB/s
mock-2.0.0-py2 100% |###############################| Time: 0:00:00  13.85 MB/s
theano-0.9.0-p 100% |###############################| Time: 0:00:00  11.40 MB/s
conda-4.3.23-p 100% |###############################| Time: 0:00:00  12.59 MB/s
nbconvert-5.1. 100% |###############################| Time: 0:00:00  12.33 MB/s
tensorflow-gpu 100% |###############################| Time: 0:00:07   9.74 MB/s
anaconda-4.4.0 100% |###############################| Time: 0:00:00  11.54 MB/s
Collecting appdirs==1.4.3 (from -r /model/pip_dependencies.txt (line 1))
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Requirement already satisfied: backports-abc==0.5 in /opt/conda/lib/python2.7/site-packages (from -r /model/pip_dependencies.txt (line 2))
Requirement already satisfied: backports.shutil-get-terminal-size==1.0.0 in /opt/conda/lib/python2.7/site-packages (from -r /model/pip_dependencies.txt (line 3))
Requirement already satisfied: backports.ssl-match-hostname==3.4.0.2 in /opt/conda/lib/python2.7/site-packages (from -r /model/pip_dependencies.txt (line 4))
Collecting backports.weakref==1.0rc1 (from -r /model/pip_dependencies.txt (line 5))
  Downloading backports.weakref-1.0rc1-py2-none-any.whl
Collecting bcrypt==3.1.3 (from -r /model/pip_dependencies.txt (line 6))
  Downloading bcrypt-3.1.3-cp27-cp27mu-manylinux1_x86_64.whl (57kB)
Collecting certifi==2017.4.17 (from -r /model/pip_dependencies.txt (line 7))
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB)
Collecting clipper-admin==0.1.4 (from -r /model/pip_dependencies.txt (line 8))
  Downloading clipper_admin-0.1.4.tar.gz
Requirement already satisfied: et-xmlfile==1.0.1 in /opt/conda/lib/python2.7/site-packages (from -r /model/pip_dependencies.txt (line 9))
Collecting fabric==1.13.1 (from -r /model/pip_dependencies.txt (line 10))
  Downloading Fabric-1.13.1-py2-none-any.whl (92kB)
Requirement already satisfied: ipython-genutils==0.2.0 in /opt/conda/lib/python2.7/site-packages (from -r /model/pip_dependencies.txt (line 11))
Requirement already satisfied: jupyter-client==5.0.1 in /opt/conda/lib/python2.7/site-packages (from -r /model/pip_dependencies.txt (line 12))
Requirement already satisfied: jupyter-console==5.1.0 in /opt/conda/lib/python2.7/site-packages (from -r /model/pip_dependencies.txt (line 13))
Requirement already satisfied: jupyter-core==4.3.0 in /opt/conda/lib/python2.7/site-packages (from -r /model/pip_dependencies.txt (line 14))
Collecting markdown==2.6.8 (from -r /model/pip_dependencies.txt (line 15))
  Downloading Markdown-2.6.8.tar.gz (307kB)
Collecting mysql-python==1.2.5 (from -r /model/pip_dependencies.txt (line 16))
  Downloading MySQL-python-1.2.5.zip (108kB)
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wz4cSe/mysql-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wz4cSe/mysql-python/
Starting PythonContainer container
Connecting to Clipper with default port: 7000
Initializing Python function container
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/conda/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Encountered an ImportError even after installing supplied dependencies.

**Comment by Corey-Zumar** [comment]
This is an undocumented limitation of `deploy_predict_function`. The system commands issued by [clipper_manager.py](clipper_manager.py) refer to `docker` rather than `nvidia-docker`, preventing proper resolution of gpu dependencies like the cuda libraries. For this use case, try modifying `add_container_cmd` on line 1329 of [clipper_manager.py](clipper_manager.py) so that it executes `nvidia-docker run` rather than `docker run`. Note that `nvidia-docker` must be installed on the host machine to which the model is being deployed.

**Comment by bigdata2** [comment]
@Corey-Zumar : I have changed my environment to use tensorflow with no GPU, I will revisit nvidia-docker later. I still have a question -- how do I deploy a trained model like the one shown in my original question the same way cifar10 example was deployed? Specifically, I want tf_session to be initialized in a class so that I do not recreate graph for each inference and would like to see my predict function to be part of that class. 

I tried killing a running python process in the cifar10 example container to modify the script, but that causes the container to exit.

**Comment by Corey-Zumar** [comment]
You'll want to use `clipper_manager.deploy_model` rather than `deploy_predict_function`. You will also need to [export your tensorflow model as a meta graph](https://www.tensorflow.org/programmers_guide/meta_graph). Then, write a python container that loads the meta graph and serves the model - this can be done with very limited modifications to [tf_cifar_container.py](tf_cifar_container.py). Once you have the Python container script, build a docker container using a docker build file - again, this can be done with very small modifications to [TensorflowCifarDockerfile](TensorflowCifarDockerfile). Finally, call deploy model as follows:

```
Clipper.deploy_model(<model_name>, 
                                     <model_version>, 
                                     <path_to_directory_containing_tensorflow_metagraph_data>,                                      
                                     <docker_container_name>,  
                                     <input_type>)
```

Additionally, we will reduce a lot of this overhead and provide first-class support for the efficient serving of Tensorflow models in our next release.

**Comment by bigdata2** [comment]
A few comments from my experiment of porting my model to the docker container:
- Update version of clipper/py-rpc to latest in clipper/TensorFlowCifarDockerfile, there is no 0.2-rc1 version available in Docker hub.
- Update Tensorflow from 1.0 to 1.2.
- Tensorflow Saver class now creates more than two files after saving the model, i.e. it also creates a protocol buffer file and an index file. The [assert](https://github.com/ucbrise/clipper/blob/develop/containers/python/tf_cifar_container.py#L65) statement to check only 2 files is not valid for the latest Tensorflow model.
- Make a comment somewhere that the input to the model will be a 1D list which may have to be reshaped before passing it to the saved model.
- Document limitation of Clipper for Tensorflow with GPU -- that is a user will have to install nvidia-docker and modify the Clipper scripts or install GPU drivers into the container (i.e. rebuilding it locally) to be able to access the GPU. Further, in the current version, the container and init python scripts will have to be modified to make Tensorflow work.
- Finally, there is a need for a log file inside the container for debugging and monitoring.

**Comment by Corey-Zumar** [comment]
@bigdata2 Thanks for documenting the process and providing feedback. We'll take your notes into consideration and address our current issues / shortcomings with Tensorflow deployment. Did everything work out after the modifications you described?

**Comment by bigdata2** [comment]
@Corey-Zumar Yes, it worked. But it was somewhat difficult to debug because if there is an issue with the model, the REST API returns the default value with a comment on the lines that it is returning default value because SLO value exceeded. An insight into why SLO value exceeded would be helpful both for debugging and runtime monitoring. At any rate, it is a good start towards a user friendly deployment of models.

**Comment by Corey-Zumar** [comment]
Got it - I absolutely agree. I'll explore strategies for improving the clarity of our default output explanations.

**Comment by dcrankshaw** [comment]
@bigdata2 Thanks for bringing this to our attention. Debugging exactly what is going on in the model containers is definitely harder than it should be. We've noted this and making model containers easier to debug is on our roadmap.
