### ISSUE TITLE
About the Feature of Easily update or add models to running applications

### ISSUE THREAD

**Issue by raopku** [ucbrise/clipper#270]
Is the code below supported by clipper?
```
from clipper_admin import Clipper
clipper_conn = Clipper("localhost")
clipper_conn.start()
clipper_conn.register_application("hello_world", "feature_sum_model", "doubles", "-1.0", 100000)

for i in xrange(1000):
      def pred(xs):
            return [str(np.sum(x)) for x in xs] + [str(i)]
      clipper_conn.deploy_predict_function("feature_sum_model", i, pred, "doubles")
```

does it support frequently update running model?

**Comment by dcrankshaw** [comment]
The above code snippet looks like it should work. However, there is a non-trivial overhead in deploying a new model, and it will take each new model container at least a few seconds to start up. Part of this overhead is starting a new Docker container.

**Comment by dcrankshaw** [comment]
The question has been answered. Closing.
