### ISSUE TITLE
Error : client and server don't have same version

### ISSUE THREAD

**Issue by abuvaneswari** [ucbrise/clipper#289]
Hello,

I followed the quickstart instructions from 
http://clipper.ai/overview/quickstart/ 

Using Ubuntu 14.04 and Python 2.7.6
Installed clipper_admin

Getting the following error message.
Please help resolve.
Thanks,
Buvana

>>> from clipper_admin import Clipper
>>> clipper_conn = Clipper("localhost", sudo=True)
Checking if Docker is running...
>>> clipper_conn.start()
Note: Docker must download the Clipper Docker images if they are not already cached. This may take awhile.

Fatal error: local() encountered an error (return code 1) while executing 'sudo docker-compose up -d query_frontend'

=============================== Standard error ===============================

client and server don't have same version (client : 1.22, server: 1.18)

===============================================================================

**Comment by dcrankshaw** [comment]
It looks like your version of Docker is really old. What does the command `docker --version` show?

Also, you may want try the latest version of clipper_admin https://github.com/ucbrise/clipper#quickstart

It will be released as part of the 0.2.0 release in the next couple days.

**Comment by abuvaneswari** [comment]
Hello,

Thank you for the info on the new version of clipper. Will try that as well.

Docker version 1.6.2

-Buvana

**Comment by abuvaneswari** [comment]
Installed the latest docker and Clipper is running!

**Comment by dcrankshaw** [comment]
Great to hear!
