### ISSUE TITLE
Add batch prediction interface

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#292]
Clipper's query frontend currently accepts only a single input at a time for predictions. Clipper should instead accept a list of inputs at once and return a list of outputs. This will improve both usability and performance, as users will no longer be forced to send a separate HTTP request for each prediction.

In particular, Clipper expects prediction requests in the following JSON format:

```
{ "input" := [double] | [int] | [byte] | [float] | string }
```

It should also accept inputs of the following format (we still want to accept input with the old format to preserve backwards compatibility).
```
{ "input_batch" := [[double] | [int] | [byte] | [float] | string] }
```
This should be implemented by modifying [`decode_and_handle_predict`](https://github.com/ucbrise/clipper/blob/b7ba1df9b64796ba37bd3bb9c717d1c09f5bee6a/src/frontends/src/query_frontend.hpp#L484-L498) in `query_frontend.hpp`. It should be modified to parse all of the inputs from the JSON, then submit each request in the batch individually to the query processor. It should then use [`folly::Future::collectAll`](https://github.com/facebook/folly/tree/master/folly/futures#collectall) to create a single future that will complete when all of the prediction futures have completed. `decode_and_handle_predict` should return a `folly::Future<std:vector<Try<Response>>>` that contains all of the responses.

The prediction closure that should then create a response JSON object that returns the list of responses in the same order as the list of requests was given (so the user knows which response corresponds to which request). Request specific error-handling should be done within the list (e.g. if some of the predictions timed out), while larger errors (e.g. malformed JSON) will not return any predictions.

Appropriate unit tests to test this new functionality should be added to [`query_frontend_tests.cpp`](https://github.com/ucbrise/clipper/blob/develop/src/frontends/src/query_frontend_tests.cpp).

**Comment by Corey-Zumar** [comment]
Completed via #321
