### ISSUE TITLE
link not maintained

### ISSUE THREAD

**Issue by geoHeil** [ucbrise/clipper#302]
`[deployer_utils.py:63] Warning: Anaconda environment was either not found or exporting the environment failed. Your function will still be serialized and deployed, but may fail due to missing dependencies. In this case, please re-run inside an Anaconda environment. See http://clipper.ai/documentation/python_model_deployment/ for more information.`
points to a link with an 404 error

**Comment by simon-mo** [comment]
It should be this link:
http://docs.clipper.ai/en/release-0.2/index.html?highlight=Anaconda#pure-python-functions

I will submit a PR for this quick fix.
