### ISSUE TITLE
Issue with prediction_cache_hit_ratio

### ISSUE THREAD

**Issue by sbcd90** [ucbrise/clipper#305]
When I try to run the quick start example in README, I get the response,

```
{
    "query_id": 6,
    "output": -1,
    "default": true,
    "default_explanation": "No connected models found for query"
}
```

When I try to analyze the issue based on the guideline 
http://clipper.ai/tutorials/troubleshooting/#no-connected-models-found-for-query

I find that the no. of replicas available is 0 & further analyzing the logs I find the issue,
in the clipper/query_frontend:develop container.
```
[17:37:13.486][error]    [METRICS] Ratio internal:prediction_cache_hit_ratio has denominator zero!
```

Can someone please help me in getting this issue resolved?

**Comment by withsmilo** [comment]
@sbcd90 : Your model container maybe crashed. Check your container logs, not query_frontend logs.

**Comment by sbcd90** [comment]
@withsmilo ,
unfortunately, this code is not windows compatible. I found the issue is with the anaconda environment can't be exported. So, the container crashes due to missing dependencies.

**Comment by dcrankshaw** [comment]
@sbcd90: Could you file the issue describing the problem you encountered (e.g. any stack traces you have available)? We would like the automatic export of Python dependencies to work on Windows. It's a bit difficult to automatically track down all Python dependencies, so we are particularly interested in edge cases that break that section of code.

**Comment by RayTsui** [comment]
@sbcd90 Hi, I had the same issue as yours, how did you solve this issue?

**Comment by KiranVaranas** [comment]
Spark container  is running and i still see the message {'query_id': 5, 'output': -1.0, 'default': True, 'default_explanation': 'No connected models found for query'}. There is no crash in scala container only error from query_front_end  **Ratio internal:prediction_cache_hit_ratio has denominator zero!**.
