### ISSUE TITLE
Allow models to specify a fixed batch size

### ISSUE THREAD

**Issue by Corey-Zumar** [ucbrise/clipper#315]
Implement an option that allows the user to specify a pre-defined batch size for a given model. If this option is set for a model "M", all containers for this model, "C_1M" ... "C_kM", should use the specified batch size. Otherwise, if the option is not set, we should continue to estimate container batch sizes using the current logic.

**Comment by dcrankshaw** [comment]
@Corey-Zumar can you annotate this with links to the relevant implementation in the `high-perf-clipper` branch?

**Comment by Corey-Zumar** [comment]
Here are the relevant steps that need to be taken, in conjunction with references from `high-perf-clipper`:

1. Modify the Clipper admin API to allow the user to specify a batch size:
This involves the addition of a new "batch_size" parameter register_model function, as well as the build_and_deploy_model function

2. Modify Clipper's ModelContainer class to accept an optional "batch_size" parameter. It's probably best to use a boost::optional<int> object for this purpose. If "batch_size" is defined (present), the get_batch_size should return it directly. Otherwise, it should use the logic that's currently defined.

3. Modify Clipper's management API to take the "batch_size" argument specified by the user in register_model (see part 1) and include it in the Redis database entry associated with the new model. See [these modifications to the management frontend](https://github.com/dcrankshaw/clipper/pull/15/files#diff-9d52ffc36b86c3e051c47bd5971c718d) for reference and [redis interface](https://github.com/dcrankshaw/clipper/pull/15/files#diff-e6b5389d668a7df7cf397284a349b35a)

4. Make the task executor listen for updates to Redis's model database. When a model, "M", is updated, set the batch size of each of its containers, "C_1M" ... "C_kM", to the specified value in the M's configuration. You can see how this is done here: https://github.com/dcrankshaw/clipper/pull/15/files#diff-b833f65e61cd8ad63fd6e579acbb3096. 

5. Fix an issue with the implementation of step 4 that I linked
It's possible for a model container "C_iM" to connect to Clipper before the model "M" is registered. As a result, there's no information available for "batch_size" in Redis. This causes a crash here: https://github.com/dcrankshaw/clipper/pull/15/files#diff-b833f65e61cd8ad63fd6e579acbb3096R295

**Comment by Corey-Zumar** [comment]
Completed via #320
