### ISSUE TITLE
Allow use of frozen Tensorflow models (.pb) with a TF container

### ISSUE THREAD

**Issue by kakru** [ucbrise/clipper#327]
Implement an option that allows the user to deploy a frozen tensorflow model.
Would you suggest to extend the existing deployer, or to create a new one?

**Comment by dcrankshaw** [comment]
I think that extending the existing deployer is the right way to go.

**Comment by dcrankshaw** [comment]
@kakru Does #328 address this?

**Comment by kakru** [comment]
@dcrankshaw #328 doesn't directly address the problem, but when it's merged I'll extend it to support also .pb files

**Comment by santi81** [comment]
@kakru I tried to address this in 328 ...pls have a look

**Comment by kakru** [comment]
@santi81 Thanks, now it works for both frozen and meta.

One suggestion:
In clipper_admin/clipper_admin/deployers/tensorflow.py:192 I'd suggest using copytree instead of copyfile to keep the behavior consistent between model types (cf. line 207). Possible problem might arise if there is more than one file in the saved_model_path (check is for >0) and only the first .pb file is copied

**Comment by Corey-Zumar** [comment]
#328 Has addressed this issue. Closing.
