### ISSUE TITLE
XGBoost model deployer

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#341]
Change ClipperCon `deploy_model` to be able to accept packages to pip install within Container keeping base image lightweight. Add integration test for XGBoost model (using above feature to install xgboost within container), and examples to help users.

**Comment by RehanSD** [comment]
@dcrankshaw @simon-mo Simon and I were talking, and we highlighted two approaches to deploying models like XGBoost:
* Have a nested predict function (within main) that has the model, i.e.: (user code)
```
# within function that deploys model
model = XGBoost.booster()
model.train()
...
def predict(inputs):
     model.predict(inputs)
     ...
deploy_and_test_model(
                clipper_conn,
                model,
                version,
                link_model=True,
                predict_fn=predict)
```
* Have a separate, general, deployer for models that you can pickle - that way, any and all models that we/users utilize in this fashion can have similar syntax to the other models - users either pass in the default predict function, or can build their own for specific use cases - and we pickle model + function and load it all behind the scenes for one class.
It seems like after our discussions on Slack, and in person, Dan wants us to move in the direction of bullet one, so thats what I'll focus on, but I would appreciate your guys's thoughts on this.

Sorry, wrong branch.

**Comment by simon-mo** [comment]
^ A separate "XGBoost" deployer is something we can market. We can tell the users:
- There is a XGBoost deployer at your disposal that takes some pickled model that serve it. You can go from a saved model to rest endpoint within 10 lines. 
- In fact, we wrote XGBoost deployer just using `depoly_and_test_model` or `depoly_python_closure`, check out tutorial on writing your own deployer!
- It's really easy to deploy your own custom model with `deploy_python_closure`. You are welcomed to write your own deployer and raise an issue in our repo if you need help.

**Comment by RehanSD** [comment]
^ Actually Simon I think that the PyRPC deployer does just that. I'm not sure where the error I was getting from earlier came from, but it seems to be resolved. Might have been something I changed on accident.

**Comment by dcrankshaw** [comment]
I agree with @simon-mo that this is something we should market and write a
tutorial about. But we don't need a separate implementation. The Python
closure deployer already is the model deployer for any Python objects
(models or otherwise) that can be pickled. The only reason we have separate
model deployers for the other frameworks is because those models cannot be
pickled. Since XGBoost can be pickled, we just need documentation
explaining that.
