### ISSUE TITLE
Tensorflow deployer: files not found

### ISSUE THREAD

**Issue by bdod6** [ucbrise/clipper#351]
I was testing out the tensorflow model deployer and it was giving me this error message:

`Exception: Frozen Tensorflow Model: ./tf_models not found or some files are missing`

It looks like it's expecting the models to be inside a `data` directory, regardless of what path you pass to the deployer. 

For the following lines in tensorflow.py

```
if glob.glob('data/*.meta') and glob.glob(
                        'data/*.index') and glob.glob(
                            "data/checkpoint") and glob.glob("data/*.data*"):

```

I think `data` needs to be replaced with the model path.

**Comment by dcrankshaw** [comment]
Nice catch. Can you file a PR to fix this?

**Comment by bdod6** [comment]
sure, https://github.com/ucbrise/clipper/pull/353
