### ISSUE TITLE
Frontend Exporter broke the linter

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#355]
@simon-mo It looks like somehow [`front_end_exporter.py`](https://github.com/ucbrise/clipper/blob/f20cfa556ba2d7986d85969c3ace2618177525a3/monitoring/front_end_exporter.py) is failing the code format check ([Jenkins log](https://amplab.cs.berkeley.edu/jenkins/job/Clipper/3299/console)). Can you look into this?

**Comment by simon-mo** [comment]
Shoot. Seems like `{**result, **d}` is python3 syntax. I'll fix it within today

**Comment by simon-mo** [comment]
See PR #356
