### ISSUE TITLE
Adding model container testing function to clipper admin

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#360]
Currently, when users use one of the model deployers to deploy a predict function to Clipper, they have no way to debug their function before deploying the model. We should add a `test_predict_function` method to each model deployer that allows users to test that their function has the correct signature and can be properly saved and loaded.

The `test_predict_function` should have the following arguments:
+ a dict request object in the same format that the query frontend expects JSON _or_ a list of dicts if the user wishes to test their batching logic behaves correctly.
+ The predict function
+ The model (for non-vanilla Python model deployers such as PyTorch or TensorFlow)
+ The model input type

The test function will first save the predict function using the appropriate model saver and then reload it to test serialization. It will then transform the JSON input into a list of the appropriate type (e.g. a list of numpy float vectors) and call the reloaded predict function, returning the results. We will need a `test_*` function for each model deployer.

Note that this feature requires an integration test as part of our CI tests to ensure that the test function and the actual query frontend maintain matching input formats.

**Comment by Corey-Zumar** [comment]
@dcrankshaw This issue belongs to Rohan Suresh. He needs to be added as a collaborator before I can assign him this issue.
