### ISSUE TITLE
CondaHTTPError occurs in building python images

### ISSUE THREAD

**Issue by Jeffwan** [ucbrise/clipper#367]
Found an error when building python closure images.

```shell
bleach 2.1.2: ########## | 100%
scipy 1.0.0: ####9      |  50%
cryptography 2.1.4: ########## | 100%
zeromq 4.2.2: ########## | 100%
certifi 2017.11.5: ########## | 100%
readline 7.0: ########## | 100%
pexpect 4.3.1: ########## | 100%
paramiko 2.4.0: ########## | 100%
html5lib 1.0.1: ########## | 100%
jpeg 9b: ########## | 100%

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/linux-64/scipy-1.0.0-py27hf5f0f52_0.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

     --> 0.1.7-had09818_2
    zeromq:             4.2.2-hb0b69da_1           --> 4.2.2-hbedb6e5_2
    zlib:               1.2.11-hfbfcf68_1          --> 1.2.11-ha838bed_2


Downloading and Extracting Packages
The command '/bin/sh -c conda install -y --file /lib/python_container_conda_deps.txt' returned a non-zero code: 1
```

Adding  
`RUN conda config --set ssl_verify no` before 
`conda install -y --file /lib/python_container_conda_deps.txt` will resolve this issue. 
Not sure if that's the most elegant way.  

Affected docker files.

- dockerfiles/PyClosureContainerDockerfile
- dockerfiles/PyClosureContainerDockerfile
- dockerfiles/PyTorchContainerDockerfile
- dockerfiles/PySparkContainerDockerfile

**Comment by dcrankshaw** [comment]
This looks like a transient network error. I'm unable to reproduce. Maybe try building the containers again?

**Comment by dcrankshaw** [comment]
I actually was able to reproduce this when building the PyTorch container. Reopening.
