### ISSUE TITLE
Generate REST API Documentation

### ISSUE THREAD

**Issue by dcrankshaw** [ucbrise/clipper#374]
Clipper exposes a significant and growing REST API for both managing the cluster and querying Clipper. We should document this API using something like [Swagger](https://swagger.io/) to help people modify clipper admin or write their own tools.

**Comment by simon-mo** [comment]
This looks like a very very fun project for me to work on. Can I take this?

**Comment by dcrankshaw** [comment]
Go for it!

**Comment by dcrankshaw** [comment]
Added in ucbrise/clipper-website#15
