### ISSUE TITLE
serve-machine-learning-models-with-clipper notebook issue

### ISSUE THREAD

**Issue by MauriceManning** [ucbrise/clipper#382]
I am also having a similar issue with the quick start after installing Clipper for the first time.

Just installed Clipper on Mac OSX 10.13.2, running conda version 4.4.8 and have created this env:

(clipper27) mauricemanning:clipper$conda list
packages in environment at /Users/mauricemanning/anaconda3/envs/clipper27:

Name                    Version                   Build  Channel
appnope                   0.1.0            py27hb466136_0  
backports                 1.0              py27hb4f9756_1  
backports.shutil_get_terminal_size 1.0.0            py27hc9115de_2  
backports_abc             0.5              py27h6972548_0  
ca-certificates           2017.08.26           ha1e5d58_0  
cachetools                2.0.1                     <pip>
certifi                   2018.1.18                py27_0  
chardet                   3.0.4                     <pip>
clipper-admin             develop                   <pip>
cloudpickle               0.5.2                     <pip>
conda-api                 1.1.0                    py27_0    anaconda
decorator                 4.2.1                    py27_0  
docker                    2.7.0                     <pip>
docker-pycreds            0.2.1                     <pip>
enum34                    1.1.6            py27hf475452_1  
google-auth               1.3.0                     <pip>
idna                      2.6                       <pip>
intel-openmp              2018.0.0             h8158457_8  
ipaddress                 1.0.19                    <pip>
ipykernel                 4.8.0                    py27_0  
ipython                   5.4.1                    py27_2  
ipython_genutils          0.2.0            py27h8b9a179_0  
jupyter_client            5.2.2                    py27_0  
jupyter_core              4.4.0            py27h5ea6ba4_0  
kubernetes                4.0.0                     <pip>
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libsodium                 1.0.15               hd9e47c5_0  
mkl                       2018.0.1             hfbd8650_4  
ncurses                   6.0                  hd04f020_2  
numpy                     1.14.0           py27h8a80b8c_1  
oauthlib                  2.0.6                     <pip>
openssl                   1.0.2n               hdbc3d79_0  
pathlib2                  2.3.0            py27he09da1e_0  
pexpect                   4.3.1                    py27_0  
pickleshare               0.7.4            py27h37e3d41_0  
pip                       9.0.1            py27h1567d89_4  
prometheus-client         0.1.1                     <pip>
prompt_toolkit            1.0.15           py27h4a7b9c2_0  
ptyprocess                0.5.2            py27h70f6364_0  
pyasn1                    0.4.2                     <pip>
pyasn1-modules            0.2.1                     <pip>
pygments                  2.2.0            py27h1a556bb_0  
python                    2.7.14              hde5916a_29  
python-dateutil           2.6.1            py27hd56c96b_1  
PyYAML                    3.12                      <pip>
pyzmq                     16.0.3           py27h91ccc67_0  
readline                  7.0                  hc1231fa_4  
requests                  2.18.4                    <pip>
requests-oauthlib         0.8.0                     <pip>
rsa                       3.4.2                     <pip>
scandir                   1.6              py27h97aa1ee_0  
scikit-learn              0.19.1           py27h9788993_0  
scipy                     1.0.0            py27h793f721_0  
setuptools                38.4.0                   py27_0  
simplegeneric             0.8.1            py27h6db5e31_0  
singledispatch            3.4.0.3          py27he22c18d_0  
six                       1.11.0           py27h7252ba3_1  
sqlite                    3.21.0               h3efe00b_2  
ssl_match_hostname        3.5.0.1          py27h8780752_2  
subprocess32              3.2.7                     <pip>
tk                        8.6.7                h35a86e2_3  
tornado                   4.5.3                    py27_0  
traitlets                 4.3.2            py27hcf08151_0  
urllib3                   1.22                      <pip>
wcwidth                   0.1.7            py27h817c265_0  
websocket-client          0.46.0                    <pip>
wheel                     0.30.0           py27h677a027_1  
zeromq                    4.2.2                ha360ad0_2  
zlib                      1.2.11               hf3cbc9b_2  
(clipper27) mauricemanning:clipper

**But running into a strange import issue with conda.api**

18-01-30:15:14:30 INFO     [deployer_utils.py:49] Saving function to /tmp/clipper/tmp9aO7DQ
18-01-30:15:14:33 INFO     [deployer_utils.py:58] Anaconda environment found. Verifying packages.
18-01-30:15:14:34 INFO     [deployer_utils.py:158] 
18-01-30:15:14:34 INFO     [deployer_utils.py:159] Traceback (most recent call last):
  File "/Users/mauricemanning/anaconda3/envs/clipper27/lib/python2.7/site-packages/clipper_admin/deployers/check_and_write_deps.py", line 2, in <module>
    from conda.api import get_index
ImportError: cannot import name 'get_index'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-3feeb8a8fa24> in <module>()
      1 # Deploy the 'predict' function as a model
      2 deploy_python_closure(clipper_conn, name="tree-model",
----> 3                       version=1, input_type="doubles", func=predict)

/Users/mauricemanning/anaconda3/envs/clipper27/lib/python2.7/site-packages/clipper_admin/deployers/python.pyc in deploy_python_closure(clipper_conn, name, version, input_type, func, base_image, labels, registry, num_replicas, batch_size)
    181     serialization_dir = save_python_function(name, func)
    182     # Special handling for Windows, which uses backslash for path delimiting
--> 183     serialization_dir = posixpath.join(*os.path.split(serialization_dir))
    184     logger.info("Python closure saved")
    185     # Deploy function

/Users/mauricemanning/anaconda3/envs/clipper27/lib/python2.7/posixpath.pyc in split(p)
     83     """Split a pathname.  Returns tuple "(head, tail)" where "tail" is
     84     everything after the final slash.  Either part may be empty."""
---> 85     i = p.rfind('/') + 1
     86     head, tail = p[:i], p[i:]
     87     if head and head != '/'*len(head):

AttributeError: 'bool' object has no attribute 'rfind'

Any help would be great.

**Comment by withsmilo** [comment]
@MauriceManning : I think that the latest anaconda(4.4.8) is not compatible with Clipper. I recommend to use anaconda 4.3.X instead of 4.4.8 for a while.

**Comment by MauriceManning** [comment]
Hello
Thanks for the help.

I installed anaconda 4.3.1 on an Ubuntu instance inside of vagrant on my
Mac. Then I installed Docker-CE, then I installed Clipper from Github.

Attempted to run the test script but I receive:

In [*1*]: *from* *clipper_admin* *import* ClipperConnection,
DockerContainerManager


In [*2*]: clipper_conn = ClipperConnection(DockerContainerManager())


In [*3*]: clipper_conn.start_clipper()

18-02-01:00:29:00 WARNING  [clipper_admin.py:114] Error starting Clipper:
Unable to Connect to Docker. Please Check if Docker is running.

---------------------------------------------------------------------------

ClipperException                          Traceback (most recent call last)

<ipython-input-3-6451cc0a1d80> in <module>()

----> 1 clipper_conn.start_clipper()


/home/vagrant/anaconda3/envs/clipper27/lib/python2.7/site-packages/clipper_admin/clipper_admin.pyc
in start_clipper(self, query_frontend_image, mgmt_frontend_image,
cache_size)

*    113*         except ClipperException as e:

*    114*             logger.warning("Error starting Clipper: {}".format(e.
msg))

--> 115             raise e

*    116*

*    117*     def connect(self):


ClipperException: Unable to Connect to Docker. Please Check if Docker is
running.


However, Docker is running. The Hello World test runs as expected. Is it
possible to run Clipper inside a Vagrant container? I don't have a
different dev environment currently and I prefer not to uninstall Anaconda
on my Mac to roll back to a prior version.

Again, thanks for your help
Maurice

**Comment by MauriceManning** [comment]
ok, was able to get Clipper running on that version of anaconda in an
Ubuntu instance on Azure.
