### ISSUE TITLE
Dependency issues while building R model

### ISSUE THREAD

**Issue by vivekka93** [ucbrise/clipper#396]
While deploying a trained randomForest model in R, I come across the following error:
`Error in .local(e, collector, basedir, reset, formulaInputs, ...) : 
  don't know about randomForest.formularandomForest
`

Steps to reproduce:
Train a randomForest classifier on a sample data
```
library(randomForest)
input_data <- read.csv('sample.csv')
model <- randomForest(churn~., data = input_data, keep.forest=TRUE)
```
Wrap the model in a function
```
model_wrap <- function(input){
  output <- predict(model, input)
  return(output)
}
```
Build the model
```
Rclipper::build_model("test-model", "1", model_wrap, sample_input = input_data[1,])
```
Above step throws the error
```
Error in .local(e, collector, basedir, reset, formulaInputs, ...) : 
  don't know about randomForest.formularandomForest
```

**Comment by dcrankshaw** [comment]
@Corey-Zumar does this look familiar?

**Comment by Corey-Zumar** [comment]
@dcrankshaw I haven't seen this before. Will look into it.

**Comment by Corey-Zumar** [comment]
@vivekka93 This appears to be an issue with CodeDepends - the library used for capturing function dependencies. The problematic call is located here: https://github.com/ucbrise/clipper/blob/dd127184521c7e2590758fc18e6ee4866805fdc5/containers/R/rclipper_user/R/serialize_model.R#L116. I've filed an issue with CodeDepends: https://github.com/duncantl/CodeDepends/issues/21. I will look into finding a fix and submitting a CodeDepends PR.

**Comment by kheraAniruddh** [comment]
@vivekka93 were you able to run the randomforest model container?
