### ISSUE TITLE
Create a Conda Environment for Dev

### ISSUE THREAD

**Issue by RehanSD** [ucbrise/clipper#399]
Create a environment.yml file that installs dependencies required to develop for clipper.

**Comment by RehanSD** [comment]
Might want to make a shell script instead of just conda environment so that brew can be used to install necessary dependencies.

**Comment by simon-mo** [comment]
you mean something like this:
```sh
# dev_setup.sh
git clone --recursive https://github.com/ucbrise/clipper.git
brew install clang
conda install clipper/bin/dev_environment.yml
```
What exactly is need though?

**Comment by RehanSD** [comment]
@simon-mo I was thinking something like 
```
# dev_setup.sh
 a=$(uname)
 echo $a
 if [[ $a == "Darwin" ]] ; then
which -s brew
if [[ $? != 0 ]] ; then
# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install    /master/install)"
else
brew update
fi
# Install redis-server, docker, etc.
else
# Install redis-server, docker, etc. using sudo apt-get
fi
# Create conda environment with cloudpickle etc., have python v 2.7, etc.
conda env create -f environment.yml
```
And addressing need, I just thought that it would be helpful for on boarding dev members, because something that I noticed was time consuming was figuring out all the deps I needed to install - for example, for dependencies like kubernetes, I figured out I needed to install them by going through the errors that unittests.sh threw.

**Comment by simon-mo** [comment]
Hmmm.. I don't think the shell script is the way to go because many people has part of the environment setup. We should still have the `environment.yml` but have a separate doc like this: https://dask.pydata.org/en/latest/develop.html#development-environment

**Comment by RehanSD** [comment]
Thats interesting - but what about stuff like docker and kubernetes that are essential to install on your machine? Plus, I think if the script is written correctly to check for deps before installing, it should be lightweight for people with partial setup, but still effective and in depth enough for people who are just starting, right?

**Comment by simon-mo** [comment]
The thing is: 
- If you are developing with docker, you don't need kubernetes. 
- If you are developing with kubernetes, the minikube on mac doesn't really function nicely. (It can run simple example but developing with kubernetes on local machine is quite a challenge. Don't ask me how did i found out lol).
- I agree that a simple script can definitely help. but won't it be nice we can have a developer doc somewhere?

**Comment by RehanSD** [comment]
Actually I was thinking about a developer doc - I definitely agree that that would take care of a lot of issues - unrelated side note, I was developing with docker but not kubernetes, when I ran into an issue importing kubernetes, so I had to pip install kubernetes.

Maybe instead of heavyweight script installing everything, an environment.yml file for installs of like tensor flow, pyspark, xgboost, cloud pickle, and docker and kubernetes, and some more detailed dev docs on how to get onboard?

**Comment by dcrankshaw** [comment]
This is a great discussion. The developer documentation is definitely out of date. If you want to edit it, here's the relevant source for the website: https://github.com/ucbrise/clipper-website/blob/master/content/contributing/_index.md

Also, for more detailed development instructions on specific parts of the codebase, feel free to create or edit a README.md document in the relevant directory.

Note that for the kubernetes dependencies that @RehanSD is discussing, he's referring to the `kubernetes` python package, not the system itself. If you're developing for clipper admin, then doing a `pip install -e /path/to/clipper/clipper_admin` will install all of the python dependencies for you.

**Comment by dcrankshaw** [comment]
I agree that trying to create a general shell script might end up being overly complicated. Detailed instructions on what all the dependencies are is probably the right way to go.

**Comment by dcrankshaw** [comment]
After thinking about this more I think the right way to do this is to create a development docker image that has all of the required dependencies. Then the user can still do development in their local repo but test everything in the Docker container by doing

```sh
docker run -it --rm --mount source=/path/to/local/clipper,target=/clipper clipper/dev-image:develop
```
