### ISSUE TITLE
[Metrics] Enable user-defined metrics

### ISSUE THREAD

**Issue by simon-mo** [ucbrise/clipper#401]
We shouldn’t just let user define how the metric is computed via a configuration file. 

Following that main idea, here are three approaches:
* Pass in a queue/pipe entry point to the specific model function. For example:
    *  def sum_model(xs, metric_queue=None)
* Let the model return prediction + metric.
* (My vote): expose the metric “queue” through http endpoint, let the model container post this data to the metric end point. This does not require any code changes in RPC logic. 
    * e.g. http://localhost: 1391
    * in the model, the user can post any metric they want. (for example, the covariance, the categorical result histogram, …)
    * in the rpc.py metric server loop, we have another thread to setup a simple http server, check the posted result and move it inside the metric pipe/queue. 
    * The idea is: don’t let the user mess with the metric pipe/queue. We handle the parsing and metric forming for the user. 
    * Caveat: this might require user to both update their model and the metric_config.yaml. 

For performance: we might be able to change http server to 
1. zeromq (since they just need to expose tcp port)

**Comment by dcrankshaw** [comment]
@simon-mo just to clarify, this is for users to export metrics from their own models right?

For option 3, can you spec out a in a little more detail an example of what this would look like? This seems more complicated than letting the model return any additional metrics (option 2). Is the advantage that it doesn't require changing the RPC code?

**Comment by simon-mo** [comment]
@dcrankshaw 
Yep. The example use case I have in mind is
1. A classification model, the count for each categories. 
2. Some metrics of input data: variance, image histogram (concept drift detection)
3. Time metric for long running model. (layer-wise latency for each layer in CNN). 

Users should be responsible exporting, Clipper should be responsible handling the metric and integrat them into prometheus. 

Option 3 indeed seems complicated. My main issue with option 2 is that it returns unpredictable result. Option 2 will actually require more changes to rpc code because the (a high performance) zeromq parsing code need to take into account for both returned data and returned metrics. I would rather let the metric be independent of the prediction process such that if the metrics go down, the prediction model is still serving. 

For more detail on option3,  I believe it looks something like this:
- RPC now has three process
1. The main process running zeromq and communicates between query frontend and the model. This process will aggregate some metrics (Clipper defined, like prediction latency etc) and put inside a queue for `process 2` to pickup. 
2. The prometheus metrics exporter process responsible for aggregate all the metrics coming from the queue and export the a /metrics page for prometheus main worker to scrape
3. The user defined metrics server that takes in json object and put it inside a queue for `process 2` to pick up
- On the user side, the user just need:
```
request.post('http://localhost:1391', json=USER_METRICS)
```
- The code change is just another block of code in `rpc.py`. 

Performance Caveat:
- request module is blocking. The overhead need to be measured. Several possible solutions
1. Use async request (requires python3)
2. Bind socket and send raw data
3. Use zeromq to pass data around. 

Another note:
- I did consider passing the python queue directly to the model's predict function. But I don't know if it's doable or not. Plus, this seems to require even more changes.

**Comment by simon-mo** [comment]
Examples to be added:
1. Time metrics for preprocessing step and prediction step.
2. Result count for each classification (_concept drift_)

**Comment by simon-mo** [comment]
Closed via #440
