### ISSUE TITLE
[Metric Monitoring] Use Summary instead of Histogram

### ISSUE THREAD

**Issue by simon-mo** [ucbrise/clipper#408]
Because the latency metrics are extremely dependent on the specific jobs, hard-coded, pre-configured histogram buckets are not suitable for monitoring. A better model is [prometheus summary](https://prometheus.io/docs/concepts/metric_types/#summary), which calculate the quantiles and stream it to the prometheus server. 

But before we switch, we need to measure the performance cost, prometheus [claims](https://prometheus.io/docs/practices/histograms/#quantiles) summary have relatively heavy performance cost due to streaming calculation. We need to measure how much does it actually cost the computation resource. This does not need to be formal.

**Comment by dcrankshaw** [comment]
There are some other downsides to summaries as well. In particular, it sounds like they cannot be combined so it sounds like it would be hard to support aggregate metrics (e.g. across model containers). What if we set the histogram buckets based on the user-provided SLO?

**Comment by simon-mo** [comment]
You are right. I’m closing this. But I’ll open a new issue later to:
- find the best way to generate buckets given SLO
- add an api in clipper admin for user to specific buckets if needed.
