### ISSUE TITLE
[Metrics] Allow users to specify histogram buckets in clipper_admin

### ISSUE THREAD

**Issue by simon-mo** [ucbrise/clipper#412]
~~Currently, we support users to specify the histogram buckets in `metric_config.yaml`~~, we should enable users to set the configuration inside clipper_admin interface so users can interact with metric inside `clipper_admin` through scripting or python-cli

**Comment by simon-mo** [comment]
After some thoughts:
- `metric_config.yaml` is not visible to users and packed directly into rpc.py. This metric_config files is for Clipper's own metrics. 
- If users want to specify histogram buckets for Clipper's metrics (as overriding default buckets), one place can be at `deployer::create_endpoint`. However, this requires changes in all the possible deployers and creates unnecessary complication. 
- The preferred way to do it: Let the #401's metric server be not just a metric receiver but also some sort of api server that 
1. Enable overriding default configuration at __init__ step in ModelContainer 
2. Enable schema definition for user_defined metrics
3. Able to receive metrics during the lifetime of the model container.

**Comment by simon-mo** [comment]
/api/v1/
- add
	POST: name, type, description, (bucket)
- report
	POST: name, metric data
- update_default
	POST: name, new_bucket

**Comment by dcrankshaw** [comment]
That makes sense. I think it's logical to place *model-specific* metric configuration (whether that is changing default bucket sizes, adding their own metrics, etc), in the model container code.

**Comment by dcrankshaw** [comment]
The other thing to keep in mind is how to support these metrics in model containers implemented in other languages. Is there a way to keep the metrics exporter code unified in Python, and export to it from a model container written in Java or R?

**Comment by simon-mo** [comment]
Closed via #440
