### ISSUE TITLE
[Metrics] Docker Metric Monitoring using hardcoded ip and ports for Prometheus Configuration

### ISSUE THREAD

**Issue by hitesh-tarani** [ucbrise/clipper#424]
[docker_metric_utils.py#L156](https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/docker/docker_metric_utils.py#L156) & [docker_metric_utils.py#L176](https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/docker/docker_metric_utils.py#L176) uses hardcoded ports for prometheus configuration.
@withsmilo, PR #402 should use configuration added in #384.

**Comment by dcrankshaw** [comment]
@simon-mo can you look into this?

**Comment by simon-mo** [comment]
@dcrankshaw yeah sure it should be a quick fix. @hitesh-tarani thanks for catching this!

**Comment by simon-mo** [comment]
Will fix this in upcoming multi-tenancy support.

**Comment by simon-mo** [comment]
Closed by #503
