### ISSUE TITLE
Signal when rpc.start() is called

### ISSUE THREAD

**Issue by chester-leung** [ucbrise/clipper#425]
Use Docker health checking to signal when rpc.start() is called.

**Comment by dcrankshaw** [comment]
Will address #152

**Comment by chester-leung** [comment]
Issue: When we update a model version, we query the new model before its container and it are ready, resulting in default predictions being returned. We want to wait until the new model is ready to be queried before we go ahead and query it.


Proposal: Before `rpc.start()` is called, we know that the model and its container are ready. Therefore, in this function, we can use the SDK version of the `docker exec` command to create a file named `model_is_ready` in the model's corresponding container. 

In the Dockerfile for each model, create a `HEALTHCHECK`. The `HEALTHCHECK` command will check that there exists a file named `model_is_ready` in its container.

Before we query, we can then inspect the health of the container: `docker inspect --format='{{json .State.Health}}' <container_name>`. If the `HEALTHCHECK` returns a `healthy` status, we know that the `HEALTHCHECK` passed, meaning that there exists a file named `model_is_ready` in the container, meaning that the model and the container are ready to be queried. If the `HEALTHCHECK` returns `unhealthy`, the `HEALTHCHECK` failed, and thus the model is not yet ready to be queried. We can then `time.sleep()` or something to similar effect, periodically checking if the `HEALTHCHECK` passes. When it does, we can go ahead and query the model.

Note: The naming of the file is arbitrary, but assumes that there exists only one model per container. If there is more than one model per container, there may be an issue: the name of the file we look for before querying is hardcoded into the dockerfile, but the model name is dynamically generated, meaning that we won't be able to hardcode the filename into the dockerfile. 
I'm confident we can find devise a system as a workaround if this issue arises, but if there's only one model per container, we should be fine.

**Comment by dcrankshaw** [comment]
Thanks for writing this up. This is mostly right. Everything after the first paragraph of the proposal is spot on.

In terms of actually writing the `model_is_ready` file though, remember that `rpc.start()` is called *inside the container.* So we don't need to use docker exec, we can just directly write a file to the filesystem from within `rpc.py`. Does that make sense?

**Comment by chester-leung** [comment]
Got it. Should I go ahead and implement this?

**Comment by zoux86** [comment]
I run the clipper.ai quickstart examples, i get the error。 i should create a model_is_ready.check file?

Events:
  Type     Reason     Age                   From                Message
  ----     ------     ----                  ----                -------
  Warning  Unhealthy  11m (x1366 over 20h)  kubelet, zhiyuan-4  Readiness probe failed: cat: /model_is_ready.check: No such file or directory
  Warning  BackOff    1m (x5175 over 20h)   kubelet, zhiyuan-4  Back-off restarting failed container
