### ISSUE TITLE
[Kubernetes] What image pull policy to use?

### ISSUE THREAD

**Issue by simon-mo** [ucbrise/clipper#436]
- So we do not have a image pull policy in all Kuberntetes configuration. This will lead to Kubernetes use the cached image on the node. This is fine for Clipper's management/query frontend as well as redis. **However, model container shouldn't be cached**. 
- There is model version exposed to the user but the most likely scenario is: user use the same name for some model over and over again and probably not paying much attention to the version. 
- Fix is simple: add `imagePullPolicy: Always` somewhere [here](https://github.com/ucbrise/clipper/blob/bd579202b3ef103802c8733d4cf0672669f0841f/clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py#L188-L216)

**Comment by dcrankshaw** [comment]
So Clipper won't let you deploy multiple models with the same name and version. The idea is that once Clipper is informed of a model and version, that should be immutable. If you want to change anything, you have to register a new model or change the version. In that case, caching seems like it should be fine.
