### ISSUE TITLE
Clipper does not persist application and model details

### ISSUE THREAD

**Issue by vinotna** [ucbrise/clipper#442]
Stopping the clipper seem to remove all application and model details from clipper/redis. Please find the use case details below,

1. Start clipper 

```
clipper_conn = ClipperConnection(DockerContainerManager()
clipper_conn.start_clipper()
```

2. Register an application using clipper_conn.register_application()

3. Deploy the model using deploy_python_closure()

4. Link model to application using clipper_conn.link_model_to_app()

5. Stop clipper

`clipper_conn.stop_all()`

6. Start clipper again

`clipper_conn.start_clipper()`

7. Observe that application and models registered before stopping clipper are not present
            a. Model container corresponding to model deployed at step 3 above is not automatically started.
            b. redis-cli output indicates that application details are not present in redis.
                **Before stopping clipper:**
                   127.0.0.1:6379[1]> SELECT 5
                   OK
                  127.0.0.1:6379[5]> hgetall testApp
                  1) "input_type"
                  2) "strings"
                  3) "policy"
                  4) "DefaultOutputSelectionPolicy"
                  5) "default_output"
                  6) "-1.0"
                  7) "latency_slo_micros"
                  8) "1500000"
**After stopping and starting Clipper:**
127.0.0.1:6379[5]> SELECT 5
OK
127.0.0.1:6379[5]> hgetall testApp
(empty list or set)

Please look into this issue. Kindly let me know, if you need additional details.

Thanks,
Vinoth.

**Comment by dcrankshaw** [comment]
Hi @vinotna. This behavior happens because the Redis container gets stopped by `stop_all()` and a new one started when you call `start_clipper()` again. We recommend providing Clipper with your own, fault-tolerant and persistent Redis instance. See [this documentation](http://clipper.ai/tutorials/container_managers/) for a little more detail.
