### ISSUE TITLE
Using clipper without model selection layer

### ISSUE THREAD

**Issue by xunzhang** [ucbrise/clipper#443]
Can I use clipper without model selection layer? Say, the application directly send requests and they go to the model abstraction layer(dynamic batching) and RPC the backend serving service?

The reason why I don't want to use model selection is that sometimes when training served models, we have already decided what model to use, and I don't want additional overhead to do model selection at runtime.

**Comment by dcrankshaw** [comment]
Hi @xunzhang. This is actually the only currently supported way to use Clipper right now. We are currently working on adding back support for selection policies, but right now no selection policies are used. You link a model directly to an application and queries go straight to the model.

**Comment by henningsway** [comment]
I've read about the Selection Layer mentioned in the Paper and the talks, but not in the documentation somewhere.

I suppose, this is still a feature on the roadmap, that has been designed but not yet been implemented?

**Comment by withsmilo** [comment]
Hi, @henningsway .
Clipper team decided not to implement the selection layer. See https://github.com/ucbrise/clipper/issues/683#issuecomment-490290795.

**Comment by henningsway** [comment]
I can imagine the additional complexity (e.g. stateful containers), but it would have been such a nice set of features... :)

Thank you for the update!
