### ISSUE TITLE
Running Clipper without Docker containers at all

### ISSUE THREAD

**Issue by kvechera** [ucbrise/clipper#449]
Is there any recommended way to run the Clipper services without separating them into a Docker containers? I.e. run the query frontend with a caffe2 model rpc-server in the single machine. With no cluster management, redis etc. Something similar to plain Nginx + MXNet Model Server bundle.

**Comment by dcrankshaw** [comment]
There's nothing inherent about the Clipper implementation that requires Docker. There's a [script](https://github.com/ucbrise/clipper/blob/develop/bin/start_clipper.sh) in `bin/` that you can use to start Clipper directly outside of Docker, although it may require some tweaking (we recently added support for Prometheus which that script will not start). Once you've started Clipper, you can connect to it using `clipper_admin.ClipperConnection.connect()` (you can create a dummy DockerContainerManager object that won't get used). Finally, you can start models directly as they are just Python/Java/C++ programs, as long as you have all the dependencies installed. Keep in mind that the models expect certain environment variables to be set, you can check out the source to see what exactly those are. If you start a model directly, it still needs to be registered with Clipper via [`clipper_admin.ClipperConnection.register_model()`](http://docs.clipper.ai/en/release-0.2/#clipper_admin.ClipperConnection.register_model).

**Comment by rkooo567** [comment]
Resolved
