### ISSUE TITLE
Increase thread pool size in query front end

### ISSUE THREAD

**Issue by vijinkp** [ucbrise/clipper#523]
Is there any way to change '_size_t thread_pool_size_' parameter in '_src/libs/httpserver/server_http.hpp_' while starting the clipper through clipper_admin? If its not, please provide your comments.
Currently its hardcoded, _size_t thread_pool_size=1_.
Awaiting for the reply.

**Comment by vijinkp** [comment]
@withsmilo, Thanks a lot. Can i pull your version to test ?

**Comment by withsmilo** [comment]
@vijinkp 
Sure! Please add my repo(https://github.com/withsmilo/clipper) to your git-remote, and then checkout my `expose_http_conf` branch.

**Comment by vijinkp** [comment]
@withsmilo Thanks. I was trying to start clipper, but getting the following error.
_18-06-25:12:27:57 INFO     [docker_container_manager.py:153] [default-cluster] Starting managed Redis instance in Docker
18-06-25:12:28:00 INFO     [docker_container_manager.py:236] [default-cluster] Metric Configuration Saved at /tmp/tmpf_gyedtd.yml
Traceback (most recent call last):
  File "clipper_scripts/clipper_start.py", line 3, in <module>
    clipper_conn.start_clipper()
  File "/home/vijin/clipper/clipper_admin/clipper_admin/clipper_admin.py", line 136, in start_clipper
    http_timeout_content, num_frontend_replicas)
  File "/home/vijin/clipper/clipper_admin/clipper_admin/docker/docker_container_manager.py", line 249, in start_clipper
    self.connect()
  File "/home/vijin/clipper/clipper_admin/clipper_admin/docker/docker_container_manager.py", line 272, in connect
    'query_rest']]
KeyError: 'ai.clipper.query_frontend.query.port'_

**Comment by withsmilo** [comment]
@vijinkp 
How did you checkout my branch and test it?

**Comment by vijinkp** [comment]
@withsmilo 
i cloned your clipper repo and check out '_expose_http_conf_' branch. Then did a pip install clipper_admin pointing to _clipper_admin_ folder.

**Comment by withsmilo** [comment]
@vijinkp 
First of all, you must set development environment and build Clipper images. Refer to http://clipper.ai/contributing/

**Comment by vijinkp** [comment]
Thanks @withsmilo. I will setup dev env and test.

**Comment by withsmilo** [comment]
https://github.com/ucbrise/clipper/issues/524 was merged with ‘develop’ branch finally.
