### ISSUE TITLE
I deploy a Keras model,but get a pickle.PicklingError

### ISSUE THREAD

**Issue by dyoung23** [ucbrise/clipper#525]
I want to deploy a Keras model,code as below:
```
from clipper_admin import ClipperConnection,DockerContainerManager

clipper_conn = ClipperConnection(DockerContainerManager())
try:
	clipper_conn.start_clipper()
except Exception, e:
	print(e)
	clipper_conn.stop_all()

clipper_conn.register_application(name="hello-keras", input_type="bytes", default_output="this is default output", slo_micros=100000)

#clipper_conn.get_all_apps()
from keras.models import load_model
model = load_model('./models/model.h5')

def predict(inputs):
    import base64
    import io
    import tempfile
    import numpy as np
    from keras.preprocessing.image import load_img, img_to_array

    num_imgs = len(inputs)
    preds = []
    for i in range(num_imgs):
        # Create a temp file to write to
        tmp = tempfile.NamedTemporaryFile('wb', delete=False, suffix='.png')
        tmp.write(io.BytesIO(inputs[i]).getvalue())
        tmp.close()
  
	#read image and convert image
        image = load_img(tmp.name,grayscale=True,target_size=(28,28))
	image = img_to_array(image)
	image = np.expand_dims(image, axis=0)
	image = image.astype('float32')
	image /= 255
  
        #predict
	pred = model.predict(image)      
        preds.append(pred)
    return [str(p) for p in preds]

from clipper_admin.deployers.python import deploy_python_closure

deploy_python_closure(clipper_conn, name="keras-model", version=1, input_type="bytes", func=predict,base_image='docker.io/clipper/keras-container:develop',registry="docker.io/clipper",pkgs_to_install=[])

clipper_conn.link_model_to_app(app_name="hello-keras", model_name="keras-model")

```
But when I run this script,I get a error.
```
Traceback (most recent call last):
  File "start_keras.py", line 46, in <module>
    deploy_python_closure(clipper_conn, name="keras-model", version=1, input_type="bytes", func=predict,base_image='docker.io/clipper/keras-container:develop',registry="docker.io/clipper",pkgs_to_install=[])
  File "/usr/lib/python2.7/site-packages/clipper_admin/deployers/python.py", line 189, in deploy_python_closure
    serialization_dir = save_python_function(name, func)
  File "/usr/lib/python2.7/site-packages/clipper_admin/deployers/deployer_utils.py", line 37, in save_python_function
    c.dump(func)
  File "/usr/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 272, in dump
    raise pickle.PicklingError(msg)
pickle.PicklingError: Could not pickle object as excessively deep recursion required.
```

What's wrong with my predict function?Couldn't I deploy a Keras model in this way?

Thanks in advance.If you have a example of deploying Keras model.I will be very grateful.

**Comment by simon-mo** [comment]
Hi @dyoung23,

I noticed you put the base_image as `base_image='docker.io/clipper/keras-container:develop`. As I can recall, we never wrote a custom keras container. Did you write it? If so, how?

This error message probably comes from this line in your predict function:
```py
pred = model.predict(image) 
```
Precisely, what happened was:
- cloudpickle tries to serialize `model` object
- `model` object is referring to the global `model` object, which is a *compiled* model instance. 
- Keras is a pure python library; however, when the object was *compiled*, it instantiates tensorflow or theano object in the background. 
- Keras can be pickled, but tensorflow can't. 
- This is why serialization failed.

Steps to resolve this:
- There need to be a custom keras container just like our [mxnet](https://github.com/ucbrise/clipper/blob/develop/containers/python/mxnet_container.py), [pytorch](https://github.com/ucbrise/clipper/blob/develop/containers/python/pytorch_container.py), and [tensorflow](https://github.com/ucbrise/clipper/blob/develop/containers/python/tf_container.py) container. 
- The code most boilderplate, the idea here is that you should instantiate and compile the model in the beginning of the model container (when the model was actually ran)
- The deployer code can be found [here](https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/deployers). Using [tensorflow deployer](https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/deployers/tensorflow.py) as an example,  the interface becomes:
```py
        # Note that predict function now takes sess as an argument
        # In Keras, this will be "model"
        def predict(sess, inputs):
            # In Keras, this will be model.predict
            preds = sess.run('predict_class:0', feed_dict={'pixels:0': inputs})
            return [str(p) for p in preds]
        
       deploy_tensorflow_model(
            clipper_conn,
            model_name,
            version,
            input_type,
            predict_fn, 
            sess)
```

**Comment by dyoung23** [comment]
@simon-mo Thank you for your answer.
I saw a example which deploy a pure python model in sklearn. So I follow it  and deploy a Keras model in same way,but fail to realize the effort of Tensorflow.
I build this container in this [Dockerfile](https://gitlab.com/dyoung23/Clipper/blob/master/Dockerfile/KerasDockerfile) and rewrite [keras_container.py.](https://gitlab.com/dyoung23/Clipper/blob/master/container/keras_container.py)

I think it's wrong way,after your answer.
In fact,before I try this way,I thought using the method as your recommend,but tensorflow deployer will takes sess or path to model files as an argument, and copy your model file into the container will be started.But this function will check if all the model files are present,so it can't be used to deploy keras model directly.Should I write a keras deployer like this deployer or other methods.

Thank you.

**Comment by simon-mo** [comment]
@dyoung23 

Writing a deployer would the right way to go. Seeing the `Dockerfile` and `keras_container.py`, I think you are 99% there. The last step would just be writing the deployer that will take model file and build docker container with model file copied into it. 

Feel free to ask any more question regarding the deployers! The [tensorflow deployer](https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/deployers/tensorflow.py) is a great example to follow. 

Would you be interested in submitting a PR to contribute the Keras deployer making it into part of Clipper?

**Comment by RehanSD** [comment]
@dyoung23 We've received a lot of interest in a Keras deployer, so we were wondering if you would be interested in contributing to Clipper by submitting a PR for your deployer.

**Comment by thomasSve** [comment]
Has this issue been moved forward? Is the keras deployer being added any time soon?

**Comment by eavidan** [comment]
@simon-mo 
I have recently implemented a Keras deployer by rewriting the Tensorflow one
just opened a PR for this #594

**Comment by rkooo567** [comment]
@dyoung23 https://github.com/ucbrise/clipper/pull/594 has been merged thanks to @eavidan's efforts! You can deploy keras using clipper from the next release.
