### ISSUE TITLE
when I deploy clipper in kube cluster,but" ClipperException: Error connecting to Kubernetes cluster. No external node addresses found"

### ISSUE THREAD

**Issue by xuguangzhao** [ucbrise/clipper#528]
clipper_conn.start_clipper(query_frontend_image="clipper/query_frontend", mgmt_frontend_image="clipper/management_frontend")
18-07-04:05:59:12 INFO     [kubernetes_container_manager.py:33] {u'kind': u'deployments', u'group': u'extensions', u'name': u'redis'} already exists, skipping!
18-07-04:05:59:12 INFO     [kubernetes_container_manager.py:33] {u'kind': u'services', u'name': u'redis'} already exists, skipping!
18-07-04:05:59:22 INFO     [kubernetes_container_manager.py:33] {u'kind': u'deployments', u'group': u'extensions', u'name': u'mgmt-frontend'} already exists, skipping!
18-07-04:05:59:22 INFO     [kubernetes_container_manager.py:33] {u'kind': u'services', u'name': u'mgmt-frontend'} already exists, skipping!
18-07-04:05:59:22 INFO     [kubernetes_container_manager.py:33] {u'kind': u'deployments', u'group': u'extensions', u'name': u'query-frontend-0'} already exists, skipping!
18-07-04:05:59:23 INFO     [kubernetes_container_manager.py:33] {u'kind': u'services', u'name': u'query-frontend'} already exists, skipping!
18-07-04:05:59:23 INFO     [kubernetes_metric_utils.py:31] {u'kind': u'configmaps', u'name': u'prometheus-config'} already exists, skipping!
18-07-04:05:59:23 INFO     [kubernetes_metric_utils.py:31] {u'kind': u'deployments', u'group': u'extensions', u'name': u'metrics'} already exists, skipping!
18-07-04:05:59:23 INFO     [kubernetes_metric_utils.py:31] {u'kind': u'services', u'name': u'metrics'} already exists, skipping!
18-07-04:05:59:23 ERROR    [kubernetes_container_manager.py:238] Error connecting to Kubernetes cluster. No external node addresses found
18-07-04:05:59:23 WARNING  [clipper_admin.py:129] Error starting Clipper: Error connecting to Kubernetes cluster. No external node addresses found
---------------------------------------------------------------------------
ClipperException                          Traceback (most recent call last)
<ipython-input-4-4cdd8f3d20e3> in <module>()
----> 1 clipper_conn.start_clipper(query_frontend_image="clipper/query_frontend", mgmt_frontend_image="clipper/management_frontend")

/root/anaconda2/lib/python2.7/site-packages/clipper_admin/clipper_admin.pyc in start_clipper(self, query_frontend_image, mgmt_frontend_image, cache_size, num_frontend_replicas)
    128         except ClipperException as e:
    129             logger.warning("Error starting Clipper: {}".format(e.msg))
--> 130             raise e
    131 
    132     def connect(self):

ClipperException: Error connecting to Kubernetes cluster. No external node addresses found

**Comment by simon-mo** [comment]
Is the kubernetes cluster running in internal IP? If so you can start clipper with 
`clipper_conn = ClipperConnection(KubernetesContainerManager(useInternalIP=True))`


```
        useInternalIP : bool, optional
            Use Internal IP of the K8S nodes . If ``useInternalIP`` is set to False, Clipper will
            throw an exception if none of the nodes have ExternalDNS.
            If ``useInternalIP`` is set to true, Clipper will use the Internal IP of the K8S node
            if no ExternalDNS exists for any of the nodes.
```

**Comment by xuguangzhao** [comment]
done ,thanks
