### ISSUE TITLE
Error while running R package 

### ISSUE THREAD

**Issue by aliraza0337** [ucbrise/clipper#530]
Thanks for giving me the pointer everything seems to be in order but I am still getting this error while trying to deploy the R model, 

**Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rclipper/build_container.py", line 9, in <module>
    version.__registry__, version.__version__)
AttributeError: 'module' object has no attribute '__registry__'
To deploy this model, execute the following command from a connected ClipperConnection object `conn`:
conn.deploy_model("test-model", "1", "ints", "test-model:1", num_replicas=<num_container_replicas>)**

Any Idea why I am getting this?

**Comment by simon-mo** [comment]
Hi @aliraza0337 , this might be clipper version issue. 

Can you run `pip install git+https://github.com/ucbrise/clipper.git#subdirectory=clipper_admin` to make sure the installed clipper version matches the version Rclipper is calling from. 

Basically what happened was:
- RClipper will try to call a python script. This script is up to date.
- The script will try to call `clipper_admin` package installed. 
- The package is not up to date with script.

**Comment by csmithnm** [comment]
I am getting a similar error with clipper-develop. 
I tried `pip install git+https://github.com/ucbrise/clipper.git#subdirectory=clipper_admin` and it did NOT work.

Traceback (most recent call last):
  File "/usr/local/lib/R/site-library/Rclipper/build_container.py", line 5, in <module>
    from clipper_admin import DockerContainerManager, ClipperConnection, ClipperException
  File "/home/ubuntu/clipper-develop/clipper_admin/clipper_admin/clipper_admin.py", line 27, in <module>
    from .container_manager import CONTAINERLESS_MODEL_IMAGE, ClusterAdapter
ValueError: Attempted relative import in non-package
To deploy this model, execute the following command from a connected ClipperConnection object `conn`:
conn.deploy_model("r-csus-tc", "6", "strings", "r-csus-tc:6", num_replicas=<num_container_replicas>)

**Comment by aliraza0337** [comment]
@simon-mo The above error is gone after I ran the update but now I am getting the following, while running the admin

**Traceback (most recent call last):
  File "admin.py", line 7, in <module>
    conn.connect()
  File "/Library/Python/2.7/site-packages/clipper_admin/clipper_admin.py", line 147, in connect
    self.cm.connect()
  File "/Library/Python/2.7/site-packages/clipper_admin/docker/docker_container_manager.py", line 261, in connect
    self.redis_port = all_labels[CLIPPER_DOCKER_PORT_LABELS['redis']]
KeyError: 'ai.clipper.redis.port'**

Thanks for your help

**Comment by simon-mo** [comment]
@aliraza0337 You might need to kill the existing clipper docker containers before starting a new connection. From my experience, this error occurs when there's dangling containers. You can do so by running `docker kill $(docker ps -q)` in your terminal.

**Comment by simon-mo** [comment]
@csmithnm where are you running the the script? From the traceback, the clipper package that the R/python runtime found was located at `/home/ubuntu/clipper-develop/clipper_admin/....` however it should be located at either a conda environement of python runtime (typically they are located under a directory called `site-pakages` within python folder. 

I have seen this error occurs when i start my R or python REPL within clipper folder. Most of the time, switching to some other place to run the REPL will help.

**Comment by aliraza0337** [comment]
I tried the above command and after that ran `docker container ls`it showed no container, but I am still getting the above error.
Also in the python code, does it have to do anything that we aren't start clipper and right away calling connect?

http://clipper.ai/tutorials/r-deployment/#deploy-and-link-the-model

**Comment by csmithnm** [comment]
It now works. I was forcing Python to look in the /home/ubuntu/clipper-develop/clipper_admin/clipper_admin/clipper_admin.py via the PYTHONPATH environment variable. I removed the PYTHONPATH environment variable and now the build works!!!  Thank You!  I have been working getting Clipper to with with R for MONTHS without any luck. I am hoping this version will do the trick.

**Comment by csmithnm** [comment]
But be careful with the `clipper-develop` version when you try to deploy. The Clipper developers added `default-cluster` onto the name of the Docker image:

`clipper_conn.deploy_model("r-csus-tc", "6", "strings", "default-cluster-r-csus-tc:6", num_replicas=1)`

**Comment by aliraza0337** [comment]
One more thing even if when I run the R code given here: 
http://clipper.ai/tutorials/r-deployment/#build-a-model
It gives the expected output, but when I run `docker container ls` I don't see any container.

**Comment by aliraza0337** [comment]
@simon-mo @csmithnm 
In case you missed it, just bumping it up.
This is the output if starting R model.
```
Alis-MacBook-Pro:RCode aliraza$ Rscript model.R 
Loading required package: CodeDepends
Loading required package: histry
[1] "Serialized list of dependent libraries: Rclipper: knitr: histry: CodeDepends: stats: graphics: grDevices: utils: datasets: methods: base"
[1] "Serialized model function!"
[1] "Done!"
18-07-07:16:40:10 INFO     [clipper_admin.py:467] [default-cluster] Building model Docker image with model data from /tmp/clipper//2018-07-07-16-40-08.583
18-07-07:16:40:12 INFO     [clipper_admin.py:472] [default-cluster] Step 1/2 : FROM clipper/r-container-base:develop
18-07-07:16:40:12 INFO     [clipper_admin.py:472] [default-cluster]  ---> b81704bec464
18-07-07:16:40:12 INFO     [clipper_admin.py:472] [default-cluster] Step 2/2 : COPY /tmp/clipper//2018-07-07-16-40-08.583 /model/
18-07-07:16:40:12 INFO     [clipper_admin.py:472] [default-cluster]  ---> c51d1cce5daf
18-07-07:16:40:12 INFO     [clipper_admin.py:472] [default-cluster] Successfully built c51d1cce5daf
18-07-07:16:40:12 INFO     [clipper_admin.py:472] [default-cluster] Successfully tagged default-cluster-test-model:1
18-07-07:16:40:12 INFO     [clipper_admin.py:474] [default-cluster] Pushing model Docker image to default-cluster-test-model:1
To deploy this model, execute the following command from a connected ClipperConnection object `conn`:
conn.deploy_model("test-model", "1", "ints", "test-model:1", num_replicas=<num_container_replicas>)

```
This is when I start admin: 

```
Traceback (most recent call last):
  File "check.py", line 4, in <module>
    conn.connect()
  File "/Library/Python/2.7/site-packages/clipper_admin/clipper_admin.py", line 147, in connect
    self.cm.connect()
  File "/Library/Python/2.7/site-packages/clipper_admin/docker/docker_container_manager.py", line 261, in connect
    self.redis_port = all_labels[CLIPPER_DOCKER_PORT_LABELS['redis']]
KeyError: 'ai.clipper.redis.port'
```

what do you think causing it crash, second after running the R model, I don't see any container. when I do `docker container ls`.

**Comment by withsmilo** [comment]
@aliraza0337 : 
http://clipper.ai/tutorials/r-deployment/#deploy-and-link-the-model assumes that a Clipper cluster is running on localhost with a registered application that has the name app1. So you must execute other commands before it.
```python
from clipper_admin import ClipperConnection, DockerContainerManager
conn = ClipperConnection(DockerContainerManager())
# Start Clipper cluster
conn.start_clipper()
# Register 'app1' application to Clipper
conn.register_application(name="app1", input_type="ints", default_output="-1.0", slo_micros=100000)
```
and then,
```python
conn.connect()

# Deploy a single replica of the model
conn.deploy_model(name="test-model", version="1", input_type="ints", image="test-model:1", replicas=1)

conn.link_model_to_app(app_name="app1", model_name="test-model")
```

**Comment by aliraza0337** [comment]
Hi @withsmilo  
I have tried what you suggested up there, I get the following error.
`18-07-09:19:54:53 INFO     [docker_container_manager.py:151] [default-cluster] Starting managed Redis instance in Docker
18-07-09:19:54:55 INFO     [docker_container_manager.py:229] [default-cluster] Metric Configuration Saved at /private/var/folders/9l/nb5rkvcx70xgfcttqmzqc7dm0000gn/T/tmptIBmbl.yml
18-07-09:19:54:56 INFO     [clipper_admin.py:138] [default-cluster] Clipper is running
18-07-09:19:54:56 INFO     [clipper_admin.py:215] [default-cluster] Application app1 was successfully registered
18-07-09:19:54:56 INFO     [clipper_admin.py:151] [default-cluster] Successfully connected to Clipper cluster at localhost:1337
18-07-09:19:54:56 INFO     [docker_container_manager.py:353] [default-cluster] Found 0 replicas for test-model:1. Adding 1
Traceback (most recent call last):
  File "/Users/aliraza/Desktop/SummerEco/RCode/check.py", line 11, in <module>
    conn.deploy_model("test-model", "1", "ints", "test-model:1", num_replicas=1)
  File "/Library/Python/2.7/site-packages/clipper_admin/clipper_admin.py", line 560, in deploy_model
    num_replicas=num_replicas)
  File "/Library/Python/2.7/site-packages/clipper_admin/docker/docker_container_manager.py", line 279, in deploy_model
    self.set_num_replicas(name, version, input_type, image, num_replicas)
  File "/Library/Python/2.7/site-packages/clipper_admin/docker/docker_container_manager.py", line 358, in set_num_replicas
    image)
  File "/Library/Python/2.7/site-packages/clipper_admin/docker/docker_container_manager.py", line 333, in _add_replica
    **self.extra_container_kwargs)
  File "/Library/Python/2.7/site-packages/docker/models/containers.py", line 768, in run
    self.client.images.pull(image, platform=platform)
  File "/Library/Python/2.7/site-packages/docker/models/images.py", line 412, in pull
    self.client.api.pull(repository, tag=tag, **kwargs)
  File "/Library/Python/2.7/site-packages/docker/api/image.py", line 399, in pull
    self._raise_for_status(response)
  File "/Library/Python/2.7/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Library/Python/2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("pull access denied for test-model, repository does not exist or may require 'docker login'")
[Finished in 4.1s with exit code 1]
[shell_cmd: python -u "/Users/aliraza/Desktop/SummerEco/RCode/check.py"]
[dir: /Users/aliraza/Desktop/SummerEco/RCode]
[path: /Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS]`



This is my Rcode: 
`library(Rclipper)

pred_fn = function(inputs) {
return(lapply(inputs, function(input) {
return(as.character(length(input)))
}))
}

Rclipper::build_model("test-model", "1", pred_fn, sample_input = as.integer(c(1,2,3)))
`

**Comment by withsmilo** [comment]
@aliraza0337 : 
You got this error,
```
docker.errors.ImageNotFound: 404 Client Error: Not Found ("pull access denied for test-model, repository does not exist or may require 'docker login'")
```
Did you execute `Rclipper::build_model("test-model", ...)`? If you had the success to build your R model, you can find your own Docker image(test-model) through `docker images`.

**Comment by aliraza0337** [comment]
yes, I do execute that, as I you can see in my R code above at the bottom of my comment, this is how my Rcode looks and it runs with out error:
""
library(Rclipper)
pred_fn = function(inputs) {
return(lapply(inputs, function(input) {
return(as.character(length(input)))
}))
}
Rclipper::build_model("test-model", "1", pred_fn, sample_input = as.integer(c(1,2,3)))
""

and when I view images I see: 
default-cluster-test-model         1                              a9c74a7b65ac        19 seconds ago      895MB
So i updated the python admin code and changed as follows:
conn.deploy_model("test-model", "1", "ints", "default-cluster-test-model:1", num_replicas=1)
It makes the error go away, but still not working.

**Comment by withsmilo** [comment]
1. Please share your /Users/aliraza/Desktop/SummerEco/RCode/check.py.
2. Please share your Docker image list through `docker images`.

**Comment by aliraza0337** [comment]
check.py

```
from clipper_admin import ClipperConnection, DockerContainerManager
conn = ClipperConnection(DockerContainerManager())
# Start Clipper cluster
conn.start_clipper()
# Register 'app1' application to Clipper
conn.register_application(name="app1", input_type="ints", default_output="-1.0", slo_micros=100000)
conn.connect()

# Deploy a single replica of the model
#conn.deploy_model(name="test-model", version="1", input_type="ints", image="test-model:1", replicas=1)
conn.deploy_model("test-model", "1", "ints", "test-model:1", num_replicas=1)

conn.link_model_to_app(app_name="app1", model_name="test-model")
```
docker images
```
REPOSITORY                         TAG                            IMAGE ID            CREATED             SIZE
default-cluster-test-model         1                              9c35423eda51        29 seconds ago      895MB
<none>                             <none>                         a9c74a7b65ac        7 minutes ago       895MB
<none>                             <none>                         ebe176dec507        32 minutes ago      895MB
invoker                            latest                         3d20b3124b85        About an hour ago   392MB
whisk/invoker                      latest                         3d20b3124b85        About an hour ago   392MB
whisk/controller                   latest                         671ebdeba61c        About an hour ago   312MB
controller                         latest                         671ebdeba61c        About an hour ago   312MB
scala                              latest                         7979151227d9        About an hour ago   199MB
whisk/scala                        latest                         7979151227d9        About an hour ago   199MB
<none>                             <none>                         086803fedf77        5 hours ago         895MB
<none>                             <none>                         5ad6ef43085b        5 hours ago         895MB
<none>                             <none>                         2542ee614c64        5 hours ago         895MB
<none>                             <none>                         cf48375592ef        5 hours ago         895MB
<none>                             <none>                         9fdaa6b79592        5 hours ago         895MB
<none>                             <none>                         55ab263006bf        5 hours ago         895MB
<none>                             <none>                         3d604fd6fe8a        5 hours ago         895MB
<none>                             <none>                         1cc0c2719348        5 hours ago         895MB
<none>                             <none>                         3210a27d6855        5 hours ago         895MB
<none>                             <none>                         9ef18972ed0d        5 hours ago         895MB
<none>                             <none>                         0d1922e38d68        5 hours ago         895MB
openwhisk/apigateway               latest                         7bcaf99cc58d        8 hours ago         555MB
openwhisk/invoker                  latest                         34da23791748        10 hours ago        392MB
openwhisk/controller               latest                         4ea6bda7a2b8        10 hours ago        312MB
adoptopenjdk/openjdk8              jdk8u172-b11-alpine            1cd02d9d8566        30 hours ago        193MB
<none>                             <none>                         41a930450952        2 days ago          895MB
<none>                             <none>                         a47255ab3cc1        2 days ago          895MB
<none>                             <none>                         ffce634f4c04        2 days ago          895MB
<none>                             <none>                         27b0933d5ecd        2 days ago          895MB
<none>                             <none>                         d73b5663977d        2 days ago          895MB
<none>                             <none>                         bcc16b928915        2 days ago          895MB
<none>                             <none>                         c51d1cce5daf        2 days ago          895MB
<none>                             <none>                         72348ee9e11d        3 days ago          895MB
<none>                             <none>                         c73e9f2cc6f6        3 days ago          895MB
<none>                             <none>                         19a4e18370cf        3 days ago          895MB
<none>                             <none>                         8655a77571c2        3 days ago          895MB
default-cluster-sum-model1         2                              7c9abfcc8417        3 days ago          460MB
default-cluster-sum-model          1                              e58781ea5bb6        3 days ago          460MB
<none>                             <none>                         ee1e23344228        3 days ago          895MB
zookeeper                          3.4                            ef4e95d0f320        3 days ago          147MB
redis                              alpine                         4a1adec0b3ab        3 days ago          28.4MB
clipper/python-closure-container   develop                        76a098e0f6ee        3 weeks ago         460MB
clipper/query_frontend             develop                        e9f3003fe4c8        3 weeks ago         1.85GB
clipper/management_frontend        develop                        52b6407ef38a        3 weeks ago         1.85GB
clipper/frontend-exporter          develop                        c29b40eb6336        4 weeks ago         148MB
clipper/r-container-base           develop                        b81704bec464        4 weeks ago         895MB
minio/minio                        RELEASE.2018-05-04T23-13-12Z   7c079871e874        2 months ago        29.4MB
openwhisk/nodejs6action            latest                         18e881851d8e        2 months ago        538MB
prom/prometheus                    v2.1.0                         c8ecf7c719c1        5 months ago        112MB
couchdb                            1.6                            827c620e2004        8 months ago        226MB
confluentinc/cp-kafka-rest         3.3.1                          12a1d317a72a        8 months ago        440MB
landoop/kafka-topics-ui            0.9.3                          78d75abcbd70        8 months ago        26MB
actionproxy                        latest                         25d1878c2f31        9 months ago        109MB
openwhisk/dockerskeleton           latest                         25d1878c2f31        9 months ago        109MB
whisk/actionproxy                  latest                         25d1878c2f31        9 months ago        109MB
wurstmeister/kafka                 0.11.0.1                       b994f889ee53        9 months ago        265MB
ddragosd/ansible                   2.4.0.0-debian8                83abf1a2bf1c        9 months ago        243MB
redis                              2.8                            481995377a04        2 years ago         186MB
```

**Comment by withsmilo** [comment]
@simon-mo added 'default-cluster' to Docker image's name on the latest 'develop' branch by [this commit](https://github.com/ucbrise/clipper/commit/3c5a1cc6ce59e0ccd778f526a50808d0e7b2576f#diff-e1c99d5ca218bda649bbaac7cf045cf4R459). So I think that you must execute like this,
```
conn.deploy_model("test-model", "1", "ints", "default-cluster-test-model:1", num_replicas=1)
```

**Comment by aliraza0337** [comment]
Okay this time, it didnt give error, but not correct out put. I guess CURL command has issue: 

curl -X POST --header "Content-Type:application/json" -d '{"input": [1,2,3,4]}' 127.0.0.1:1337/app1/predict

As we don't have predict here?

**Comment by aliraza0337** [comment]
never mind, it seem to be working. Thanks alot :)

**Comment by withsmilo** [comment]
@aliraza0337 👍 Please close this issue if you resolved the problem.

**Comment by aliraza0337** [comment]
@withsmilo it works sometime and sometime its not giving the correct output :/
It gives, 
{"query_id":18,"output":-1.0,"default":true,"default_explanation":"No connected models found for query"}

**Comment by withsmilo** [comment]
Check Clipper_query_frontend's logs when querying your inputs.
```
$ docker container ls
$ docker logs --tail 100 -f <query_frontend_container_ID>
```
