### ISSUE TITLE
How to predict using REST for a batch of rows?

### ISSUE THREAD

**Issue by donigian** [ucbrise/clipper#544]
How would you extend `get_test_point()` in this [example](http://clipper.ai/tutorials/xgboost_deployment/) to support a predict call using REST for a batch of rows?
`Note:` I've modified the example to use `doubles` instead of `integers`.

I've tried to modify the following snippet to use an array of arrays, but running into the error below.
```
import requests, json
# Get Address
addr = clipper_conn.get_query_addr()
# Post Query
response = requests.post(
     "http://%s/%s/predict" % (addr, 'xgboost-test'),
     headers={"Content-type": "application/json"},
     data=json.dumps({
         'input': batch_test_points()
     }))
result = response.json() 
result
```
where `batch_test_points()` returns `[ [],[] ]`. For model training, I used `df.values.tolist()` which returns a list of lists. For this reason, I expected the list of lists of work during inference.

error:
```
>>> result = response.json()
>>> result
{'error': 'Json error', 'cause': 'Error parsing JSON: Array input of type Array is not of type double. Expected JSON schema: \n  {\n   "input" := [double] | [int] | [string] | [byte] | [float],\n  }\n'}
```

**Comment by ssuerbier** [comment]
I just ran into the same issue. If you check this issue: https://github.com/ucbrise/clipper/issues/292 (and the linked PR) it tells you to send the data under `input_batch` instead of `input`. So try:

```
response = requests.post(
     "http://%s/%s/predict" % (addr, 'xgboost-test'),
     headers={"Content-type": "application/json"},
     data=json.dumps({
         'input_batch': batch_test_points()
     }))
```

This feature is not documented yet in http://clipper.ai/api/api.html as it seems.

**Comment by simon-mo** [comment]
Thanks for catching that! 

Yes, input_batch is the way to go. I’ll add documentation for rest api as well as update tutorial to introduce batch_predict.

**Comment by donigian** [comment]
Excellent, updating the documentation will provide clarity.
