### ISSUE TITLE
Unable to deploy scikit-learn model using deploy_python_closure function

### ISSUE THREAD

**Issue by kheraAniruddh** [ucbrise/clipper#546]
Hi,

I tried deploying a toy model using scikit-learn on Clipper cluster using DockerContainerManager.

It's successfully able to build the docker image but gets stuck on

> 18-08-05:18:37:04 INFO [docker_container_manager.py:353] [default-cluster] Found 0 replicas for tree-model:1. Adding 1

On inspecting the docker container, first it exits and on checking the logs of the respective container I get:

> Starting Python Closure container Connecting to Clipper with default port: 7000 Encountered an ImportError when running container. You can use the pkgs_to_install argument when calling clipper_admin.build_model() to supply any needed Python packages.

I think this is a common error, even others encountered it: https://github.com/ShuaiW/serve-ml-with-clipper/issues/3

I would like to mention that I declared the dependencies like scikit-learn, pandas with pkgs_to_install (which I could see got installed on the container)

Any help would be really appreciated!

**Comment by withsmilo** [comment]
@kheraAniruddh 
How did you execute Clipper? Please share your codes with me.

**Comment by RehanSD** [comment]
Hi @kheraAniruddh!
Could you please post your call to deploy python closure? To be able to deploy a scikit learn model, you need to install the dependencies correctly, so you should add `numpy` and `scipy`, and then `scikit-learn` to packages to install.

**Comment by RehanSD** [comment]
I’m fairly certain that the issue here is that you have to install the dependencies for scikit learn manually.

**Comment by kheraAniruddh** [comment]
@RehanSD, I am absolutely certain that I have specified the dependencies using the pkgs_to_install and they are installed on the container.
(numpy, scipy) gets installed as the scikit dependencies

**Comment by RehanSD** [comment]
@kheraAniruddh, it would still help to see your code.

**Comment by kheraAniruddh** [comment]
@withsmilo 
```
# Deploy the 'predict' function as a model
deploy_python_closure(clipper_conn, name="titanictreemodel",
                      version=1, input_type="strings", func=predict, pkgs_to_install=['scikit-learn','pandas'])
```

**Comment by kheraAniruddh** [comment]
@RehanSD 
<img width="738" alt="screen shot 2018-08-05 at 7 26 36 pm" src="https://user-images.githubusercontent.com/22443954/43693907-82ee24ca-98e5-11e8-8564-867995e50dfd.png">

**Comment by kheraAniruddh** [comment]
I appreciate your help. Even you can look into the link I specified in my initial comment. That toy example is giving the same error.

**Comment by kheraAniruddh** [comment]
@RehanSD, you were right! On specifying the numpy and scipy packages, the model got deployed!

Thanks! I think you can close this issue.
