### ISSUE TITLE
Question about "data=json.dumps({"input": X})" when data input to a deployed model

### ISSUE THREAD

**Issue by yuezha01** [ucbrise/clipper#552]
Hi,

I am new to Clipper and very excited about the deployment feature offered by Clipper. But I am very confused with the input to a deployed model using the following code. 
`requests.post(url, headers, data=json.dumps({"input": X}))`
Based on the examples on Clipper website, I came up with the following naive tests for different X. But I am having a hard time understanding what goes wrong in my programs.

I started with a very simple example when X is just a list of numbers (doubles or ints)
```
import numpy as np
import requests, json
from clipper_admin import ClipperConnection, DockerContainerManager

clipper_conn = ClipperConnection(DockerContainerManager())
clipper_conn.start_clipper()
clipper_conn.register_application(name="numeric", input_type="doubles", 
                                  default_output="-1.0", slo_micros=10000000)

#works
def test1(inputs):
    result = [elem for elem in inputs]
    return result

#work
def test2(inputs):
    n = len(inputs)
    result = []
    for i in range(n):
        result.append(inputs[i])
    return result

#error
def test3(inputs):
    n = len(inputs)
    return [np.double(n)]

#error
def test4(inputs):
    result = []
    result.append(inputs[0])
    return result

from clipper_admin.deployers import python as python_deployer
python_deployer.deploy_python_closure(clipper_conn, name="test1-numeric", version=1, input_type="doubles", func=test1)
clipper_conn.link_model_to_app(app_name="numeric", model_name="test1-numeric")
headers = {"Content-type": "application/json"}
requests.post("http://localhost:1337/numeric/predict", headers=headers, 
                         data=json.dumps({"input": [1.0, 2.0, 3.0]})).json()
clipper_conn.stop_all()
```

For test1 and test2, the output is normal. Then I thought [1.0, 2.0, 3.0] is passed as a list into the argument "inputs" in the above python functions. However, there are only very simple operations on "inputs" in test3 and test4, so I don't understand why they generate errors like this:
{'query_id': 0,
 'output': -1.0,
 'default': True,
 'default_explanation': 'Failed to retrieve a prediction response within the specified latency SLO'}

Is there any tutorial that explain the input format with details, especially when the input is more complex (e.g. a list of array, integer and string mixing together)? I think I can first transfer it to JSON by doing "data=json.dumps({"input": json.dumps(X)}). But, again, I don't understand how to use it as an input in the linked python function. Please advise. 

Thanks a lot!

**Comment by RehanSD** [comment]
Hi @moon412!
I think the issue here is that the output of the predict function needs to be of the same length as the input. To make test 3 work, for example, all you need to do is change it to this:
```python
def test3_new(inputs):
    return [np.doubles(len(inputs))] * len(inputs)
```
In effect, it doesn’t matter what the elements of the list returned by the function is - just that `len(inputs) == len(test3_new(inputs))`. This is because of adaptive batching - to find the optimal batch size for a model container, Clipper sends batches of different sizes to discover which gets the best throughout while still meeting the latency SLO.

**Comment by yuezha01** [comment]
Thanks @RehanSD ! 
Your reply solves the puzzle for me. I was so confused what the data structure of "inputs" looks like.
