### ISSUE TITLE
Dockerfile for  python36-closure-container image 

### ISSUE THREAD

**Issue by robi56** [ucbrise/clipper#553]
I am searching  to find the Dockrfile * of *python36-closure-container** image from the link https://hub.docker.com/r/clipper/python36-closure-container/
but it doesn't exist there. 
Where I find it?

**Comment by withsmilo** [comment]
@robi56 : 
All the dockerfiles are [here](https://github.com/ucbrise/clipper/tree/develop/dockerfiles).
