### ISSUE TITLE
Nvidia driver,cuda, cudnn,tensorflow-gpu DockerFile  Image for Model Container

### ISSUE THREAD

**Issue by robi56** [ucbrise/clipper#554]
I am trying  to install nvidia driver cuda cudnn and related dependcy for running models in gpu mode.

First of all , I built a custom image with the following code 

`FROM clipper/python36-closure-container:0.3

RUN mkdir -p /python-deps

RUN apt-get update 

RUN apt-get install -y libgtk2.0-dev

RUN pip install pillow

RUN pip install opencv-python

RUN pip install --default-timeout=100000 tensorflow-gpu

RUN pip install cython

RUN pip install --default-timeout=100000 scipy

RUN pip install --default-timeout=100000 sklearn

ENV PYTHONPATH=$PYTHONPATH:/python-deps/`

and I built a model container with the image and link it to the clipper-admin by the following code
`clipper_conn.register_application(name="opencv2", input_type="bytes", default_output="-1.0", slo_micros=300000000)
python_deployer.deploy_python_closure(clipper_conn, name="detectface", version=2,num_replicas=2, input_type="bytes", func=detectface,base_image='face_image:latest')
clipper_conn.link_model_to_app(app_name="opencv2", model_name="detectface")`

After doing these stuff ,I am trying to import tensorflow from terminal  in docker 

`import tensorflow as tf`
but it says the error 
**ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory**
To resolve this i am tring to install **Nvidia driver,cuda, cudnn,tensorflow-gpu** from the following 
https://gist.github.com/ashokpant/5c4e9481615f54af4025ab2085f85869
https://gist.github.com/niderhoff/52c514f20337516500084dd7b17af7e2

But i can't install nvidia-driver, cuda , nvidia-container-runtime properly.

I am searching for Dockerfile that includes all dependency to build a docker container that supports gpu computing and i don't want to install any dependency after  logging to the docker manually.

Is there is any docker image available that supports GPU?

**Comment by withsmilo** [comment]
@robi56 : 
How about refer to [this site](https://github.com/NVIDIA/nvidia-docker)?

**Comment by RehanSD** [comment]
Hi @robi56! Clipper will soon include native CUDA 10 support for PyTorch and TF! Here is a [PR](https://github.com/ucbrise/clipper/pull/629) adding pytorch support with docker! This can also serve as a handy guide if you want to write your own Dockerfile.

**Comment by RehanSD** [comment]
This PR addresses this issue #669
