### ISSUE TITLE
dynamic input which leads to change in output, errors out

### ISSUE THREAD

**Issue by kheraAniruddh** [ucbrise/clipper#555]
Hi,

I cam across this problem. I have an arbitrary python model, which works well when I send an input of same length as what I sent initially.

What I mean is, suppose my input_type="strings", which I use to send an array of json objects (each json object corresponds to one prediction).

After successfully deploying the model, if I send my input with suppose 1 json object in the array, it works well or if I send with say 5 json object it works well.

But on subsequent requests if I change the number of json objects in the array, it errors out.

I understand this might be due to the fact we are caching the predictions for incorporating the feedback.

Is there a way I can avoid clipper doing this??

The error:

`Traceback (most recent call last):
  File "/container/python_closure_container.py", line 61, in <module>
    rpc_service.start(model)
  File "/container/rpc.py", line 726, in start
    self.server.run(collect_metrics=self.collect_metrics)
  File "/container/rpc.py", line 353, in run
    prediction_request)
  File "/container/rpc.py", line 167, in handle_prediction_request
    (len(prediction_request.inputs), len(outputs)))
rpc.PredictionError: 'Expected model to return 1 outputs, found 2 outputs'
Encountered error not related to missing packages. Please refer to the container log to diagnose.`

Also, if I change the input string itself, which basically calls a different model under the hood (I am using predict function as the wrapper function), it errors out.

Possibly I can change the code: line number 167 of rpc.py. Is there a way like providing a parameter to avoid such behavior?

**Comment by withsmilo** [comment]
@kheraAniruddh : 
Your model must return the same length as inputs'. I think that your `predict` function has something wrong. Please share your `predict` function.

**Comment by kheraAniruddh** [comment]
@withsmilo 
Yes I understand that. What I meant I am changing the length of input, which is resulting in this error.
In simple words, I would like to make my predict function to give me predictions for say 'n' people, where 'n' will change with each request.
That is, model should predict for n samples.
 
Does it make sense?

**Comment by withsmilo** [comment]
@kheraAniruddh : 
I understand. You can return prediction results using json format like this,
```python
def predict_function(inputs):
    def generate_output_json_str(i, res, n):
        output = {
            'input': i,
            'output': [res] * n
        }
        return json.dumps(output)
    res = ....
    n = ....
    return [generate_output_json_str(i, res, n) for i in inputs]
```

**Comment by kheraAniruddh** [comment]
Well  after debugging  a bit, I understood the inputs length will always be 2 and inputs is NOT EQUAL to the list of strings which I passed.

Taking the example on the github and clipper.ai :

`def feature_sum(xs):
    return [str(sum(x)) for x in xs]`

`$ curl -X POST --header "Content-Type:application/json" -d '{"input": [1.1, 2.2, 3.3]}' 127.0.0.1:1337/hello-world/predict
 `

Whose output is 6.6 (where len([1.1,2.2,3.3]) is NOT EQUAL to len([6.6]).

The xs length I was assuming to be 3 (since 1.1, 2.2, 3.3) but it is 2:
 xs[0] = [1.1, 2.2, 3.3] and also xs[1]=[1.1,2.2,3.3]  (hence we can do something like sum(x) as shown above).

And output should also be of len 2 always.

Therefore, the above explanation by @withsmilo  makes sense.

**Comment by RehanSD** [comment]
Hey @kheraAniruddh!
Just as a quick explanation, the reason Clipper does this is because it performs adaptive batching - so even though you’re just sending one input to the model, Clipper varies the batch size by copying that input and creating a batch to find the optimal batch size that still meets the SLO while maximizing throughput. Once it finds this optimal size, it sends batches of this size to the model container, which is why your output vector isn’t of length 1, and must be the same length as the input vector - because you must return a prediction for every input.
