### ISSUE TITLE
Failed when use pkgs_to_install argument!

### ISSUE THREAD

**Issue by zoux86** [ucbrise/clipper#560]
i run a simple examples with no pkgs_to_install argument, it successed!
but i run the same simple examples with pkgs_to_install , i got this error!
BuildError: The command '/bin/sh -c apt-get -y install build-essential && pip install  random' returned a non-zero code: 1

this is my code:
from clipper_admin import ClipperConnection, KubernetesContainerManager
clipper_conn = ClipperConnection(KubernetesContainerManager(useInternalIP=True))
clipper_conn.connect()     
clipper_conn.register_application(name="test-1", input_type="doubles", default_output="-1.0", slo_micros=100000) 
def feature_sum(xs):
    return [str(sum(x)) for x in xs]
from clipper_admin.deployers import python as python_deployer
python_deployer.deploy_python_closure(clipper_conn, name="model-1", version=1, input_type="doubles", func=feature_sum,pkgs_to_install=['random'])
clipper_conn.link_model_to_app(app_name="test-1", model_name="model_1")

when i don't have the pkgs_to_install arguments , it success!
but when i have the pkgs_to_install argument, the error appeared!
not only the "random" package, the other packages also get error!

can anyone give me a suggestion?

**Comment by YCait** [comment]
I met this problem too, how do you fix it?
