### ISSUE TITLE
ImportError with sklearn

### ISSUE THREAD

**Issue by thomas9t** [ucbrise/clipper#562]
I'm trying to deploy a simple model through sklearn. However, the container crashes with the following error message:

```
Starting Python Closure container
Connecting to Clipper with default port: 7000
Encountered an ImportError when running container. You can use the pkgs_to_install argument when calling clipper_admin.build_model() to supply any needed Python packages.
```

The error persists when `sklearn` is requested in `pkgs_to_install`. I suspect I'm just doing something wrong since deploying sklearn models is probably well trodden turf by now, but I haven't been able to figure out what's going on. Perhaps this comes from the fact that `sklearn.linear_model` needs to be imported directly? i.e. You can't do `import sklearn; model = sklearn.linear_model.LinearRegression()`. Below is an example to reproduce:

```
import numpy as np

from sklearn.linear_model import LinearRegression
from clipper_admin import ClipperConnection, DockerContainerManager
from clipper_admin.deployers import python as python_deployer

clipper_conn = ClipperConnection(DockerContainerManager())
clipper_conn.start_clipper()

N, K = 10000, 1000
X = np.random.rand(N, K)
y = X.dot(np.random.rand(K, 1)) + np.random.normal(size=(N,1))

model = sklearn.linear_model.LinearRegression()
model.fit(X, y)

def predict_fn(x):
    model.predict(x)
    return [str(x) for x in res]

clipper_conn.register_application(
    name="app1", input_type="doubles", 
    default_output="-1.0", slo_micros=slo_micros)
python_deployer.deploy_python_closure(
    clipper_conn, name="model1", version=1, 
    input_type="doubles", func=predict_fn, pkgs_to_install=['sklearn'])
clipper_conn.link_model_to_app(
    app_name="app1", model_name="model1")
```

And relevant system details:

```
docker --version -> Docker version 18.06.1-ce, build e68fc7a
python --version -> Python 2.7.15 :: Anaconda, Inc.
python -c "import clipper_admin; print clipper_admin.__version__" -> 0.3.0
python -c "import sklearn; print sklearn.__version__" -> 0.19.1

**Comment by zoux86** [comment]
maybe you should import scipy at the same time.
pkgs_to_install=['scipy','sklearn']
you can try it!

**Comment by thomas9t** [comment]
Thanks @zoux86 - that fixed the problem! I knew I was missing something simple 😄 - a little surprising though. I though pip usually installed dependencies along with the target package.
