### ISSUE TITLE
How to build a model with the model and clipper code in different py file?

### ISSUE THREAD

**Issue by zoux86** [ucbrise/clipper#565]
i have two python files, one is the predict function, one is the clipper code.

feature_sum.py
![image](https://user-images.githubusercontent.com/14087435/44963818-9ddc1400-af5f-11e8-9d11-8fde4f517fde.png)

buildModel.py
![image](https://user-images.githubusercontent.com/14087435/44963766-4c338980-af5f-11e8-8d3b-f807d4da717d.png)

when i run the bulidModel.py. i get this error.
![image](https://user-images.githubusercontent.com/14087435/44963990-b0a31880-af60-11e8-91d5-eba046438d2b.png)

can anyone give me some suggestions? thans!

**Comment by simon-mo** [comment]
this requires copying the file over. We don't have a hook in python package for this right now. The approach we recommend is to build your custom container:
http://clipper.ai/tutorials/custom_model_container/

**Comment by zoux86** [comment]
@simon-mo Thanks! i will have a try!
