### ISSUE TITLE
External redis crash fix

### ISSUE THREAD

**Issue by HarryAtMove** [ucbrise/clipper#571]
When specifying the `redis_ip` for the DockerContainerManager constructor, then connecting to Clipper an exception will be thrown similiar to the following.

```
    clipper_conn.start_clipper()
  File "/app/anaconda3/envs/ml-serve/lib/python3.6/site-packages/clipper_admin-develop-py3.6.egg/clipper_admin/clipper_admin.py", line 126, in start_clipper
    num_frontend_replicas)
  File "/app/anaconda3/envs/ml-serve/lib/python3.6/site-packages/clipper_admin-develop-py3.6.egg/clipper_admin/docker/docker_container_manager.py", line 246, in start_clipper
    self.connect()
  File "/app/anaconda3/envs/ml-serve/lib/python3.6/site-packages/clipper_admin-develop-py3.6.egg/clipper_admin/docker/docker_container_manager.py", line 265, in connect
    self.redis_port = all_labels[CLIPPER_DOCKER_PORT_LABELS['redis']]
KeyError: 'ai.clipper.redis.port'
```

The fix for this is to skip port look up and use the value of `self.redis_port` by replacing line 261 of **clipper/clipper_admin/clipper_admin/docker/docker_container_manager.py** with the following:
```
        if not self.external_redis:
            self.redis_port = all_labels[CLIPPER_DOCKER_PORT_LABELS['redis']]
```

**Comment by rkooo567** [comment]
@simon-mo Is it fixed in the current develop?

**Comment by DNCoelho** [comment]
@rkooo567 I had this issue today while working with a fresh install from develop. I fixed it by simply performing a key check before the assignment. This is what I got at line 312 of `DockerContainerManager`:

```py
if CLIPPER_DOCKER_PORT_LABELS['redis'] in all_labels:
    self.redis_port = all_labels[CLIPPER_DOCKER_PORT_LABELS['redis']]
```

By doing this the `redis_port` is not reassigned when an external value is passed, while still behaving normally in case it isn't.

**Comment by withsmilo** [comment]
@DNCoelho Good point. I think it's missed check. Would you please create a new PR?

**Comment by DNCoelho** [comment]
@withsmilo  Done :+1:
