### ISSUE TITLE
PyTorch CNN Model Serving - Image Querying Mechanism

### ISSUE THREAD

**Issue by arulbharathi** [ucbrise/clipper#572]
Hi 
May I have any documentation or small examples where CNN models (preferably PyTorch) are being served using Clipper. I tried using this example (https://github.com/ucbrise/clipper/blob/develop/examples/image_query/example.md), but I am not sure whether it is efficient for image processing algorithms to serve predictions

**Comment by RehanSD** [comment]
Hi @arulbharathi we recently published some tutorials on Clipper that we used in Strata NYC '18 as well as RISE Camp 18. They actually use not only a PyTorch Squeezenet model, but also a Darknnet Yolo model, so they should help out. Check out [this](https://github.com/ucbrise/clipper-tutorials/blob/master/1-Clipper-Basics.ipynb) iPython notebook for the tutorial!

**Comment by rkooo567** [comment]
Closed
