### ISSUE TITLE
On pip3 install, failed building wheel for cryptography

### ISSUE THREAD

**Issue by sentient-soellingeraj** [ucbrise/clipper#584]
On install command, I got an error.  I installed on my mac just fine, but had problems on the server

```pip3 install clipper_admin```

Seeing a lot of stack trace blocks that look like this:
```distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1```

and
```Failed cleaning build dir for cryptography```

```Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-b8b7xkq5/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-w1wp_jjr-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-b8b7xkq5/cryptography/```

Can someone help?

**Comment by sentient-soellingeraj** [comment]
Someone more familiar with the inner workings might confirm, but what resolved this issue for me was to use ```sudo /usr/bin/env python3 -m pip install clipper_admin``` instead of ```pip3 install clipper_admin```
There appears to be some issues with the pip3 command that cause this issue.

**Comment by withsmilo** [comment]
@sentient-soellingeraj : 
I recommend that you create own Anaconda environment in your server and install clipper_admin.
```
$ conda create --name test_py36 python=3.6
$ source activate test_py36
$ pip install clipper_admin
$ python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import clipper_admin
>>
```
