### ISSUE TITLE
Docker error on clipper_conn.start_clipper()

### ISSUE THREAD

**Issue by sentient-soellingeraj** [ucbrise/clipper#585]
I received the "Docker not running error" even when docker was running, looked as follows:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/clipper_admin/clipper_admin.py", line 130, in start_clipper
    raise e
  File "/usr/local/lib/python3.5/dist-packages/clipper_admin/clipper_admin.py", line 114, in start_clipper
    cache_size, num_frontend_replicas)
  File "/usr/local/lib/python3.5/dist-packages/clipper_admin/docker/docker_container_manager.py", line 116, in start_clipper
    raise ClipperException(msg)
clipper_admin.exceptions.ClipperException: Unable to Connect to Docker. Please Check if Docker is running.```

Can someone help?

**Comment by sentient-soellingeraj** [comment]
To resolve this, I had to sudo into the python console.
```sudo python3```

**Comment by withsmilo** [comment]
@sentient-soellingeraj : 
I think that you must permit to manage Docker as a non-root user.
https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by godkillok** [comment]
@sentient-soellingeraj  i have run python3  from root  but  still have that problem

**Comment by jaskirat1208** [comment]
I also faced the same problem. Then I started docker as non root as mentioned by @withsmilo. Then there came another issue where it tried to write to a file in /tmp/clipper/promethius.yml. For this purpose, I did chmod 777 over each of them. Then it worked without using sudo.

**Comment by rkooo567** [comment]
Closed.
