### ISSUE TITLE
get stuck when deploying a model 

### ISSUE THREAD

**Issue by YupaTapuY** [ucbrise/clipper#589]
hi, i tried deploying a model from your tutorial that mentioned in getting started using DockerContainerManager but it get stuck in this process

18-10-15:00:46:16 INFO     [docker_container_manager.py:353] [default-cluster] Found 0 replicas for model:1. Adding 1

im using centOS7 and docker version 18.06.0-ce, after that i tried to deploy my keras tensorflow model with tensorflow deployer and get stuck in the same line.

**Comment by simon-mo** [comment]
While it's getting stuck, can you try run `docker ps -a | head` to find out the model container that crashed. And run `docker logs {CONTAINER_NAME}` to see the error logs? 

This is something we will improve on in the next release.

**Comment by YupaTapuY** [comment]
hi, thanks for the answer, now i know why i got stack in tutorial because my pickle version, but i still got stuck when i deploy my keras model with tensorflow deployer, i want to know whether tensorflow deployer is incompatible with keras model and do clipper have a default keras deployer for that ? anyway thank you for your help

**Comment by simon-mo** [comment]
No we do not have a default Keras deployer yet. We will add a Keras deployer in few weeks!

**Comment by YupaTapuY** [comment]
ah alright, thanks for answering
so for now it still incompatible with keras model and i must make a custom container deployer for that ?

**Comment by simon-mo** [comment]
Yes. Someone actually implemented all these already here: https://gitlab.com/dyoung23/Clipper

**Comment by YupaTapuY** [comment]
thanks, i'll try to implemented  it based on that

**Comment by YupaTapuY** [comment]
thanks, it worked

**Comment by kumarivin** [comment]
I am getting similar issue how to resolve this ?

This is what i am seeing in the docker container default-cluster-sum-model:1 for the sample demo in the github

docker logs ee8aee4e8aa5
Starting Python Closure container
Connecting to Clipper with default port: 7000
Traceback (most recent call last):
  File "/container/python_closure_container.py", line 56, in <module>
    rpc_service.get_input_type())
  File "/container/python_closure_container.py", line 28, in __init__
    self.predict_func = load_predict_func(predict_path)
  File "/container/python_closure_container.py", line 17, in load_predict_func
    return cloudpickle.load(serialized_func_file)
  File "/usr/local/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 1060, in _make_skel_func
    base_globals['__builtins__'] = __builtins__
TypeError: 'str' object does not support item assignment
Encountered error not related to missing packages. Please refer to the container log to diagnose.

**Comment by kumarivin** [comment]
found solution in ticket https://github.com/ucbrise/clipper/issues/568

**Comment by karthikra** [comment]
@simon-mo 
I am getting similar issue how to resolve this ?
docker logs pytorch-model_1-36217
Starting PyTorchContainer container
Connecting to Clipper with default port: 7000
Traceback (most recent call last):
  File "/container/pytorch_container.py", line 82, in <module>
    rpc_service.get_input_type())
  File "/container/pytorch_container.py", line 54, in __init__
    self.model = load_pytorch_model(torch_model_path, torch_weights_path)
  File "/container/pytorch_container.py", line 36, in load_pytorch_model
    model = cloudpickle.load(serialized_model_file)
AttributeError: Can't get attribute '_rebuild_parameter' on <module 'torch._utils' from '/usr/local/lib/python3.6/site-packages/torch/_utils.py'>

**Comment by simon-mo** [comment]
@karthikra This is a pytorch issue. Can you run `python -c "import torch; print(torch.__version__)"` to confirm what version of pytorch do you have?

**Comment by prasann16** [comment]
@simon-mo I am getting a similar error:
Traceback (most recent call last): File "/container/pytorch_container.py", line 82, in <module> rpc_service.get_input_type()) File "/container/pytorch_container.py", line 54, in _init_ self.model = load_pytorch_model(torch_model_path, torch_weights_path) File "/container/pytorch_container.py", line 36, in load_pytorch_model model = cloudpickle.load(serialized_model_file) AttributeError: Can't get attribute '_load_from_bytes' on <module 'torch.storage' from '/usr/local/lib/python3.6/site-packages/torch/storage.py'>

Does clipper only work with pytorch 0.4.0? I have pytorch 0.4.1 installed. Why does clipper not work with higher versions?
