### ISSUE TITLE
Broken links in http://clipper.ai/tutorials/basic_concepts/

### ISSUE THREAD

**Issue by gcsfred2** [ucbrise/clipper#592]
Text in page:

"One to deploy arbitrary Python functions (within some constraints): [Docs]
One to deploy PySpark models along with pre- and post-processing logic: [Docs]"

Broken links:
http://docs.clipper.ai/en/release-0.2/#pure-python-functions

http://docs.clipper.ai/en/release-0.2/#pyspark-models

**Comment by rkooo567** [comment]
Seems like these links work. 

http://docs.clipper.ai/en/v0.3.0/model_deployers.html#pure-python-functions. 
http://docs.clipper.ai/en/v0.3.0/model_deployers.html#pyspark-models
