### ISSUE TITLE
Problem deploying my model 

### ISSUE THREAD

**Issue by kumarivin** [ucbrise/clipper#593]
I am trying to deploy a fastai model https://github.com/fastai/fastai/blob/master/courses/dl2/imdb.ipynb  into clipper by wrapping up the model in the below function

```
def convert_csv_to_token(csvpath):
    col_names = ['labels','text']
    predict_data=pd.read_csv(csvpath , encoding='iso-8859-1')
    predict_data.to_csv(CLAS_PATH/'predict.csv', header=False, index=False)
    df_predict = pd.read_csv(CLAS_PATH/'predict.csv', header=None, chunksize=chunksize)
    tok_predict=get_all(df_predict,1)
    return tok_predict

def return_Sentiment(csvpath):
    tok_val = convert_csv_to_token(csvpath) #CLAS_PATH/"reuters/TestData.csv"
    results = []
    while i < len(tok_val[0]):
        sen = ' '.join(tok_val[0][i])
        i+=1
        m.eval()
        #reset hidden state
        m.reset()
        idxs = np.array([[stoi[p] for p in sen.strip().split(" ")]])
        idxs = np.transpose(idxs)
        #get predictions from model
        p = m(VV(idxs))
        #     print(sen + ': ' + str(to_np(torch.topk(p[0],1)[1])[0]))
        # append classification to list of results for validation
        results.append(torch.topk(p[0],1)[1].data.tolist()[0])
    sLength = len(predict_data['labels'])
    predict_data['result'] = results
    predict_data.to_csv("sentimentresults3.csv") 
```
 

below is the deployer packages install
`from clipper_admin.deployers import python as python_deployer
python_deployer.deploy_python_closure(clipper_conn, name="sentiment-lm-model", version=1, input_type="string", func=return_Sentiment, pkgs_to_install=["pandas","fastai"])`

and its getting stuck with the below message 

> 18-10-29:10:41:36 INFO     [deployer_utils.py:41] Saving function to /var/folders/bq/rtjwrm097xs8j_373wbyx28r0000gn/T/tmp5c1st4abclipper
18-10-29:10:41:37 INFO     [deployer_utils.py:51] Serialized and supplied predict function
18-10-29:10:41:37 INFO     [python.py:192] Python closure saved
18-10-29:10:41:37 INFO     [python.py:206] Using Python 3.6 base image
18-10-29:10:41:37 INFO     [clipper_admin.py:467] [default-cluster] Building model Docker image with model data from /var/folders/bq/rtjwrm097xs8j_373wbyx28r0000gn/T/tmp5c1st4abclipper
18-10-29:10:41:42 INFO     [clipper_admin.py:472] [default-cluster] Step 1/3 : FROM clipper/python36-closure-container:develop
18-10-29:10:41:42 INFO     [clipper_admin.py:472] [default-cluster]  ---> 0fac6e6e8242
18-10-29:10:41:42 INFO     [clipper_admin.py:472] [default-cluster] Step 2/3 : RUN apt-get -y install build-essential && pip install pandas fastai
18-10-29:10:41:42 INFO     [clipper_admin.py:472] [default-cluster]  ---> Using cache
18-10-29:10:41:42 INFO     [clipper_admin.py:472] [default-cluster]  ---> 9d507ceb93a6
18-10-29:10:41:42 INFO     [clipper_admin.py:472] [default-cluster] Step 3/3 : COPY /var/folders/bq/rtjwrm097xs8j_373wbyx28r0000gn/T/tmp5c1st4abclipper /model/
18-10-29:10:41:42 INFO     [clipper_admin.py:472] [default-cluster]  ---> b25158338050
18-10-29:10:41:42 INFO     [clipper_admin.py:472] [default-cluster] Successfully built b25158338050
18-10-29:10:41:42 INFO     [clipper_admin.py:472] [default-cluster] Successfully tagged default-cluster-sentiment-lm-model:1
18-10-29:10:41:42 INFO     [clipper_admin.py:474] [default-cluster] Pushing model Docker image to default-cluster-sentiment-lm-model:1
18-10-29:10:41:42 INFO     [docker_container_manager.py:353] [default-cluster] Found 0 replicas for sentiment-lm-model:1. Adding 1

docker logs shows below error

> Starting Python Closure container
Connecting to Clipper with default port: 7000
Encountered an ImportError when running container. You can use the pkgs_to_install argument when calling clipper_admin.build_model() to supply any needed Python packages.

wondering if i a doing something wrongly here.

**Comment by withsmilo** [comment]
@kumarivin : 
Your predict function(`return_Sentiment`) is wrong. Do you want to read a csv file as input, predict and save them?

**Comment by kumarivin** [comment]
@withsmilo  yes I would like to predict and save the sentiment of reviews. Also if you observe, my model is not loaded in the return_sentiment but outside the model, so I am not sure if that is exactly how i can do it or not.

**Comment by hsubbaraj** [comment]
@kumarivin 
The input to the predict function for the python_deployer should be a list of inputs and return a list of outputs. Please refer to http://docs.clipper.ai/en/v0.3.0/model_deployers.html#pure-python-functions for an example. The reason your current implementation won't work right now is because the .csv file isn't copied over to the model container. 

There are several solutions to this:
1. You can write your own custom Docker base image where you load in the .csv file. See https://github.com/ucbrise/clipper-tutorials/blob/master/1-Clipper-Basics.ipynb for an example
2. Store the file in an S3 bucket and use http to fetch the file from within your predict function.

In the future, we might add support for copying files/folders directly to the model container

**Comment by kumarivin** [comment]
@hsubbaraj thank you , will look into it !!

**Comment by voodoohop** [comment]
I am getting the same error and was wondering if there is some way to get more detailed logs than just this error... I am having difficulty debugging the cause of the error:

> Encountered an ImportError when running container. You can use the pkgs_to_install argument when calling clipper_admin.build_model() to supply any needed Python packages.
