### ISSUE TITLE
Custom model container with custom Python packages

### ISSUE THREAD

**Issue by colincrook** [ucbrise/clipper#612]
I can't use any of the python model deployer because my model relies on some custom Python packages.
Those custom Python packages can be install via pip but they are not in base URL of Python Package Index (https://pypi.org/simple) and so I need to use the argument -i to use a custom URL.

So, I tried to create my custom image, first by copying all the packages using the COPY command from this example http://clipper.ai/tutorials/custom_model_container/ 
I was able to create the image, but now I have some difficulties to then use the deploy_python_closure. I added my base_image as an argument but I don't know what the parameter myfunc should then be. 

Is there any other way to go? 

Thanks

**Comment by RehanSD** [comment]
Hi @colincrook!
Just add a `-i` in the `pkgs_to_install` argument. Ex:
```python
pkgs_to_install = [‘-i’, ‘pkg1’, …]
OR
pkgs_to_install = [‘-i pkg1’]
```
In both cases, the `pip install` command will be formatted as
```
pip install -i pkg1 pkg2 …
```
Hope that helps.

**Comment by colincrook** [comment]
Hi @RehanSD , thanks for the tips. I just tried, my python clipper is stuck at the step:
[docker_container_manager.py:257] Found 0 replicas for test-4:1. Adding 1

and when I check the docker logs for this container id I can see an error:
Encountered an ImportError when running container. You can use the pkgs_to_install argument when calling clipper_admin.build_model() to supply any needed Python packages.

There must be a missing package, I'll test everything on my side. 

Thanks!
