### ISSUE TITLE
Problem in deploying tutorial

### ISSUE THREAD

**Issue by jaskirat1208** [ucbrise/clipper#613]
Ref: clipper.ai quickstart

Command: `python_deployer.deploy_python_closure(clipper_conn, name="sum-model", version=1, input_type="doubles", func=feature_sum)`
Output
```


 

19-01-16:16:09:46 INFO     [deployer_utils.py:44] Saving function to /tmp/clipper/tmpvllkwja5
19-01-16:16:09:46 INFO     [deployer_utils.py:54] Serialized and supplied predict function
19-01-16:16:09:46 INFO     [python.py:192] Python closure saved
19-01-16:16:09:46 INFO     [python.py:202] Using Python 3.5 base image
19-01-16:16:09:46 INFO     [clipper_admin.py:452] Building model Docker image with model data from /tmp/clipper/tmpvllkwja5
19-01-16:16:09:47 INFO     [clipper_admin.py:456] {'stream': 'Step 1/2 : FROM clipper/python35-closure-container:0.3.0'}
19-01-16:16:09:47 INFO     [clipper_admin.py:456] {'stream': '\n'}
19-01-16:16:09:47 INFO     [clipper_admin.py:456] {'stream': ' ---> 1fc910c1ed28\n'}
19-01-16:16:09:47 INFO     [clipper_admin.py:456] {'stream': 'Step 2/2 : COPY /tmp/clipper/tmpvllkwja5 /model/'}
19-01-16:16:09:47 INFO     [clipper_admin.py:456] {'stream': '\n'}
19-01-16:16:09:47 INFO     [clipper_admin.py:456] {'stream': ' ---> bfd1743552f4\n'}
19-01-16:16:09:47 INFO     [clipper_admin.py:456] {'aux': {'ID': 'sha256:bfd1743552f4bffbd707f217d1f1cdb0b3b22b3b8387bb226a06dc85c115a759'}}
19-01-16:16:09:47 INFO     [clipper_admin.py:456] {'stream': 'Successfully built bfd1743552f4\n'}
19-01-16:16:09:47 INFO     [clipper_admin.py:456] {'stream': 'Successfully tagged sum-model:1\n'}
19-01-16:16:09:47 INFO     [clipper_admin.py:458] Pushing model Docker image to sum-model:1
19-01-16:16:09:53 INFO     [docker_container_manager.py:257] Found 0 replicas for sum-model:1. Adding 1
       


```

This goes on for more than 20 minutes. `Successfully added` message does not come
Thanks

**Comment by simon-mo** [comment]
@RehanSD can you take a look? I'm a bit swamped right now.

**Comment by withsmilo** [comment]
@jaskirat1208 : 
How about increase your Docker's swap size?

**Comment by jaskirat1208** [comment]
@withsmilo I had created a virtual environment using  

`conda create -n clipperenv python=3.6.1 anaconda
`
And in this virtual environment, I tried to run those clipper commands. Could you please tell me how to increase my docker swap size ?

**Comment by withsmilo** [comment]
<img width="497" alt="2019-01-29 3 40 18" src="https://user-images.githubusercontent.com/3915543/51889222-36c26e80-23dc-11e9-84aa-875501e273df.png">
@jaskirat1208 : If you use Docker version on Mac, please tune the 'Swap' bar in upper image.

**Comment by jaskirat1208** [comment]
I am using ubuntu, any comments about this ?

**Comment by withsmilo** [comment]
So sorry. I am not using ubuntu now.

**Comment by simon-mo** [comment]
Did you do `pip install -U cloudpickle==0.5.3`?

**Comment by jaskirat1208** [comment]
@withsmilo  I did this on a mac as well, with a 4 GB swap memory. But no effect.

**Comment by jaskirat1208** [comment]
@simon-mo  I hadn't done that before. It worked. Thank you :+1:

**Comment by jaskirat1208** [comment]
@simon-mo @withsmilo  Could you please update your documentation page about installing cloudpickle as well ? This would be helpful since it was not working without it.
