### ISSUE TITLE
how to load pretrain tensorflow pb file 

### ISSUE THREAD

**Issue by wcwang07** [ucbrise/clipper#627]
from clipper_admin import ClipperConnection,DockerContainerManager

clipper_conn = ClipperConnection(DockerContainerManager())

try:
	clipper_conn.start_clipper()
except Exception, e:
	print(e)
	clipper_conn.stop_all()

clipper_conn.register_application(name="hello-tf", input_type="int", default_output="this is default output", slo_micros=100000)

def predict(sess, inputs):
	preds = sess.run('predict_class:0', feed_dict={'image_tensor:0': inputs})
	return [str(p) for p in preds]

from clipper_admin.deployers import python as python_deployer
python_deployer.deploy_tensorflow_model(clipper_conn=clipper_conn, name="tf-mobilnet", version=1, input_type="int", func=predict, tf_sess_or_saved_model_path='/home/ubuntu/tf-mobilenet')

When query on this endpoint, i get:
{"query_id":7,"output":"this is default output","default":true,"default_explanation":"No connected models found for query"}

maybe i have missed some steps, but I am not sure.
(https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)
![input_mobilenet](https://user-images.githubusercontent.com/830341/52387642-e84a4b00-2a3f-11e9-91e6-23623d33e3eb.JPG)

**Comment by withsmilo** [comment]
Hi, @wcwang07 

1. When executing 'python_deployer.deploy_tensorflow_model(...)', did you see error messages?

2. Could you share your model container('tf-mobilnet')'s log with me? (The example below is for reference only.)
```
$ docker ps -a
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                    PORTS                                            NAMES
79b2cbab56e3        sum-model:1                           "/container/containe…"   15 seconds ago      Up 14 seconds (healthy)                                                    sum-model_1-96511
1d9a28acda3b        prom/prometheus:v2.1.0                "/bin/prometheus --c…"   20 seconds ago      Up 20 seconds             0.0.0.0:9090->9090/tcp                           metric_frontend-19254
9a844dbf0a90        clipper/frontend-exporter:develop     "python /usr/src/app…"   21 seconds ago      Up 20 seconds                                                              query_frontend_exporter-57189
82a7708a9ca9        clipper/query_frontend:develop        "/clipper/query_fron…"   22 seconds ago      Up 21 seconds             0.0.0.0:1337->1337/tcp, 0.0.0.0:7000->7000/tcp   query_frontend-57189
86ddd7c556f2        clipper/management_frontend:develop   "/clipper/mgmt_front…"   22 seconds ago      Up 22 seconds             0.0.0.0:1338->1338/tcp                           mgmt_frontend-41814
54daa7bbe88b        redis:alpine                          "docker-entrypoint.s…"   23 seconds ago      Up 22 seconds             0.0.0.0:6379->6379/tcp                           redis-90870
```
```
$ docker logs sum-model_1-96511
19-02-07:13:39:54 INFO     [rpc.py:681] model_replica_id is 1
19-02-07:13:39:54 INFO     [rpc.py:694] Connecting to Clipper with default port: 7000
Starting Python Closure container
...
```

**Comment by wcwang07** [comment]
Hi  @withsmilo 
1. When executing python_deployer.deploy_tensorflow_model, did not see any error message.
2. the container logs show that:

2019-02-07 18:02:58.299059: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
19-02-07:18:03:02 INFO     [tf_logging.py:116] Saver not created because there are no variables in the graph to restore
19-02-07:18:03:02 INFO     [tf_logging.py:116] The specified SavedModel has no variables; no checkpoints were restored.
Starting TensorFlow container
Connecting to Clipper with default port: 7000
19-02-07:18:03:02 INFO     [server.py:80] Metric Server Started!
19-02-07:18:03:02 INFO     [server.py:85] Redis Connected! Waiting for messages...
Serving predictions for ints input type.
Sent heartbeat!
Received heartbeat!
Sent container metadata!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Got start of message 0
Traceback (most recent call last):
  File "/container/tf_container.py", line 84, in <module>
    rpc_service.start(model)
  File "/container/rpc.py", line 726, in start
    self.server.run(collect_metrics=self.collect_metrics)
  File "/container/rpc.py", line 353, in run
    prediction_request)
  File "/container/rpc.py", line 160, in handle_prediction_request
    outputs = predict_fn(prediction_request.inputs)
  File "/container/tf_container.py", line 54, in predict_ints
    preds = self.predict_func(self.sess, inputs)
  File "<ipython-input-6-b0d49dbbda85>", line 2, in predict
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1083, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: The name 'image_tensor' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".
Encountered error not related to missing packages. Please refer to the container log to diagnose.

I am not sure if the input/output variable to the session is causing the issue? I am trying to play around

preds = sess.run('y:0', feed_dict={'image_tensor:0': inputs})

**Comment by wcwang07** [comment]
Hi  @withsmilo 
1. When executing python_deployer.deploy_tensorflow_model, did not see any error message.
2. the container logs show that:

2019-02-07 18:02:58.299059: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
19-02-07:18:03:02 INFO     [tf_logging.py:116] Saver not created because there are no variables in the graph to restore
19-02-07:18:03:02 INFO     [tf_logging.py:116] The specified SavedModel has no variables; no checkpoints were restored.
Starting TensorFlow container
Connecting to Clipper with default port: 7000
19-02-07:18:03:02 INFO     [server.py:80] Metric Server Started!
19-02-07:18:03:02 INFO     [server.py:85] Redis Connected! Waiting for messages...
Serving predictions for ints input type.
Sent heartbeat!
Received heartbeat!
Sent container metadata!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Got start of message 0
Traceback (most recent call last):
  File "/container/tf_container.py", line 84, in <module>
    rpc_service.start(model)
  File "/container/rpc.py", line 726, in start
    self.server.run(collect_metrics=self.collect_metrics)
  File "/container/rpc.py", line 353, in run
    prediction_request)
  File "/container/rpc.py", line 160, in handle_prediction_request
    outputs = predict_fn(prediction_request.inputs)
  File "/container/tf_container.py", line 54, in predict_ints
    preds = self.predict_func(self.sess, inputs)
  File "<ipython-input-6-b0d49dbbda85>", line 2, in predict
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1083, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: The name 'image_tensor' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".
Encountered error not related to missing packages. Please refer to the container log to diagnose.

**Comment by wcwang07** [comment]
update:  only need to feed correct data now

Traceback (most recent call last):
  File "/container/tf_container.py", line 84, in <module>
    rpc_service.start(model)
  File "/container/rpc.py", line 726, in start
    self.server.run(collect_metrics=self.collect_metrics)
  File "/container/rpc.py", line 353, in run
    prediction_request)
  File "/container/rpc.py", line 160, in handle_prediction_request
    outputs = predict_fn(prediction_request.inputs)
  File "/container/tf_container.py", line 54, in predict_ints
    preds = self.predict_func(self.sess, inputs)
  File "<ipython-input-5-b8af1d04d507>", line 2, in predict
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (2, 3) for Tensor u'image_tensor:0', which has shape '(?, ?, ?, 3)'
Got start of message 0
Encountered error not related to missing packages. Please refer to the container log to diagnose.

**Comment by wcwang07** [comment]
ubuntu@ip-172-31-46-38:~$ curl -X POST --header "Content-Type:application/json" -d '{"input": [[[[[0,0,0],[0,0,0],[0,0,0]]]]]}' 127.0.0.1:1337/hello-tf-v2/predict
{"error":"Json error","cause":"Error parsing JSON: Array input of type Array is not of type int. Expected JSON schema: \n  {\n   \"input\" := [double] | [int] | [string] | [byte] | [float],\n  }\n"}

I think front-end is blocking different type of inputs

clipper/src/libclipper/src/json_util.cpp it is blocking any type other than array_string, array_double, array_float, array_Int, i have 4-d array of Int input

**Comment by simon-mo** [comment]
Yes we are only accepting array of primitive types. You might need to do
reshaping of input array inside the prediction function.

So the prediction function’s input will be of shape (batch size, input
flattened size)
