### ISSUE TITLE
setup up aws/clipper benchmarking

### ISSUE THREAD

**Issue by wcwang07** [ucbrise/clipper#633]
have you tried to benchmark sagemaker against clipper? if so, could you share steps to reproduce it?  Could you show how to enable auto scaling on clipper endpoint? Would you share any insight on how clipper integrate with aws kubernetes? Would it be possible to perform A/B testing on clipper?  

on the https://github.com/ucbrise/clipper/tree/develop/bench

there is no comparison done for example against sagemaker, would it be possible to elaborate the tests?

**Comment by simon-mo** [comment]
@EyalSel can you share your benchmarking tool is possible? 

@wcwang07  Another way to proceed is to re-produce your experiment against sagemaker in Clipper, can you layout what is needed to re-produce your experiment? So far I know that you need
- Setup AWS Kuberenetes (Clipper should work out-of-the-box for this one)
- Setup Autoscaling (Clipper doesn't have native support yet, but you can change the number of replica via single `.set_num_replicas` api call. 
- Setup A/B testing (Again, no native support yet)

**Comment by wcwang07** [comment]
@simon-mo For the current tasks on my plate, having no access to company system:
1.   I need to investigate one use case using recommendation inputs base on age, and location, we would need to understand cache hit ratio for different caching strategy, later I can look into other use case like NLP, CV.
2. I need to understand how to scale in kubernetes using clipper to be cost effective when to scale in/out.  In addition, to understand if batching can be done during scaling.  This will help to understand costs for different use cases.

**Comment by wcwang07** [comment]
@simon-mo 
I have been trying to setup clipper through EKS

I have been having this issue for a while, have you had this issue before?

![image](https://user-images.githubusercontent.com/830341/53056631-da91be00-3460-11e9-81e6-e110c8b09307.png)

why is is trying to
