### ISSUE TITLE
google k8s getting another error 

### ISSUE THREAD

**Issue by avinregmi** [ucbrise/clipper#634]
I'm able to deploy a model and it's running. When i'm sending a request to serve container will crash and restart. I've attached log output. 
![screen shot 2019-02-13 at 2 29 38 pm](https://user-images.githubusercontent.com/32203792/52738211-2265a080-2f9c-11e9-8644-b8e7e8b99ec2.png)

**Comment by dsandii** [comment]
I ran into fatal 'unknown opcode' errors myself when trying to run predictions on models exported from environments using Python 3.6 (whereas my model containers were using Python 3.5). 

I had to modify my Clipper model Dockerfile to use Python 3.6 instead. I'm not entirely sure if this is what you're experiencing, but hopefully this helps.

**Comment by avinregmi** [comment]
Yes, after updating to python3.6 it works!!!! Thanks

**Comment by wcwang07** [comment]
@avinregmi Hi I was following your thread on kubernetes deployment, the issue I am facing right now is that "Clipper still initializing" how do you get around it?  I am deploying on aws but the issue I have is get_admin will only get default cluster name but it did not get the proper pod name.
