### ISSUE TITLE
[RPC] lost contact with a container

### ISSUE THREAD

**Issue by adslwang4601** [ucbrise/clipper#636]
[14:28:29.034][info]         [RPC] lost contact with a container
[14:28:29.034][info]  [CONTAINERS] Removing container - model: lgm-high-1, version: 1, replica ID: 0
[14:28:29.034][info]  [CONTAINERS] All containers of model: lgm-high-1, version: 1 are removed. [14:28:29.034][info]  [CONTAINERS] 
Active containers:
	Model: lgm-low-2:1
		rep_id: 0, container_id: 4
	Model: lgm-mean-1:1
		rep_id: 0, container_id: 0
	Model: lgm-high-2:1
		rep_id: 0, container_id: 5
	Model: lgm-low-1:1
		rep_id: 1, container_id: 6
	Model: lgm-mean-2:1
		rep_id: 0, container_id: 3

terminate called after throwing an instance of 'std::runtime_error'
  what():  Documenting receive time for an unregistered container
the query frontend often crashes, How can I avoid it?

**Comment by withsmilo** [comment]
Hi, @adslwang4601 : 
1. Could you share your scenario with us if you can?
2. What version of Clipper are you using?

**Comment by withsmilo** [comment]
@adslwang4601
I met the same issue. I suspect that in rare case, the 'unique' connection id generated automatically by new ZMQ connection between model replica and query_frontend replica, was the same with previous ids, so query_frontend's RPCService couldn't register the model container with it, and then this error was occurred finally.

I will try to fix this error as soon as possible.

**Comment by withsmilo** [comment]
@adslwang4601 
Fixed. This commit will be contained within next release.
