### ISSUE TITLE
imagepullbackoff kubernetes

### ISSUE THREAD

**Issue by wcwang07** [ucbrise/clipper#638]
ran into following issue on kubernetes deployment, is there is something I missed here?

![image](https://user-images.githubusercontent.com/830341/53123406-d5d71380-350d-11e9-8000-ed0375489b2f.png)

**Comment by harmw** [comment]
Let me share some snippets of what we're doing:
```
else:
            # This will also register the model with Clipper
            logging.info("Deploying %s instances of %s:%s to EKS" % (
                instances, name, version))
            image = "%s/%s:%s" % (self.registry, name, version)
            input_type = self.md['blaze']['service']['ml']['model']['input_type']
            c.deploy_model(
                    name=name,
                    version=version,
                    input_type=input_type,
                    image=image,
                    num_replicas=instances,
                    batch_size=self.model_batch_size)
```

The image name would carry the name of your registry:
```
def image_name(self):
        md = self.get_metadata_from_file()
        name = md['name']
        version = self.generate_tag()
        return "%s/%s:%s" % (CONTAINER_REPO, name, version)
```

Looking at your screenshot, it seems as if you're missing the registry part. For example, here is the output from one of our models:

`Image:          docker.io/wehkamp/blaze-image-recognition-model:28-447e892`

I know of some changes in the naming of things between using `release-0.3` and `develop`, so perhaps that's a lead.

Also, should it concern a private registry, make sure to configure EKS accordingly:

```
kubectl create secret docker-registry my-dockerhub\
  --docker-server=docker.io \
  --docker-username=${SOMETHING} \
  --docker-password=${SOMETHING_ELSE} \
  --docker-email=${SOMETHING_SOMETHING}

kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "my-dockerhub"}]}'
```
