### ISSUE TITLE
can i change endpoint name 

### ISSUE THREAD

**Issue by Archelunch** [ucbrise/clipper#639]
Can I set another url for api like http://%s/simple-example/somethin instead http://%s/simple-example/predict?

**Comment by withsmilo** [comment]
Hi, @Archelunch.
There is no easy way yet. The clipper source must be modified manually.
https://github.com/ucbrise/clipper/blob/develop/src/frontends/src/query_frontend.hpp#L405

**Comment by Archelunch** [comment]
Ok, maybe I''try it
