### ISSUE TITLE
Keep getting 'Clipper still initializing' on start

### ISSUE THREAD

**Issue by raghavio** [ucbrise/clipper#642]
Hey guys, thanks for such a great tool!

I'm running into an issue when I specify my locally hosted Redis' ip.
```
clipper_conn = ClipperConnection(DockerContainerManager(redis_ip='0.0.0.0', redis_port='6379'))
```
It keeps printing `[clipper_admin.py:124] Clipper still initializing.`

**It all works fine when I don't specify my Redis instance and let Clipper create its own.**

Python: 3.6
Docker: 18.03.0-ce
Redis: 3.2.0

**Comment by simon-mo** [comment]
Are you using a mac or linux machine? This might be due to that Clipper's container unable to reach redis due to docker's networking issue. You might need to pass {"network":"host"} as `extra_container_kwargs` for `DockerContainerManager` to enable networking between containers and host

**Comment by raghavio** [comment]
It's a mac. I'll have to use `host.docker.internal` instead of `localhost`. Not sure how I missed this.
Thanks!
