### ISSUE TITLE
Is it possible to serve recommenders

### ISSUE THREAD

**Issue by tosolveit** [ucbrise/clipper#646]
Hi, as I see we can use models to make predictions, In my case with daily intervals I write recommendations to a file, Is there a way to serve them like sending a user id and get the recommendations?

**Comment by rkooo567** [comment]
Hi @tosolveit. Yeah for sure. Clipper supports deployment of Python function. You can read a file from the function and serve based on userid. You can find the example of python function deployment from here https://github.com/ucbrise/clipper/tree/develop/examples/basic_query.

**Comment by tosolveit** [comment]
You made my day, I am happy like a child, thanks a lot 😀
