### ISSUE TITLE
`DockerContainerManager` uses anti pattern.

### ISSUE THREAD

**Issue by rkooo567** [ucbrise/clipper#650]
<img width="541" alt="Screen Shot 2019-03-21 at 12 56 59 AM" src="https://user-images.githubusercontent.com/18510752/54739168-62f4a300-4b74-11e9-9d36-f84ddc462eeb.png">

https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html 

`DockerContainerManager` uses mutable default argument for `extra_container_kwargs`. It is commonly considered as Python anti pattern and can cause some errors if DockerContainerManager is not a singleton class. I think we should change to 
`extra_container_kwargs=None` and add 
```
if extra_container_kwargs is None:
    self.extra_container_kwargs = {}
else:
   self.extra_container_kwargs = extra_container_kwargs.copy()
```

**Comment by withsmilo** [comment]
I met already this pattern many times on the Clipper sources. I will try to fix them tonight.

**Comment by withsmilo** [comment]
merged! :)
