### ISSUE TITLE
README needs information about redis

### ISSUE THREAD

**Issue by vtolani95** [ucbrise/clipper#67]
When installing clipper and attempting to run ipython tutorial I get the following:

![image](https://cloud.githubusercontent.com/assets/6744971/23051124/63abad5e-f47b-11e6-89c4-9ab02d932461.png)

![image](https://cloud.githubusercontent.com/assets/6744971/23051126/6e3d3bc0-f47b-11e6-8ecb-c0e764315da6.png)

Possibly need documentation about installing redis before running clipper?

**Comment by dcrankshaw** [comment]
Fixed by #71
