### ISSUE TITLE
Use EC2 Spot Instance for GPU Testing

### ISSUE THREAD

**Issue by simon-mo** [ucbrise/clipper#670]
Now we have #669 in place, we need a way to test it. We can use ec2 spot instance to test it.

To do:
- [ ] Prepare an AMI that have GPU driver, nvidia-docker, and minikube with GPU support. 
    - Deliverable: `prepare_ami.sh` that should be run at a clean instance and result in the exactly the same ami
    - Deliverable: `ami-{id}` and make it public. 
- [ ] Inject aws crendential to jenkins, test that we are able to start & stop spot instance, pipe output. 
- [ ] Connect GPU tests in `./bin/shipyard.sh`

**Comment by RehanSD** [comment]
Replacing with #677 and closing.
