### ISSUE TITLE
JVM (Java/Scala) Spark deployment

### ISSUE THREAD

**Issue by jacekwachowiak** [ucbrise/clipper#671]
Hi, in the last days I deployed some Python-based models (such as PySpark), but for the project I am working on it would be perfect if there was a way to involve the JVM version of Spark. 
I went through the documentation, the paper and the github files, and I found some Scala/Spark dockerfiles, container code and so on, but no instruction or documentation. Is there any reference/instruction that would help me to deploy a JVM Spark model?
If by any chance I missed something obvious, sorry, but please share it anyway!

**Comment by rkooo567** [comment]
Hi, @jacekwachowiak. Everyone misses obvious things easily, so don't hesitate to ask questions! I believe Clipper had a JVM version of container server, but it is not maintained anymore. You can check it out from https://github.com/ucbrise/clipper/blob/227c8e46e5a801e9f94e7e42a5bf0b693a5f9919/bin/shipyard/clipper_test.cfg.py#L9. 

There's still possibility that it is usable, but I am not sure. @simon-mo can you elaborate this part?

**Comment by jacekwachowiak** [comment]
Yes, that's what I was afraid of, since I found only files with last update around a year ago and the website and all readmes are Python-focused.
> 
> [clipper/bin/shipyard/clipper_test.cfg.py](https://github.com/ucbrise/clipper/blob/227c8e46e5a801e9f94e7e42a5bf0b693a5f9919/bin/shipyard/clipper_test.cfg.py#L9)
> 
> Line 9 in [227c8e4](/ucbrise/clipper/commit/227c8e46e5a801e9f94e7e42a5bf0b693a5f9919)
> 
>  JVM and R containers are not maintained. 

I am not sure if this would be a dealbreaker (hopefully not!). Anyway, was there any instruction on how to deploy JVM in the previous version of Clipper docs? Or any additional materials? I would still like to take a look, even though it seems that making it work again may require a big overhaul.

**Comment by simon-mo** [comment]
You are correct that they are no longer maintained. JVM container does work but might require you to figure out how to package your model according to https://github.com/ucbrise/clipper/tree/develop/containers/jvm
