### ISSUE TITLE
Return Error Response

### ISSUE THREAD

**Issue by rp4fx12** [ucbrise/clipper#672]
Hi, (not sure if this the right place to ask this) but is there a way to return an error response code if someone passes in bad data to the api? Something like a 4xx status code. Is there also a way to run 5xx's if something breaks?

**Comment by RehanSD** [comment]
Hi! I'm not sure if this is what you're looking for, but when you register an application you can provide a `default_output` for when the model doesn't return by the latency or crashes.
```python
clipper_conn.register_application(name="hello-world", input_type="doubles", 
default_output="-1.0", slo_micros=100000)
```

**Comment by rkooo567** [comment]
Hi, @rp4fx12. Currently, there's no way to customize response code. But the current code already responses with response code 400 or 500 for certain type of request errors. Check out this function in `QueryFrontend`. 
https://github.com/ucbrise/clipper/blob/227c8e46e5a801e9f94e7e42a5bf0b693a5f9919/src/frontends/src/query_frontend.hpp#L314

For the sake of context, I would explain how it works briefly. When you `deploy` your predict function and model, it is deployed wrapped by a RPC server container. You can find code here. https://github.com/ucbrise/clipper/blob/develop/containers/python/rpc.py

When you have API calls, you basically call the `QueryFrontend`, not your model directly. `QueryFrontend` is in charge of batching requests, managing deployed models, versioning, and etc. When you add an application, QueryFrontend creates a POST endpoint with prediction function. The predict function is defined here. (It is inside `add_application` function)https://github.com/ucbrise/clipper/blob/227c8e46e5a801e9f94e7e42a5bf0b693a5f9919/src/frontends/src/query_frontend.hpp#L342

As you can see from code, it already has code for deciding response code.
```
      } catch (const json_parse_error& e) {
        std::string error_msg =
            json_error_msg(e.what(), PREDICTION_JSON_SCHEMA);
        std::string json_error_response = get_prediction_error_response_content(
            PREDICTION_ERROR_NAME_JSON, error_msg);
        respond_http(json_error_response, "400 Bad Request", response);
      } catch (const json_semantic_error& e) {
        std::string error_msg =
            json_error_msg(e.what(), PREDICTION_JSON_SCHEMA);
        std::string json_error_response = get_prediction_error_response_content(
            PREDICTION_ERROR_NAME_JSON, error_msg);
        respond_http(json_error_response, "400 Bad Request", response);
      } catch (const std::invalid_argument& e) {
        // This invalid argument exception is most likely the propagation of an
        // exception thrown
        // when Rapidjson attempts to parse an invalid json schema
        std::string json_error_response = get_prediction_error_response_content(
            PREDICTION_ERROR_NAME_JSON, e.what());
        respond_http(json_error_response, "400 Bad Request", response);
      } catch (const clipper::PredictError& e) {
        std::string error_msg = e.what();
        std::string json_error_response = get_prediction_error_response_content(
            PREDICTION_ERROR_NAME_QUERY_PROCESSING, error_msg);
        respond_http(json_error_response, "400 Bad Request", response);
      } catch (const version_id_error& e) {
        std::string error_msg = e.what();
        std::string json_error_response = get_prediction_error_response_content(
            PREDICTION_ERROR_NAME_QUERY_PROCESSING, error_msg);
        respond_http(json_error_response, "400 Bad Request", response);
      }
```
