### ISSUE TITLE
MXNet default deployment container crashes due to ImportError

### ISSUE THREAD

**Issue by jacekwachowiak** [ucbrise/clipper#673]
I'm trying to run all the possible frameworks and I cannot make mxnet work but I think the error is somewhere inside the mxnet deployer.

I had some problems with submitting a model and a function that would not return a pickle error but after using the #620 issue and following the example from withsmilo I could deploy it correctly. The problem is that the container died after a second and the log says exactly the same as in #611 
```
$ docker logs fa085b429917
Starting MXNetContainer container
Connecting to Clipper with default port: 7000
Encountered an ImportError when running container. You can use the pkgs_to_install argument when calling clipper_admin.build_model() to supply any needed Python packages.
```
I followed the steps shown by @simon-mo:
```
$ docker run -it --entrypoint  "/bin/bash" default-cluster-mxnet-mod:1
root@3428df35d5bd:/container# python
Python 3.6.5 (default, May  5 2018, 03:07:21)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cloudpickle
>>> func = cloudpickle.load(open('/model/func.pkl', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 908, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'mxnet.io.io'; 'mxnet.io' is not a package
```
It seems that there is an `mxnet.io.io` import - maybe the double `io` is incorrect? Anyway, I cannot debug further, has anyone encountered something similar or knows how to fix this?

I can paste here all of the code if needed, but I used the default mxnet deployer container and the python code:
```
def predict(model, xs):
    data_iter = mx.io.NDArrayIter(xs)
    preds = model.predict(data_iter)
    preds = [preds[0]]
    return [str(p) for p in preds]

train_path = "mxnet.data"
data_iter = mx.io.CSVIter(
            data_csv=train_path, data_shape=(785, ), batch_size=1)

# Create a MXNet model
# Configure a two layer neuralnetwork
data = mx.symbol.Variable('data')
fc1 = mx.symbol.FullyConnected(data, name='fc1', num_hidden=128)
act1 = mx.symbol.Activation(fc1, name='relu1', act_type='relu')
fc2 = mx.symbol.FullyConnected(act1, name='fc2', num_hidden=10)
softmax = mx.symbol.SoftmaxOutput(fc2, name='softmax')

# Initialize the module and fit it
mxnet_model = mx.mod.Module(softmax)
mxnet_model.fit(data_iter, num_epoch=0)

train_data_shape = data_iter.provide_data
//////////////////////////////
deploy_mxnet_model(
    clipper_conn,
    name="mxnet-mod",
    version = 1,
    input_type="doubles",
    func=predict,
    mxnet_model=mxnet_model,
    mxnet_data_shapes=train_data_shape,
    batch_size=1)
```

**Comment by rkooo567** [comment]
Seems like you didin't import additional packages in `pkgs_to_install` argument.
```python3
pkgs_to_install (list (of strings), optional) – A list of the names of packages to install, using pip, in the container. The names must be strings.
# From http://docs.clipper.ai/en/v0.3.0/model_deployers.html#mxnet-models
```
 Can you try to add packages to this argument? Something like
```python3
deploy_mxnet_model(
    clipper_conn,
    name="mxnet-mod",
    version = 1,
    input_type="doubles",
    func=predict,
    mxnet_model=mxnet_model,
    mxnet_data_shapes=train_data_shape,
    batch_size=1
    pkgs_to_install=[#and additional packages you import]
)
```

As you can see from this dockerfile, the original container only has `mxnet` as pip dependencies. https://github.com/ucbrise/clipper/blob/develop/dockerfiles/MXNetContainerDockerfile

**Comment by jacekwachowiak** [comment]
But since I am using the default version only and doing:
```
import mxnet as mx
import numpy as np
```
where `numpy` is used for the creation of the query data, what other packages would I need? That argument was not needed with other deployers - pyspark/pytorch/tf.

**Comment by rkooo567** [comment]
@jacekwachowiak I found out clipper generates import error when using `mxnet==1.4.0` version. Can you try using `pip install mxnet==1.1.*` (I tested against 1.3.1 which is the second latest version, and it works as well) and try to run again? I think new version of mxnet has some kinds of dependency issue with Clipper.

**Comment by jacekwachowiak** [comment]
Using version `1.1.0` for the model creation worked well with Clipper, thanks for helping!
