### ISSUE TITLE
Patch Required: Huge size python closure causes an OSError.

### ISSUE THREAD

**Issue by rkooo567** [ucbrise/clipper#681]
## Related issue
This is related to issue https://github.com/ucbrise/clipper/issues/676.

## Problem
Based on the issue, it seems like more than 2GB of pickled python closure raises an OSError due to python's `open` and `write` function (https://bugs.python.org/issue24658) even with `python 3.6.7`. Our python closure can easily have large size because it captures all the data in code including models. The most common example can be using Sklearn in the closure. 

## What should be fixed
Obviously, we should fix `deploy_python_closure `. Most of other model deployers are using `save` function built into models, so it would not cause any problem. For example, pyspark model uses `pysparkmode.save` function. One exception is pytorch. It uses the builtin python open, write functions like `deploy_python_closure `, so we should fix part as well. 

## How to reproduce
Try to deploy a python closure that contains SKLearn model of size >= 4GB.

**Comment by withsmilo** [comment]
The Python developer merged already the following patches to `python 3.6.8` and `python 3.7.*`.
* 3.6
  * https://github.com/python/cpython/pull/9937
  * https://github.com/python/cpython/pull/10659
* 3.7
  * https://github.com/python/cpython/pull/9936
  * https://github.com/python/cpython/pull/10658

**Comment by rkooo567** [comment]
Thanks for the confirmation! I will reproduce https://github.com/ucbrise/clipper/issues/676 with 3.6.8 and close this issue. @withsmilo
