### ISSUE TITLE
start_clipper() failed

### ISSUE THREAD

**Issue by SarnathK** [ucbrise/clipper#688]
I am running into issues while starting **clipper_conn.start_clipper()** More details below. 

My environment: Windows 10, x64 Machine, 4 Cores, 16GB RAM, Docker 2.0.0.3 in Running State, Conda conda 4.5.11, Virtual environment with Python packages : clipper-admin==0.3.0, docker==3.7.2 (installed via pip)

The following errors occur while start_clipper() is called. When I list docker ps , I see many containers running (though the python code below errors out). Details of running images are below the error log.

```
from clipper_admin import ClipperConnection, DockerContainerManager
clipper_conn = ClipperConnection(DockerContainerManager())
clipper_conn.start_clipper()
```

> HTTPError                                 Traceback (most recent call last)
> d:\pypoc\lib\site-packages\docker\api\client.py in _raise_for_status(self, response)
>     260         try:
> --> 261             response.raise_for_status()
>     262         except requests.exceptions.HTTPError as e:
> 
> d:\pypoc\lib\site-packages\requests\models.py in raise_for_status(self)
>     939         if http_error_msg:
> --> 940             raise HTTPError(http_error_msg, response=self)
>     941 
> 
> HTTPError: 400 Client Error: Bad Request for url: http+docker://localnpipe/v1.35/containers/a148bb2d9811acf7ddce1122854a3421557a4ac85f458f501bb1d2540f6f878c/start
> 
> During handling of the above exception, another exception occurred:
> 
> APIError                                  Traceback (most recent call last)
> <ipython-input-3-e64e719f4c6c> in <module>
> ----> 1 clipper_conn.start_clipper()
> 
> d:\pypoc\lib\site-packages\clipper_admin\clipper_admin.py in start_clipper(self, query_frontend_image, mgmt_frontend_image, cache_size, num_frontend_replicas)
>     112         try:
>     113             self.cm.start_clipper(query_frontend_image, mgmt_frontend_image,
> --> 114                                   cache_size, num_frontend_replicas)
>     115             while True:
>     116                 try:
> 
> d:\pypoc\lib\site-packages\clipper_admin\docker\docker_container_manager.py in start_clipper(self, query_frontend_image, mgmt_frontend_image, cache_size, num_frontend_replicas)
>     174                             CLIPPER_INTERNAL_METRIC_PORT)
>     175         run_metric_image(self.docker_client, self.common_labels,
> --> 176                          self.prometheus_port, self.extra_container_kwargs)
>     177 
>     178         self.connect()
> 
> d:\pypoc\lib\site-packages\clipper_admin\docker\docker_metric_utils.py in run_metric_image(docker_client, common_labels, prometheus_port, extra_container_kwargs)
>     115         },
>     116         labels=metric_labels,
> --> 117         **extra_container_kwargs)
>     118 
>     119 
> 
> d:\pypoc\lib\site-packages\docker\models\containers.py in run(self, image, command, stdout, stderr, remove, **kwargs)
>     789                                     detach=detach, **kwargs)
>     790 
> --> 791         container.start()
>     792 
>     793         if detach:
> 
> d:\pypoc\lib\site-packages\docker\models\containers.py in start(self, **kwargs)
>     390                 If the server returns an error.
>     391         """
> --> 392         return self.client.api.start(self.id, **kwargs)
>     393 
>     394     def stats(self, **kwargs):
> 
> d:\pypoc\lib\site-packages\docker\utils\decorators.py in wrapped(self, resource_id, *args, **kwargs)
>      17                     'Resource ID was not provided'
>      18                 )
> ---> 19             return f(self, resource_id, *args, **kwargs)
>      20         return wrapped
>      21     return decorator
> 
> d:\pypoc\lib\site-packages\docker\api\container.py in start(self, container, *args, **kwargs)
>    1089         url = self._url("/containers/{0}/start", container)
>    1090         res = self._post(url)
> -> 1091         self._raise_for_status(res)
>    1092 
>    1093     @utils.check_resource('container')
> 
> d:\pypoc\lib\site-packages\docker\api\client.py in _raise_for_status(self, response)
>     261             response.raise_for_status()
>     262         except requests.exceptions.HTTPError as e:
> --> 263             raise create_api_error_from_http_exception(e)
>     264 
>     265     def _result(self, response, json=False, binary=False):
> 
> d:\pypoc\lib\site-packages\docker\errors.py in create_api_error_from_http_exception(e)
>      29         else:
>      30             cls = NotFound
> ---> 31     raise cls(e, response=response, explanation=explanation)
>      32 
>      33 
> 
> APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp/clipper/prometheus.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/9269a97f34482815d536da1a4593a3e4b2960002922b20fa0e23b37d3f8fad18/merged\\\" at \\\"/var/lib/docker/overlay2/9269a97f34482815d536da1a4593a3e4b2960002922b20fa0e23b37d3f8fad18/merged/etc/prometheus/prometheus.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type")
> 

This is how the docker ps looks like after the error:
D:\>docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

D:\>docker ps

CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                            NAMES
a76ebbe5d0a3        clipper/frontend-exporter:0.3.0     "python /usr/src/app…"   7 seconds ago       Up 4 seconds                                                         query_frontend_exporter-16653
eb2d61c5464f        clipper/query_frontend:0.3.0        "/clipper/release/sr…"   9 seconds ago       Up 7 seconds        0.0.0.0:1337->1337/tcp, 0.0.0.0:7000->7000/tcp   query_frontend-16653
acca704f9261        clipper/management_frontend:0.3.0   "/clipper/release/sr…"   11 seconds ago      Up 8 seconds        0.0.0.0:1338->1338/tcp                           mgmt_frontend-27157
58a4a342ee4a        redis:alpine                        "docker-entrypoint.s…"   13 seconds ago      Up 10 seconds       0.0.0.0:6379->6379/tcp                           redis-2219

**Comment by rkooo567** [comment]
Hi, @SarnathK. Thank you for the question! 

I believe Clipper does not support Windows. As you can see from code here, 
https://github.com/ucbrise/clipper/blob/defb13153f8e55af1abdbe36718e6e9b6fc332b5/clipper_admin/clipper_admin/docker/docker_metric_utils.py#L87, when you run a Prometheus image (which you failed to run by `run_metric_image`), it mounts the config file into `/etc` folder. Windows does not have this folder. One way you can do is to modify this mounted path to be supported by Windows. (You can mount the prometheus config file to the temp folder). 

I recommend using Mac or Linux to use Clipper. But, if you still want to use Windows, you can change the mount path. I cannot 100% guarantee that it will solve all the issues.

**Comment by SarnathK** [comment]
@rkooo567 Thanks for the answer... 

Being in Python and Docker -- I believe Clipper should be able to run in Windows. 

Docker on Windows uses Hyper-V underneath and there are other Docker containers like Redis already running (as you can see towards end of my original message).

Also, Windows has it's own etc folder in c:\windows\etc if indeed this is the problem....

Is running Prometheus absolutely essential to deploy my models? Can I just ignore and move forward..?

Thanks for your time.

**Comment by rkooo567** [comment]
@SarnathK 
Yep. It should technically work, but as you can see, there are some parts that might cause some errors due to native differences between Mac/Linux and Windows (one of examples is the path). Running prometheus is not the essential as far as I know, but it is used to collect metrics, which you might need for your application. Also, commenting out `run_metric_image # this will run prometheus image` from `DockerContainerManager` might be a little tricky because there can be some dependencies in code. You can still take a look at it if you want to try. 

The best way you can do is to add some Windows supports where there are compatibility issues. If you want to do this, instead of using `pip install clipper_admin`, you can download the clipper from Git, and do `pip install -e .` in `clipper_admin` folder (the folder that has `setup.py`). After that you can change the path here to window's etc path. (Follow the link in my previous comment). 

```
metric_cmd = [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--storage.tsdb.path=/prometheus",
        "--web.console.libraries=/etc/prometheus/console_libraries",
        "--web.console.templates=/etc/prometheus/consoles",
        "--web.enable-lifecycle"
    ]
```

I am not sure if it will completely resolve the compatibility. You probably need to find some more parts that are not compatible. If you fix all of them, and if it works on Windows clearly, please feel free to submit a PR!

**Comment by SarnathK** [comment]
@rkooo567 Thank you for your clarification. I moved to Linux and the hello-world app worked like a Charm. Amazing to see so much could be accomplished with just a few calls! This is Amazing! Thanks for such a nice software.
I would request you to document in clipper.ai website that it works only on Linux. I think it can save sometime for someone. I am closing this issue.
Once again, Thanks for your time and your amazing software!

**Comment by rkooo567** [comment]
@SarnathK No problem! We will definitely add this information in the documentation. Thank you for raising an issue!
