### ISSUE TITLE
Question: Why isn't get_metric_addr included in clipper_admin API?

### ISSUE THREAD

**Issue by rkooo567** [ucbrise/clipper#692]
Related: https://github.com/ucbrise/clipper/issues/687.

Based on our API documentation (http://docs.clipper.ai/en/v0.3.0/clipper_connection.html) and code, it seems like ClipperConnection API doesn't include `get_metric_addr`. Is there any special reason for that? Is there other way to access metric address than using `clipper_conn.cm.get_metric_addr()`?

**Comment by withsmilo** [comment]
I think that `get_metric_addr` have to be added to the ClipperConnection API. There is no reason for it to be omitted from the API.

**Comment by rkooo567** [comment]
I will create a PR to handle this real quick.

**Comment by rkooo567** [comment]
PR is merged for this.
