### ISSUE TITLE
Looks like our main build still fails.

### ISSUE THREAD

**Issue by rkooo567** [ucbrise/clipper#703]
```
 [integration_py2_mxnet] Sleep 122 secs before starting a test 
 [integration_py2_mxnet] Starting Trial 0 with timeout 2400.0 seconds 
 [integration_py2_mxnet] Sleep 265 
 [integration_py2_mxnet] Starting Trial 1 with timeout 2400.0 seconds 
 [integration_py2_mxnet] Sleep 390 
 [integration_py2_mxnet] All retry failed. 
CI_test.Makefile:152: recipe for target 'integration_py2_mxnet' failed
make: *** [integration_py2_mxnet] Error 1
make: *** Waiting for unfinished jobs....
```

Sometimes, our mxnet doesn't even start and fail. I think it is one of reasons why our main build is failing. Any idea about why?

**Comment by rkooo567** [comment]
Also, does anyone know why we have tag integration_test_py2 when we use python3?
`python3 ./bin/colorize_output.py --tag integration_py2_mxnet`
https://github.com/ucbrise/clipper/blob/9e41fb24cb2fd2983e10d1aa71e0751e72b7be5c/bin/shipyard/shipyard.py#L121

**Comment by withsmilo** [comment]
### 1. integration_py2_mxnet
The 'integration_py2_mxnet' test failed to start `docker run --rm --network=host -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp         -e CLIPPER_REGISTRY=clipper         -e CL    IPPER_TESTING_DOCKERHUB_PASSWORD=$CLIPPER_TESTING_DOCKERHUB_PASSWORD         clipper/unittests:develop         "python /clipper/integration-tests/deploy_mxnet_models.py"`, but didn't print any error logs. Let's print them.
```
bin/retry_with_timeout.py
@@ -49,7 +49,7 @@ except AssertionError:

 def run_once_with_timeout(command_to_run, timeout):
     proc = subprocess.Popen(
-        command_to_run, stdout=sys.stdout, stderr=subprocess.STDOUT
+        command_to_run, stdout=sys.stdout, stderr=sys.stdout
     )
     start = time.time()
     while True:
```

### 2. python3 ./bin/colorize_output.py --tag integration_py2_mxnet
This is just for printing logs. I think it's not the cause.

**Comment by rkooo567** [comment]
I created a PR #707. Please don't merge the PR.

**Comment by rkooo567** [comment]
Will be resolved with this. https://github.com/ucbrise/clipper/issues/709
