### ISSUE TITLE
Redis connection may be disconnected after a certain period of time

### ISSUE THREAD

**Issue by withsmilo** [ucbrise/clipper#715]
My teammate is testing Clipper with the private k8s cluster, he found a critical bug after some long tests.

The redis connections (redis - mgmt_frontend, redis - query_frontend) might be broken if there is no action during 30 minutes of starting Clipper cluster. The reason for this problem is that the session persistence time of SWLB is set to be short for our k8s cluster.

To resolve this problem, we have to turn on ‘tcp keepalive’ option in redox. I’m going to create a PR this monday.

**Comment by rkooo567** [comment]
Closed with #717
