### ISSUE TITLE
Duplicate `models_used_` field.

### ISSUE THREAD

**Issue by mwhittaker** [ucbrise/clipper#73]
Inside of `datatypes.hpp`, the `Output` class has a [`std::vector<VersionedModelId> models_used_` field](https://github.com/ucbrise/clipper/blob/910d1a31c911018203e4d1926d68659684ad9d6b/src/libclipper/include/clipper/datatypes.hpp#L44). The `Response` class includes an `Output output_` field, but it also includes a [`std::vector<VersionedModelId> models_used_` field](https://github.com/ucbrise/clipper/blob/910d1a31c911018203e4d1926d68659684ad9d6b/src/libclipper/include/clipper/datatypes.hpp#L239-L240)! I'm guessing the repeated `models_used_` was an accident?

**Comment by dcrankshaw** [comment]
Fixed by the change to JSON outputs in #134
