### ISSUE TITLE
[Question] Increasing the number of query frontend rpc services on k8s

### ISSUE THREAD

**Issue by rp4fx12** [ucbrise/clipper#742]
Hi, in this [code block](https://github.com/ucbrise/clipper/blob/v0.3.0/clipper_admin/clipper_admin/kubernetes/kubernetes_container_manager.py#L189)(I think the same logic is in the current released version too), the query frontend rpc service gets created once for every number of query frontend deployment. Does there need to be an rpc service per deployment or can 1 rpc service be used for all of them? To be honest, it would be helpful to understand how clipper would scale in that context.

**Comment by simon-mo** [comment]
Here's an illustration
```
Query Frontend Service (SVC)
------------------------
               |
           /         \
         QF          QF
          |           |
    RPC SVC       RPC SVC
      / / | \ \      / / | \ \
    Models...      Models...
```

RPC service per query frontend is responsible for connecting qf to its models. There is an overarching query frontend service load balance between query frontends.

**Comment by rp4fx12** [comment]
Thanks!
