### ISSUE TITLE
[Question] Is there a way to send the clipper metrics to an external prometheus server?

### ISSUE THREAD

**Issue by rp4fx12** [ucbrise/clipper#743]
Does clipper only log to the prometheus server that is spun up by clipper or is there a way to spin up a prometheus server external to clipper and log there.

**Comment by rkooo567** [comment]
You should definitely connect clipper to your in-house prometheus. (And I think that’s a better solution for production). I think you should change some pod definition to achieve that. @simon or @withsmilo should know more details.

**Comment by simon-mo** [comment]
[Prometheus Federation](https://prometheus.io/docs/prometheus/latest/federation/) can be used here to connect to Clipper prometheus

**Comment by jacekwachowiak** [comment]
I am running an independent Prometheus. You can detect Clipper pods' metrics from there if you allow your external Prometheus to detect and scrape Clipper (or any other) logs.
I used this: https://devopscube.com/setup-prometheus-monitoring-on-kubernetes/ to gather Clipper and system metrics at the same time and use them in Grafana

**Comment by rkooo567** [comment]
@rp4fx12 ^
