### ISSUE TITLE
port collisions with hard-coded redis ports

### ISSUE THREAD

**Issue by shaneknapp** [ucbrise/clipper#76]
the hard-coded port number will cause collisions when the PRB and master build simultaneously.

i suggest something like this in your run_unittests.sh script:

```
set +e  # turn of exit on command fail
REDIS_PORT=$((34256 + RANDOM % 1000))
lsof -i :$REDIS_PORT &> /dev/null

if [ $? -eq 0 ]; then # existing port in use found
  while true; do
    REDIS_PORT=$(($REDIS_PORT + RANDOM % 1000))
    lsof -i :$REDIS_PORT &> /dev/null
    if [ $? -eq 1 ]; then  # port not in use
      break
    fi
  done
fi
export $REDIS_PORT  # if you want to slurp this in to your test_constants before compilation or something
set -e  # turn exit on fail back on
```

now you need to update your test_constants.hpp file to respect this new port.  a couple of ideas:

1) export the REDIS_PORT variable from your bash, and upon compilation, slurp it in and set it that way (i think this should work)
2) stupid unix tricks to the rescue!  sed -i "s/34256/$REDIS_PORT/g" /home/jenkins/workspace/$JOB_NAME/src/libclipper/include/clipper/test_constants.hpp

**Comment by dcrankshaw** [comment]
Fixed by #66
