### ISSUE TITLE
Model Selection 

### ISSUE THREAD

**Issue by lianzhang132** [ucbrise/clipper#761]
How is the Model Selection Policy implemented in the code?I don't see any implementation in the code

**Comment by coldtomatojuice** [comment]
There is currently only one "default selection" policy by which you can select a model registered most recently. You can see how it works from selection_policy.cpp file.
Though you might change the code to select among multiple models, it is for now impossible to link more than one model to an application. So you need to change additional parts to permit multiple model links.

**Comment by lianzhang132** [comment]
Do you have any plans for when the model selection mechanism code will be refined?

**Comment by coldtomatojuice** [comment]
you can refer to this
https://github.com/ucbrise/clipper/issues/683#issuecomment-490291320

**Comment by lianzhang132** [comment]
Ok, thank you very much for your reply
