### ISSUE TITLE
clipper asks for SSH password 

### ISSUE THREAD

**Issue by rmdort** [ucbrise/clipper#94]
When i connect to clipper, even though i am providing the SSH key, clipper still asks for the password. This only happens once. 

````
cm.Clipper(host, user, key)
````

Maybe something to do with Fabric api? I am not logging in as root, but the user has sudo permission

**Comment by dcrankshaw** [comment]
Does it ask for the login password or the SSH key password? If the ssh key is password protected, the underlying [Python SSH library](http://www.paramiko.org/) will prompt for your password.

**Comment by rmdort** [comment]
No. Its asking for the login password. Maybe its because you are running all remote commands as `sudo`?

**Comment by dcrankshaw** [comment]
Oh yeah that's likely it. We've mostly tested this on AWS where the default Ubuntu instances don't require a password for sudo. The problem is that the Docker commands require sudo, so it's independent of SSH access. Did this break things for you?

**Comment by rmdort** [comment]
Oh i see. We mostly run docker without sudo privileges

https://github.com/sindresorhus/guides/blob/master/docker-without-sudo.md

It didnt break anything. Just that i didn't want to expose superuser in our python code when connecting to clipper. 

The other option is adding the user to visudo to require NOPASSWD, which may be a security risk. Am not sure what is the right thing to do here. But would really wish that connecting to clipper can be seamless,  as long as the user has the privileges to the server.

**Comment by dcrankshaw** [comment]
Yeah that totally makes sense. What if we modified clipper_manager so that you could specify whether sudo privileges were needed? If you're running Docker without sudo, then I don't think anything we do would need sudo privileges.

Something like:
```python
clipper = clipper_manager.Clipper(host, user, keypath, sudo=False)
```

**Comment by rmdort** [comment]
Awesome. That will be great 👍  . Thank you.

**Comment by dcrankshaw** [comment]
I just filed https://clipper.atlassian.net/browse/CLIPPER-135 to track this.
