### ISSUE TITLE
Model release cycle

### ISSUE THREAD

**Issue by hrishikeshvganu** [ucbrise/clipper#99]
Do you have plans to support the model release cycle? What I mean is a workflow where:

1. The calling application triggers a model retrain based on deterioration in performance
2. Then a new model could be mounted in place of the old version.

#1 can be handled by the calling application but #2 is where I wanted to know if it's possible to programmatically upload a new version.

**Comment by dcrankshaw** [comment]
Yes this is explicitly supported in Clipper.

Clipper is designed to support frequently retrained models with minimal overhead. A model deployed in Clipper is composed of two elements, the _model container_ and the _model data_. The model container is the code (and any dependencies) needed to evaluate the model. The model data is the state (generally the trained model's parameters in some serialized format) that is loaded when a container is initialized. For frequently retrained models, the code often doesn't change, just the parameters from being trained on new data. This means that the updated model can be deployed without needing to write any code or modify the container at all by deploying a new version of the model with new _model data_. This can all be done programmatically.
